//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\fxy\Desktop\xindlx\GroSideMilling.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: Fengliang
//              Version: NX 11
//              Date: 06-11-2023  (Format: mm-dd-yyyy)
//              Time: 21:04 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "GroSideMilling.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(GroSideMilling::theSession) = NULL;
UI *(GroSideMilling::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
GroSideMilling::GroSideMilling()
{
    try
    {
        // Initialize the NX Open C++ API environment
        GroSideMilling::theSession = NXOpen::Session::GetSession();
        GroSideMilling::theUI = UI::GetUI();
        theDlxFileName = "GroSideMilling.dlx";
        theDialog = GroSideMilling::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &GroSideMilling::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &GroSideMilling::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &GroSideMilling::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &GroSideMilling::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &GroSideMilling::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
GroSideMilling::~GroSideMilling()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    GroSideMilling *theGroSideMilling = NULL;
    try
    {
        theGroSideMilling = new GroSideMilling();
        // The following method shows the dialog immediately
        theGroSideMilling->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GroSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theGroSideMilling != NULL)
    {
        delete theGroSideMilling;
        theGroSideMilling = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GroSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int GroSideMilling::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GroSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void GroSideMilling::initialize_cb()
{
    try
    {
		group41 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group41"));
		bodySelect011 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect011"));
		enumchengxu = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enumchengxu"));
		enumtool = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enumtool"));
		enumfangfa = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enumfangfa"));
		group411 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group411"));
		togglejubu11 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("togglejubu11"));
		bodySelect0111 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect0111"));
		togglenojubu11 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("togglenojubu11"));
		enumpart11 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enumpart11"));
		group4 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group4"));
		label0 = dynamic_cast<NXOpen::BlockStyler::Label*>(theDialog->TopBlock()->FindBlock("label0"));
		face_select0 = dynamic_cast<NXOpen::BlockStyler::FaceCollector*>(theDialog->TopBlock()->FindBlock("face_select0"));
		group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
		tabControl = dynamic_cast<NXOpen::BlockStyler::TabControl*>(theDialog->TopBlock()->FindBlock("tabControl"));
		tabPage = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage"));
		group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));

        enum07 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum07"));
        enum02 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum02"));
       /* toggle0 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0"));
        toggle01 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle01"));
        double012 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double012"));
        double013 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double013"));*/
		integer0 = dynamic_cast<NXOpen::BlockStyler::IntegerBlock*>(theDialog->TopBlock()->FindBlock("integer0"));
		tabPage1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage1"));
        double0 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double0"));
        double011 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double011"));
        double01 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double01"));
        double02 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double02"));
        double03 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double03"));
        double04 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double04"));
        tabPage2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage2"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        enum05 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum05"));
        double06 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double06"));
        enum011 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum011"));
        double05 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double05"));
        enum06 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum06"));
        double07 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double07"));
        double08 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double08"));
        double09 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double09"));
        double010 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double010"));
        enum012 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum012"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        enum03 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum03"));
        plane0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPlane*>(theDialog->TopBlock()->FindBlock("plane0"));
        double014 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double014"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));

		InitialParameters();
		ReadXMLOK = false;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GroSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void GroSideMilling::dialogShown_cb()
{
	InitialParameters();
    try
    {
        //---- Enter your callback code here -----
		PropertyList* toggle003Props = enumpart11->GetProperties();
		toggle003Props->SetLogical("Enable", FALSE);
		delete toggle003Props;

		PropertyList* toggle01Props = togglejubu11->GetProperties();
		toggle01Props->SetLogical("Enable", TRUE);
		toggle01Props->SetLogical("Value", FALSE);
		delete toggle01Props;


		PropertyList* toggle02Props = togglenojubu11->GetProperties();
		toggle02Props->SetLogical("Enable", TRUE);
		toggle02Props->SetLogical("Value", FALSE);
		delete toggle02Props;

		PropertyList* toggle023Props = bodySelect0111->GetProperties();
		toggle023Props->SetLogical("Enable", FALSE);

		delete toggle023Props;

		face_select0->SetFaceRules(1);

		//PropertyList* toggle0111Props = toggle0->GetProperties();
		//toggle0111Props->SetLogical("Enable", TRUE);
		//toggle0111Props->SetLogical("Value", FALSE);
		//delete toggle0111Props;

		//PropertyList* toggle01211Props = toggle01->GetProperties();
		//toggle01211Props->SetLogical("Enable", TRUE);
		//toggle01211Props->SetLogical("Value", FALSE);
		//delete toggle01211Props;

    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GroSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int GroSideMilling::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        GroSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int GroSideMilling::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
		if (block == bodySelect011)
		{
			//---------Enter your code here-----------
			PropertyList* bodySelect0Props = bodySelect011->GetProperties();
			std::vector<NXOpen::TaggedObject *> Bodies = bodySelect0Props->GetTaggedObjectVector("SelectedObjects");
			selectedBody = dynamic_cast<NXOpen::Body*>(Bodies[0]);
			delete bodySelect0Props;

			AllFaces = selectedBody->GetFaces();
			selectpartFlag = TRUE;
		}
		else if (block == enumchengxu)
		{
			//---------Enter your code here-----------
		}
		else if (block == enumtool)
		{
			//---------Enter your code here-----------
		}
		else if (block == enumfangfa)
		{
			//---------Enter your code here-----------
		}
		else if (block == togglejubu11)
		{
			//---------Enter your code here-----------
			PropertyList* toggle05Props = togglejubu11->GetProperties();
			bool jubu = toggle05Props->GetLogical("Value");
			delete toggle05Props;

			if (jubu)
			{
				PropertyList* toggle0411Props = bodySelect0111->GetProperties();
				toggle0411Props->SetLogical("Enable", TRUE);
				delete toggle0411Props;

				PropertyList* toggle041Props = togglenojubu11->GetProperties();
				toggle041Props->SetLogical("Enable", FALSE);
				delete toggle041Props;
				zuobiaoxiFlag = TRUE;

			}
			else
			{
				PropertyList* toggle0411Props = bodySelect0111->GetProperties();
				toggle0411Props->SetLogical("Enable", FALSE);
				delete toggle0411Props;

				PropertyList* toggle041Props = togglenojubu11->GetProperties();
				toggle041Props->SetLogical("Enable", TRUE);
				delete toggle041Props;

			}
		}
		else if (block == bodySelect0111)
		{
			//---------Enter your code here-----------
			PropertyList* bodySelect01Props = bodySelect0111->GetProperties();
			std::vector<NXOpen::TaggedObject *> Bodies = bodySelect01Props->GetTaggedObjectVector("SelectedObjects");
			selectedBlank = dynamic_cast<NXOpen::Body*>(Bodies[0]);
			delete bodySelect01Props;

		}
		else if (block == togglenojubu11)
		{
			//---------Enter your code here-----------
			PropertyList* toggle05Props = togglenojubu11->GetProperties();
			bool nojubu = toggle05Props->GetLogical("Value");
			delete toggle05Props;

			if (nojubu)
			{
				PropertyList* toggle003Props = enumpart11->GetProperties();
				toggle003Props->SetLogical("Enable", TRUE);
				delete toggle003Props;

				PropertyList* toggle001Props = togglejubu11->GetProperties();
				toggle001Props->SetLogical("Enable", FALSE);
				delete toggle001Props;

				zuobiaoxiFlag = TRUE;


			}
			else
			{
				PropertyList* toggle003Props = enumpart11->GetProperties();
				toggle003Props->SetLogical("Enable", FALSE);
				delete toggle003Props;

				PropertyList* toggle001Props = togglejubu11->GetProperties();
				toggle001Props->SetLogical("Enable", TRUE);
				delete toggle001Props;

			}
		}
		else if (block == enumpart11)
		{
			//---------Enter your code here-----------
		}
		else if (block == label0)
		{
			//---------Enter your code here-----------
		}
		else if (block == face_select0)
		{
			//---------Enter your code here-----------
		
			SelectedCavityBottomFaceList.clear();
			BlockStyler::PropertyList * face_select0Props = face_select0->GetProperties();
			std::vector<NXOpen::TaggedObject*> pTaggedObject_FaceList = face_select0Props->GetTaggedObjectVector("SelectedObjects");
			delete face_select0Props;

			int pTaggedObject_FaceListSize = pTaggedObject_FaceList.size();
			Face* SelectedCavityBottomFace;
			for (int i = 0; i != pTaggedObject_FaceListSize; i++)//得到所选择的面
			{
				SelectedCavityBottomFace = dynamic_cast<NXOpen::Face*>(pTaggedObject_FaceList[i]);
				SelectedCavityBottomFaceList.push_back(SelectedCavityBottomFace);
				if (SelectedCavityBottomFaceList.size() == 0)
				{
					uc1601("读取失败!",1);			
				}
				//uc1601("开始，槽已选中!", 1);
			}
			areaFlag = TRUE;

			}
		else if (block == enum07)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum02)
		{
			//---------Enter your code here-----------
		}
		//else if (block == toggle0)//步距
		//{
		//	//---------Enter your code here-----------
		//	PropertyList* toggle0Props = toggle0->GetProperties();
		//	bool stepDisFlag = toggle0Props->GetLogical("Value");
		//	delete toggle0Props;

		//	if (stepDisFlag)
		//	{
		//		PropertyList* double012Props = double012->GetProperties();
		//		double012Props->SetLogical("Enable", TRUE);
		//		delete double012Props;
		//	}
		//	else
		//	{
		//		PropertyList* double012Props = double012->GetProperties();
		//		double012Props->SetLogical("Enable", FALSE);
		//		delete double012Props;
		//	}
		//}
		//else if (block == toggle01)//残余高度
		//{
		//	//---------Enter your code here-----------
		//	PropertyList* toggle01Props = toggle01->GetProperties();
		//	bool multiPathFlag = toggle01Props->GetLogical("Value");
		//	delete toggle01Props;

		//	if (multiPathFlag)
		//	{
		//		PropertyList* double013Props = double013->GetProperties();    //残余高度值
		//		double013Props->SetLogical("Enable", TRUE);
		//		delete double013Props;
		//	}
		//	else
		//	{
		//		PropertyList* double013Props = double013->GetProperties();    //残余高度值
		//		double013Props->SetLogical("Enable", FALSE);
		//		delete double013Props;
		//	}
		//}
		//else if (block == double012)
		//{
		//	//---------Enter your code here-----------
		//}
		//else if (block == double013)
		//{
		//	//---------Enter your code here-----------
		//}
		else if (block == integer0)
		{
			//---------Enter your code here-----------
			/*PropertyList* double012Props = integer0->GetProperties();
			int StepDisAmount = double012Props->GetInteger("Value");
			delete double012Props;
			if (StepDisAmount!=0)
			{
			stepovernuFlag = TRUE;
			}*/
		}
		else if (block == double0)
		{
			//---------Enter your code here-----------
		}
		else if (block == double011)
		{
			//---------Enter your code here-----------
		}
		else if (block == double01)
		{
			//---------Enter your code here-----------
		}
		else if (block == double02)
		{
			//---------Enter your code here-----------
		}
		else if (block == double03)
		{
			//---------Enter your code here-----------
		}
		else if (block == double04)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum05)
		{
			//---------Enter your code here-----------
			PropertyList* enum05Props = enum05->GetProperties();
			int ToolApproachType = enum05Props->GetEnum("Value");
			delete enum05Props;

			if (ToolApproachType == 0)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();   //直线进刀的距离
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();    //圆弧半径
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();    //旋转角度
				double07Props->SetLogical("Enable", TRUE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();     //倾斜角度
				double08Props->SetLogical("Enable", FALSE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();     //圆弧角度
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();    //线性延伸
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 1)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();   //直线进刀的距离
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();     //圆弧半径
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();    //旋转角度
				double07Props->SetLogical("Enable", FALSE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();     //倾斜角度
				double08Props->SetLogical("Enable", TRUE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();     //圆弧角度
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();    //线性延伸
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 2)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();   //直线进刀的距离
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();     //圆弧半径
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();    //旋转角度
				double07Props->SetLogical("Enable", FALSE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();     //倾斜角度
				double08Props->SetLogical("Enable", FALSE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();     //圆弧角度
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();    //线性延伸
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 3)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetEnumAsString("Value", "%刀具");
				enum011Props->SetLogical("Enable", TRUE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();   //直线进刀的距离
				double06Props->SetDouble("Value", 100);
				double06Props->SetLogical("Enable", TRUE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", FALSE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();     //圆弧半径
				double05Props->SetLogical("Enable", FALSE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();    //旋转角度
				double07Props->SetDouble("Value", 0);
				double07Props->SetLogical("Enable", TRUE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();     //倾斜角度
				double08Props->SetDouble("Value", 0);
				double08Props->SetLogical("Enable", TRUE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();     //圆弧角度
				double09Props->SetLogical("Enable", FALSE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();    //线性延伸
				double010Props->SetLogical("Enable", FALSE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", FALSE);
				delete enum012Props;
			}
		}
		else if (block == double06)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum011)
		{
			//---------Enter your code here-----------
		}
		else if (block == double05)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum06)
		{
			//---------Enter your code here-----------
		}
		else if (block == double07)
		{
			//---------Enter your code here-----------
		}
		else if (block == double08)
		{
			//---------Enter your code here-----------
		}
		else if (block == double09)
		{
			//---------Enter your code here-----------
		}
		else if (block == double010)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum012)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum03)
		{
			//---------Enter your code here-----------
		}
		else if (block == plane0)
		{
			//---------Enter your code here-----------
		}
		else if (block == double014)
		{
			//---------Enter your code here-----------
		}
		else if (block == button0)
		{
			//---------Enter your code here-----------
			
			//程序、刀具、几何体、方法

			if (selectpartFlag == FALSE)
			{
				uc1601("请先完成零件实体模型设置,再开始加工刀轨", 1);
				//break;
			}
			else if (zuobiaoxiFlag == FALSE)
			{
				uc1601("请先完成坐标系与几何体设置,再开始加工刀轨", 1);
			}
			else if (areaFlag == FALSE)
			{
				uc1601("请先完成加工区域设置,再开始加工刀轨", 1);
			}
			/*else if (stepovernuFlag == FALSE)
			{
				uc1601("请先完成步距数设置,再开始加工刀轨", 1);
			}*/
			else if (selectpartFlag == TRUE && areaFlag == TRUE && zuobiaoxiFlag == TRUE )
			{


				PropertyList* enum010Props = enumchengxu->GetProperties();
				ParameterSet_Huan.PROGRAM = enum010Props->GetEnumAsString("Value");
				delete enum010Props;

				PropertyList* enum01Props = enumtool->GetProperties();
				NXString tempToolName = enum01Props->GetEnumAsString("Value");
				const char* tempToolNameChar = tempToolName.GetUTF8Text();
				ParameterSet_Huan.ToolMsg.ToolName = tempToolName;
				delete enum01Props;

				PropertyList* enum0Props = enumpart11->GetProperties();
				ParameterSet_Huan.GeomtryMCS = enum0Props->GetEnumAsString("Value");
				delete enum0Props;

				PropertyList* enum08Props = enumfangfa->GetProperties();
				ParameterSet_Huan.METHOD = enum08Props->GetEnumAsString("Value");
				delete enum08Props;


				PropertyList* toggle05Props = togglejubu11->GetProperties();
				ParameterSet_Huan.IfLCsys = toggle05Props->GetLogical("Value");
				delete toggle05Props;


				for (std::vector<NXString>::size_type n = 0; n != ToolStringList.size(); n++)
				{
					NXString nToolName = ToolStringList[n];
					const char* nToolNameChar = nToolName.GetUTF8Text();
					if (lstrcmp(nToolNameChar, tempToolNameChar) == 0)
					{
						NXOpen::CAM::CAMObject* EachMember = ToolMembers[n + 1];
						CAM::MillToolBuilder* millToolBuilder1;
						millToolBuilder1 = workPart->CAMSetup()->CAMGroupCollection()->CreateMillToolBuilder(dynamic_cast<CAM::Tool*>(EachMember));

						ParameterSet_Huan.ToolMsg.ToolDiameter = millToolBuilder1->TlDiameterBuilder()->Value();
						double tempvalue = millToolBuilder1->TlTaperAngBuilder()->Value();
						ParameterSet_Huan.ToolMsg.ToolCorner = millToolBuilder1->TlLowCorRadBuilder()->Value();
						ParameterSet_Huan.ToolMsg.ToolLength = millToolBuilder1->TlHeightBuilder()->Value();
						ParameterSet_Huan.ToolMsg.ToolFluteLength = millToolBuilder1->TlFluteLnBuilder()->Value();
					}
				}

				//切削策略


				PropertyList* enum07Props = enum07->GetProperties();
				ParameterSet_Huan.CuttingDirection = enum07Props->GetEnum("Value");
				delete enum07Props;

				PropertyList* enum02Props = enum02->GetProperties();
				ParameterSet_Huan.CuttingMode = enum02Props->GetEnum("Value");
				delete enum02Props;

				//步距
				/*PropertyList* toggle0Props = toggle0->GetProperties();
				ParameterSet_Huan.StepDisFlag = toggle0Props->GetLogical("Value");
				delete toggle0Props;*/

				PropertyList* double012Props = integer0->GetProperties();
				ParameterSet_Huan.StepDisAmount = double012Props->GetInteger("Value");
				delete double012Props;

				//残余高度
				//PropertyList* toggle01Props = toggle01->GetProperties();
				//ParameterSet_Huan.ScallopHeightFlag = toggle01Props->GetLogical("Value");
				//delete toggle01Props;

				//PropertyList* double013Props = double013->GetProperties();
				//ParameterSet_Huan.ScallopHeightAmount = double013Props->GetDouble("Value");
				//delete double013Props;

				//切削参数
				PropertyList* double0Props = double0->GetProperties();
				ParameterSet_Huan.Tolerance = double0Props->GetDouble("Value");
				delete double0Props;

				PropertyList* double011Props = double011->GetProperties();
				ParameterSet_Huan.PartAllowance = double011Props->GetDouble("Value");
				delete double011Props;

				PropertyList* double01Props = double01->GetProperties();
				ParameterSet_Huan.SpindleSpeed = double01Props->GetDouble("Value");
				delete double01Props;

				PropertyList* double02Props = double02->GetProperties();
				ParameterSet_Huan.Machining = double02Props->GetDouble("Value");
				delete double02Props;

				PropertyList* double03Props = double03->GetProperties();
				ParameterSet_Huan.Approach = double03Props->GetDouble("Value");
				delete double03Props;

				PropertyList* double04Props = double04->GetProperties();
				ParameterSet_Huan.Retract = double04Props->GetDouble("Value");
				delete double04Props;

				//非切削移动 之进退刀
				PropertyList* enum05Props = enum05->GetProperties();
				ParameterSet_Huan.ToolMotion.ToolMotionType = enum05Props->GetEnum("Value");
				delete enum05Props;
				//距离
				PropertyList* enum011Props = enum011->GetProperties();
				ParameterSet_Huan.ToolMotion.ToolMotionDistanceUnit = enum011Props->GetEnum("Value");
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				ParameterSet_Huan.ToolMotion.ToolMotionDistance = double06Props->GetDouble("Value");
				delete double06Props;
				//半径
				PropertyList* enum06Props = enum06->GetProperties();
				ParameterSet_Huan.ToolMotion.CircleRadiusUnit = enum06Props->GetEnum("Value");
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				ParameterSet_Huan.ToolMotion.CircleRadius = double05Props->GetDouble("Value");
				delete double05Props;
				//三个角度
				PropertyList* double07Props = double07->GetProperties();
				ParameterSet_Huan.ToolMotion.RotationAngle = double07Props->GetDouble("Value");
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				ParameterSet_Huan.ToolMotion.TiltAngle = double08Props->GetDouble("Value");
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				ParameterSet_Huan.ToolMotion.CircleAngle = double09Props->GetDouble("Value");
				delete double09Props;
				//线性延伸
				PropertyList* enum012Props = enum012->GetProperties();
				ParameterSet_Huan.ToolMotion.LinearExtensionUnit = enum012Props->GetEnum("Value");
				delete enum012Props;

				PropertyList* double010Props = double010->GetProperties();
				ParameterSet_Huan.ToolMotion.LinearExtension = double010Props->GetDouble("Value");
				delete double010Props;

				//非切削移动 之公共安全设置
				PropertyList* enum03Props = enum03->GetProperties();
				ParameterSet_Huan.SafeSetType = enum03Props->GetEnum("Value");
				delete enum03Props;

				PropertyList* double014Props = double014->GetProperties();
				ParameterSet_Huan.SafeSetOffset = double014Props->GetDouble("Value");
				delete double014Props;
				//uc1601("进入环形槽工艺编程！", 1);

				AnnulusCavityBottomMillingCmd* AnnulusCavityBottomMilling = new AnnulusCavityBottomMillingCmd(ListOfCavity_Huanout, ListOfBoss, ParameterSet_Huan, workPart, selectedBody, selectedBlank, SelectedCavityBottomFaceList);
				uc1601("完成编程！", 1);
			}
		}
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GroSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int GroSideMilling::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        GroSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* GroSideMilling::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

BSTR GroSideMilling::ConvertToBSTR(NXString iString)
{
	char* istr = (char*)iString.GetUTF8Text();
	BSTR bstr = _com_util::ConvertStringToBSTR(istr);
	return bstr;
}

NXString GroSideMilling::ConvertToString(BSTR bstr)
{
	char* istr = _com_util::ConvertBSTRToString(bstr);
	NXString str(istr);
	return str;
}


void GroSideMilling::InitialParameters()
{
	NXOpen::Session *theSession = NXOpen::Session::GetSession();
	workPart = theSession->Parts()->Work();
	theSession->CreateCamSession();

	//-------------------设置所有的程序组  即 program
	CAM::NCGroup *nCGroup010(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NC_PROGRAM")));
	ProgramMembers = nCGroup010->GetMembers();
	int ProgramMemberSize = ProgramMembers.size();
	ProgramStringList.clear();
	for (int i = 1; i < ProgramMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = ProgramMembers[i];
		NXString EachMemberstr = EachMember->Name();               //也可以用GetObject来获取名字
		ProgramStringList.push_back(EachMemberstr);
	}
	PropertyList* enum010Props = enumchengxu->GetProperties();
	enum010Props->SetEnumMembers("Value", ProgramStringList);
	delete enum010Props;

	//--------------------设置所有的刀具
	CAM::NCGroup* nCGroup01(dynamic_cast<CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("GENERIC_MACHINE")));
	ToolMembers = nCGroup01->GetMembers();
	int ToolMemberSize = ToolMembers.size();
	ToolStringList.clear();
	for (int i = 1; i < ToolMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = ToolMembers[i];
		NXString EachMemberstr = EachMember->Name();
		ToolStringList.push_back(EachMemberstr);
	}
	PropertyList* enum01Props = enumtool->GetProperties();
	enum01Props->SetEnumMembers("Value", ToolStringList);
	delete enum01Props;

	//-------------------设置所有的MCS/几何体  
	CAM::NCGroup *nCGroup0(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("GEOMETRY")));
	MCSMembers = nCGroup0->GetMembers();
	int MCSMemberSize = MCSMembers.size();
	MCSStringList.clear();
	NXString MCS_name = "MCS_MILL";
	MCSStringList.push_back(MCS_name);
	//for (int i = 1; i < MCSMemberSize; i++)
	//{
	//	NXOpen::CAM::CAMObject* EachMember = MCSMembers[i];
	//	NXString EachMemberstr = EachMember->Name();
	//	MCSStringList.push_back(EachMemberstr);
	//}
	PropertyList* enum0Props = enumpart11->GetProperties();
	enum0Props->SetEnumMembers("Value", MCSStringList);
	delete enum0Props;

	//-------------------设置所有的方法  
	CAM::NCGroup *nCGroup08(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
	MethodMembers = nCGroup08->GetMembers();
	int MethodMemberSize = MethodMembers.size();
	MethodStringList.clear();
	for (int i = 1; i < MethodMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = MethodMembers[i];
		NXString EachMemberstr = EachMember->Name();
		MethodStringList.push_back(EachMemberstr);
	}
	PropertyList* enum08Props = enumfangfa->GetProperties();
	enum08Props->SetEnumMembers("Value", MethodStringList);
	delete enum08Props;

	//切削策略

	PropertyList* enum07Props = enum07->GetProperties();
	enum07Props->SetEnumAsString("Value", "順铣");
	delete enum07Props;

	PropertyList* enum02Props = enum02->GetProperties();   //凸台顶面面铣 用单向驱动
	enum02Props->SetEnumAsString("Value", "单向");
	delete enum02Props;

	PropertyList* int014Props = integer0->GetProperties();
	int014Props->SetInteger("Value", 0);
	delete int014Props;

	//PropertyList* double012Props = double012->GetProperties();  //步距数
	//double012Props->SetDouble("Value", 3);
	//double012Props->SetLogical("Enable", FALSE);
	//delete double012Props;

	//PropertyList* double013Props = double013->GetProperties();    //残余高度值
	//double013Props->SetDouble("Value", 0.15);
	//double013Props->SetLogical("Enable", FALSE);
	//delete double013Props;


	//切削参数
	PropertyList* double0Props = double0->GetProperties();       //公差
	double0Props->SetDouble("Value", 0.03);
	delete double0Props;

	PropertyList* double011Props = double011->GetProperties();   //部件余量
	double011Props->SetDouble("Value", 0);
	delete double011Props;

	PropertyList* double01Props = double01->GetProperties();     //主轴转速
	double01Props->SetDouble("Value", 8000);
	delete double01Props;

	PropertyList* double02Props = double02->GetProperties();     //进给速度
	double02Props->SetDouble("Value", 8000);
	delete double02Props;

	PropertyList* double03Props = double03->GetProperties();     //进刀速度
	double03Props->SetDouble("Value", 6000);
	delete double03Props;

	PropertyList* double04Props = double04->GetProperties();     //退刀速度
	double04Props->SetDouble("Value", 6000);
	delete double04Props;

	//非切削移动之 进退刀设置
	PropertyList* enum05Props = enum05->GetProperties();
	enum05Props->SetEnumAsString("Value", "圆弧-平行于刀轴");
	delete enum05Props;

	PropertyList* enum011Props = enum011->GetProperties();
	enum011Props->SetEnumAsString("Value", "%刀具");
	enum011Props->SetLogical("Enable", FALSE);
	delete enum011Props;

	PropertyList* double06Props = double06->GetProperties();
	double06Props->SetDouble("Value", 100);
	double06Props->SetLogical("Enable", FALSE);
	delete double06Props;

	PropertyList* enum06Props = enum06->GetProperties();
	enum06Props->SetEnumAsString("Value", "%刀具");
	enum06Props->SetLogical("Enable", TRUE);
	delete enum06Props;

	PropertyList* double05Props = double05->GetProperties();
	double05Props->SetDouble("Value", 50);
	double05Props->SetLogical("Enable", TRUE);
	delete double05Props;

	PropertyList* double07Props = double07->GetProperties();    //旋转角度
	double07Props->SetDouble("Value", 0);
	double07Props->SetLogical("Enable", FALSE);
	delete double07Props;

	PropertyList* double08Props = double08->GetProperties();     //倾斜角度
	double08Props->SetDouble("Value", 0);
	double08Props->SetLogical("Enable", FALSE);
	delete double08Props;

	PropertyList* double09Props = double09->GetProperties();     //圆弧角度
	double09Props->SetDouble("Value", 90);
	double09Props->SetLogical("Enable", TRUE);
	delete double09Props;

	PropertyList* double010Props = double010->GetProperties();    //高度
	double010Props->SetDouble("Value", 0);
	double010Props->SetLogical("Enable", TRUE);
	delete double010Props;

	PropertyList* enum012Props = enum012->GetProperties();
	enum012Props->SetEnumAsString("Value", "mm");
	enum012Props->SetLogical("Enable", TRUE);
	delete enum012Props;

	//非切削移动之 公共安全设置
	PropertyList* enum03Props = enum03->GetProperties();
	enum03Props->SetEnumAsString("Value", "包容圆柱体");
	delete enum03Props;

	PropertyList* plane0Props = plane0->GetProperties();
	plane0Props->SetLogical("Enable", FALSE);
	delete plane0Props;

	PropertyList* double014Props = double014->GetProperties();
	double014Props->SetDouble("Value", 30);
	delete double014Props;
}

