//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\PRO_code\20231019刀具库\cutting_database.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 10-20-2023  (Format: mm-dd-yyyy)
//              Time: 17:18 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "cutting_database.hpp"

using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(cutting_database::theSession) = NULL;
UI *(cutting_database::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
cutting_database::cutting_database()
{
    try
    {
        // Initialize the NX Open C++ API environment
        cutting_database::theSession = NXOpen::Session::GetSession();
        cutting_database::theUI = UI::GetUI();
        theDlxFileName = "cutting_database.dlx";
        theDialog = cutting_database::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &cutting_database::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &cutting_database::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &cutting_database::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &cutting_database::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &cutting_database::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
cutting_database::~cutting_database()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
	UF_initialize();
    cutting_database *thecutting_database = NULL;
    try
    {
        thecutting_database = new cutting_database();
        // The following method shows the dialog immediately
        thecutting_database->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        cutting_database::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(thecutting_database != NULL)
    {
        delete thecutting_database;
        thecutting_database = NULL;
    }
	UF_terminate();
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        cutting_database::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int cutting_database::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        cutting_database::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void cutting_database::initialize_cb()
{
    try
    {
        nativeFileBrowser0 = dynamic_cast<NXOpen::BlockStyler::FileSelection*>(theDialog->TopBlock()->FindBlock("nativeFileBrowser0"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        list_box0 = dynamic_cast<NXOpen::BlockStyler::ListBox*>(theDialog->TopBlock()->FindBlock("list_box0"));
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
        enum03 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum03"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        enum02 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum02"));
        button03 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button03"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        group4 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group4"));
        double05 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double05"));
        double06 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double06"));
        double07 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double07"));
        double04 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double04"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        double08 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double08"));
        double09 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double09"));
        double01 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double01"));
        double02 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double02"));
        double03 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double03"));
        double0 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double0"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        button02 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button02"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        button01 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        //------------------------------------------------------------------------------
        //Registration of ListBox specific callbacks
        //------------------------------------------------------------------------------
        //list_box0->SetAddHandler(make_callback(this, &cutting_database::AddCallback));
        
        //list_box0->SetDeleteHandler(make_callback(this, &cutting_database::DeleteCallback));
        
        //------------------------------------------------------------------------------
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        cutting_database::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void cutting_database::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        cutting_database::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int cutting_database::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        cutting_database::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int cutting_database::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == nativeFileBrowser0)
        {
        //---------Enter your code here-----------
			ReadExcelFile();
			ReadEXCELOK = true;			

        }
        else if(block == list_box0)
        {
        //---------Enter your code here-----------
			int iRowIndex;
			NXString FeatureName;

			GetSelectedIndexAndFeatureName(iRowIndex, FeatureName);

			ResponseToFeatureList(iRowIndex, FeatureName);

			/*uc1601("进入显示列表", 1);*/

        }
        else if(block == enum01)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum03)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum02)
        {
        //---------Enter your code here-----------
        }
        else if(block == button03)
        {
        //---------Enter your code here-----------
			for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
				CuttingDataLib[i]->CutterTypeLable = false;
				CuttingDataLib[i]->CuttingFeatureLable = false;
				CuttingDataLib[i]->CuttingMaterialLable = false;
				CuttingDataLib[i]->ProcessingStageLable = false;
			}

			string strEnum01;
			BlockStyler::PropertyList * Featureselect01Props = enum01->GetProperties();
			NXString nxStrEnum01 = Featureselect01Props->GetEnumAsString("Value");
			delete Featureselect01Props;
			char crstring01[133] = "";
			strcpy_s(crstring01, 133, nxStrEnum01.GetLocaleText());
			strEnum01 = crstring01;

			if (strEnum01 == "铣刀")
			{
				/*uc1601("铣刀", 1);*/
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 1)
					{
						CuttingDataLib[i]->CutterTypeLable = true;						
					}
						
				}
			}
			else if (strEnum01 == "钻刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 2)
					{
						CuttingDataLib[i]->CutterTypeLable = true;						
					}						
				}
			}
			else if (strEnum01 == "点钻刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 3)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}
			else if (strEnum01 == "螺纹铣刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 4)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}
			else if (strEnum01 == "铰刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 5)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}
			else if (strEnum01 == "镗刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 6)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}

//------------------------------------------------------------------------------
			/*for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
			if (CuttingDataLib[i]->CutterTypeLable == true)
			{
			char message[30];
			UF_UI_open_listing_window();

			sprintf(message, "%d\n", CuttingDataLib[i]->CutterType);
			UF_UI_write_listing_window(message);
			}
			}*/
//------------------------------------------------------------------------------
			string strEnum03;
			BlockStyler::PropertyList * Featureselect03Props = enum03->GetProperties();
			NXString nxStrEnum03 = Featureselect03Props->GetEnumAsString("Value");
			delete Featureselect03Props;
			char crstring03[133] = "";
			strcpy_s(crstring03, 133, nxStrEnum03.GetLocaleText());
			strEnum03 = crstring03;

			if (strEnum03 == "凸台类")
			{
				/*uc1601("凸台类", 1);*/
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingFeature == 1)
					{
						CuttingDataLib[i]->CuttingFeatureLable = true;
					}
				}
			}
			else if (strEnum03 == "筋类")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingFeature == 2)
					{
						CuttingDataLib[i]->CuttingFeatureLable = true;
					}
				}
			}
			else if (strEnum03 == "孔类")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingFeature == 3)
					{
						CuttingDataLib[i]->CuttingFeatureLable = true;
					}
				}
			}
			else if (strEnum03 == "槽类")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingFeature == 4)
					{
						CuttingDataLib[i]->CuttingFeatureLable = true;
					}
				}
			}
//---------------------------------------------------------------------------------------------
			/*for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
				if (CuttingDataLib[i]->CuttingFeatureLable == true)
				{
					char message[30];
					UF_UI_open_listing_window();

					sprintf(message, "%d\n", CuttingDataLib[i]->CuttingFeature);
					UF_UI_write_listing_window(message);
				}
			}*/
//---------------------------------------------------------------------------------------------
			string strEnum0;
			BlockStyler::PropertyList * Featureselect0Props = enum0->GetProperties();
			NXString nxStrEnum0 = Featureselect0Props->GetEnumAsString("Value");
			delete Featureselect0Props;
			char crstring0[133] = "";
			strcpy_s(crstring0, 133, nxStrEnum0.GetLocaleText());
			strEnum0 = crstring0;

			if (strEnum0 == "GH4169")
			{
				/*uc1601("GH4169", 1);*/
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingMaterial == 1)
					{
						CuttingDataLib[i]->CuttingMaterialLable = true;
					}
				}
			}
			else if (strEnum0 == "GH4169D")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingMaterial == 2)
					{
						CuttingDataLib[i]->CuttingMaterialLable = true;
					}
				}
			}
			else if (strEnum0 == "GH141")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingMaterial == 3)
					{
						CuttingDataLib[i]->CuttingMaterialLable = true;
					}
				}
			}
//--------------------------------------------------------------------------------------
			/*for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
				if (CuttingDataLib[i]->CuttingMaterialLable == true)
				{
					char message[30];
					UF_UI_open_listing_window();

					sprintf(message, "%d\n", CuttingDataLib[i]->CuttingMaterial);
					UF_UI_write_listing_window(message);
				}
			}*/
//--------------------------------------------------------------------------------------
			string strEnum02;
			BlockStyler::PropertyList * Featureselect02Props = enum02->GetProperties();
			NXString nxStrEnum02 = Featureselect02Props->GetEnumAsString("Value");
			delete Featureselect02Props;
			char crstring02[133] = "";
			strcpy_s(crstring02, 133, nxStrEnum02.GetLocaleText());
			strEnum02 = crstring02;

			if (strEnum02 == "粗加工")
			{
				
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->ProcessingStage == 1)
					{
						CuttingDataLib[i]->ProcessingStageLable = true;
					}
				}
			}
			else if (strEnum02 == "半精加工")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->ProcessingStage == 2)
					{
						CuttingDataLib[i]->ProcessingStageLable = true;
					}
				}
			}
			else if (strEnum02 == "精加工")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->ProcessingStage == 3)
					{
						CuttingDataLib[i]->ProcessingStageLable = true;
					}
				}
			}
//------------------------------------------------------------------------------------------------
			/*for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
				if (CuttingDataLib[i]->ProcessingStageLable == true)
				{
					char message[30];
					UF_UI_open_listing_window();

					sprintf(message, "%d\n", CuttingDataLib[i]->ProcessingStage);
					UF_UI_write_listing_window(message);
				}
			}*/
//------------------------------------------------------------------------------------------------
			Showlist.clear();
			NotShowlist.clear();

			for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
				if (CuttingDataLib[i]->CutterTypeLable == true && CuttingDataLib[i]->CuttingFeatureLable == true &&
					CuttingDataLib[i]->CuttingMaterialLable == true && CuttingDataLib[i]->ProcessingStageLable == true)
				{
					Showlist.push_back(CuttingDataLib[i]);
				}	
				else
				{
					NotShowlist.push_back(CuttingDataLib[i]);
				}
			}

			if (Showlist.size() == 0)
				uc1601("没有符合选项的刀具！", 1);
//------------------------------------------------------------------------------------------------
			/*char message[30];
			UF_UI_open_listing_window();
			sprintf(message, "%d\n", Showlist.size());
			UF_UI_write_listing_window(message);*/
//------------------------------------------------------------------------------------------------
			CuttingdataDisplay();

        }
        else if(block == double05)
        {
        //---------Enter your code here-----------
        }
        else if(block == double06)
        {
        //---------Enter your code here-----------
        }
        else if(block == double07)
        {
        //---------Enter your code here-----------
        }
        else if(block == double04)
        {
        //---------Enter your code here-----------
        }
        else if(block == double08)
        {
        //---------Enter your code here-----------
        }
        else if(block == double09)
        {
        //---------Enter your code here-----------
        }
        else if(block == double01)
        {
        //---------Enter your code here-----------
        }
        else if(block == double02)
        {
        //---------Enter your code here-----------
        }
        else if(block == double03)
        {
        //---------Enter your code here-----------
        }
        else if(block == double0)
        {
        //---------Enter your code here-----------
        }
        else if(block == button02)
        {
        //---------Enter your code here-----------
			uc1601("注意！该操作会同时修改列表中所有已展开刀具！", 1);
			if (Showlist.size() > 0)
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != Showlist.size(); i++)
				{
					if (Showlist[i]->ifselect == true)
					{
						PropertyList* double05Props = double05->GetProperties();
						Showlist[i]->ToolDiameter = double05Props->GetDouble("Value");
						delete double05Props;

						PropertyList* double06Props = double06->GetProperties();
						Showlist[i]->ToolCorner = double06Props->GetDouble("Value");
						delete double06Props;

						PropertyList* double07Props = double07->GetProperties();
						Showlist[i]->ToolLength = double07Props->GetDouble("Value");
						delete double07Props;

						PropertyList* double04Props = double04->GetProperties();
						Showlist[i]->ToolFluteLength = double04Props->GetDouble("Value");
						delete double04Props;

						PropertyList* double08Props = double08->GetProperties();
						Showlist[i]->Tolerance = double08Props->GetDouble("Value");
						delete double08Props;

						PropertyList* double09Props = double09->GetProperties();
						Showlist[i]->PartAllowance = double09Props->GetDouble("Value");
						delete double09Props;

						PropertyList* double01Props = double01->GetProperties();
						Showlist[i]->Machining = double01Props->GetDouble("Value");
						delete double01Props;

						PropertyList* double02Props = double02->GetProperties();
						Showlist[i]->Approach = double02Props->GetDouble("Value");
						delete double02Props;

						PropertyList* double03Props = double03->GetProperties();
						Showlist[i]->Retract = double03Props->GetDouble("Value");
						delete double03Props;

						PropertyList* double0Props = double0->GetProperties();
						Showlist[i]->SpindleSpeed = double0Props->GetDouble("Value");
						delete double0Props;

					}
				}
				CuttingdataDisplay();

				CuttingDataLib.clear();
				CuttingDataLib.insert(CuttingDataLib.end(), Showlist.begin(), Showlist.end());
				CuttingDataLib.insert(CuttingDataLib.end(), NotShowlist.begin(), NotShowlist.end());

				std::string FileString(constFileCharString[0].GetUTF8Text());
				const char*FileCharString = FileString.data();

				PrintCsvCuttingData(FileCharString);
			}

			else
				uc1601("请先点开任意刀具！", 1);
        }
        else if(block == button0)
        {
        //---------Enter your code here-----------
			string strEnum01;
			BlockStyler::PropertyList * Featureselect01Props = enum01->GetProperties();
			NXString nxStrEnum01 = Featureselect01Props->GetEnumAsString("Value");
			delete Featureselect01Props;
			char crstring01[133] = "";
			strcpy_s(crstring01, 133, nxStrEnum01.GetLocaleText());
			strEnum01 = crstring01;

			Cuttingdata *cuttingdatacase = new Cuttingdata;


			if (strEnum01 == "铣刀")
			{
				/*uc1601("铣刀", 1);*/
				cuttingdatacase->CutterType = 1;
			}
			else if (strEnum01 == "钻刀")
			{
				cuttingdatacase->CutterType = 2;
			}
			else if (strEnum01 == "点钻刀")
			{
				cuttingdatacase->CutterType = 3;
			}
			else if (strEnum01 == "螺纹铣刀")
			{
				cuttingdatacase->CutterType = 4;
			}
			else if (strEnum01 == "铰刀")
			{
				cuttingdatacase->CutterType = 5;
			}
			else if (strEnum01 == "镗刀")
			{
				cuttingdatacase->CutterType = 6;
			}
//---------------------------------------------------------------------------------------------------
			string strEnum03;
			BlockStyler::PropertyList * Featureselect03Props = enum03->GetProperties();
			NXString nxStrEnum03 = Featureselect03Props->GetEnumAsString("Value");
			delete Featureselect03Props;
			char crstring03[133] = "";
			strcpy_s(crstring03, 133, nxStrEnum03.GetLocaleText());
			strEnum03 = crstring03;

			if (strEnum03 == "凸台类")
			{
				cuttingdatacase->CuttingFeature = 1;
			}

			else if (strEnum03 == "筋类")
			{
				cuttingdatacase->CuttingFeature = 2;
			}
			else if (strEnum03 == "孔类")
			{
				cuttingdatacase->CuttingFeature = 3;
			}
			else if (strEnum03 == "槽类")
			{
				cuttingdatacase->CuttingFeature = 4;
			}
//---------------------------------------------------------------------------------------------
			string strEnum0;
			BlockStyler::PropertyList * Featureselect0Props = enum0->GetProperties();
			NXString nxStrEnum0 = Featureselect0Props->GetEnumAsString("Value");
			delete Featureselect0Props;
			char crstring0[133] = "";
			strcpy_s(crstring0, 133, nxStrEnum0.GetLocaleText());
			strEnum0 = crstring0;

			if (strEnum0 == "GH4169")
			{
				cuttingdatacase->CuttingMaterial = 1;
			}
			else if (strEnum0 == "GH4169D")
			{
				cuttingdatacase->CuttingMaterial = 2;
			}
			else if (strEnum0 == "GH141")
			{
				cuttingdatacase->CuttingMaterial = 3;
			}
//--------------------------------------------------------------------------------------
			string strEnum02;
			BlockStyler::PropertyList * Featureselect02Props = enum02->GetProperties();
			NXString nxStrEnum02 = Featureselect02Props->GetEnumAsString("Value");
			delete Featureselect02Props;
			char crstring02[133] = "";
			strcpy_s(crstring02, 133, nxStrEnum02.GetLocaleText());
			strEnum02 = crstring02;

			if (strEnum02 == "粗加工")
			{
				cuttingdatacase->ProcessingStage = 1;
			}
			else if (strEnum02 == "半精加工")
			{
				cuttingdatacase->ProcessingStage = 2;
			}
			else if (strEnum02 == "精加工")
			{
				cuttingdatacase->ProcessingStage = 3;
			}
//------------------------------------------------------------------------------------------------
			PropertyList* double05Props = double05->GetProperties();
			cuttingdatacase->ToolDiameter = double05Props->GetDouble("Value");
			delete double05Props;

			PropertyList* double06Props = double06->GetProperties();
			cuttingdatacase->ToolCorner = double06Props->GetDouble("Value");
			delete double06Props;

			PropertyList* double07Props = double07->GetProperties();
			cuttingdatacase->ToolLength = double07Props->GetDouble("Value");
			delete double07Props;

			PropertyList* double04Props = double04->GetProperties();
			cuttingdatacase->ToolFluteLength = double04Props->GetDouble("Value");
			delete double04Props;

			PropertyList* double08Props = double08->GetProperties();
			cuttingdatacase->Tolerance = double08Props->GetDouble("Value");
			delete double08Props;

			PropertyList* double09Props = double09->GetProperties();
			cuttingdatacase->PartAllowance = double09Props->GetDouble("Value");
			delete double09Props;

			PropertyList* double01Props = double01->GetProperties();
			cuttingdatacase->Machining = double01Props->GetDouble("Value");
			delete double01Props;

			PropertyList* double02Props = double02->GetProperties();
			cuttingdatacase->Approach = double02Props->GetDouble("Value");
			delete double02Props;

			PropertyList* double03Props = double03->GetProperties();
			cuttingdatacase->Retract = double03Props->GetDouble("Value");
			delete double03Props;

			PropertyList* double0Props = double0->GetProperties();
			cuttingdatacase->SpindleSpeed = double0Props->GetDouble("Value");
			delete double0Props;

			CuttingDataLib.push_back(cuttingdatacase);
			/*uc1601("重新查找后，可看到新增刀具！", 1);*/


//----------------------------------------------------再次筛选一遍-------------------------------------------------------
			for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
				CuttingDataLib[i]->CutterTypeLable = false;
				CuttingDataLib[i]->CuttingFeatureLable = false;
				CuttingDataLib[i]->CuttingMaterialLable = false;
				CuttingDataLib[i]->ProcessingStageLable = false;
			}

			if (strEnum01 == "铣刀")
			{
				/*uc1601("铣刀", 1);*/
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 1)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}

				}
			}
			else if (strEnum01 == "钻刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 2)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}
			else if (strEnum01 == "点钻刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 3)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}
			else if (strEnum01 == "螺纹铣刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 4)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}
			else if (strEnum01 == "铰刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 5)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}
			else if (strEnum01 == "镗刀")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CutterType == 6)
					{
						CuttingDataLib[i]->CutterTypeLable = true;
					}
				}
			}

			//------------------------------------------------------------------------------
			//------------------------------------------------------------------------------

			if (strEnum03 == "凸台类")
			{
				/*uc1601("凸台类", 1);*/
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingFeature == 1)
					{
						CuttingDataLib[i]->CuttingFeatureLable = true;
					}
				}
			}
			else if (strEnum03 == "筋类")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingFeature == 2)
					{
						CuttingDataLib[i]->CuttingFeatureLable = true;
					}
				}
			}
			else if (strEnum03 == "孔类")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingFeature == 3)
					{
						CuttingDataLib[i]->CuttingFeatureLable = true;
					}
				}
			}
			else if (strEnum03 == "槽类")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingFeature == 4)
					{
						CuttingDataLib[i]->CuttingFeatureLable = true;
					}
				}
			}
			//--------------------------------------------------------------------------------------------
			//---------------------------------------------------------------------------------------------

			if (strEnum0 == "GH4169")
			{
				/*uc1601("GH4169", 1);*/
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingMaterial == 1)
					{
						CuttingDataLib[i]->CuttingMaterialLable = true;
					}
				}
			}
			else if (strEnum0 == "GH4169D")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingMaterial == 2)
					{
						CuttingDataLib[i]->CuttingMaterialLable = true;
					}
				}
			}
			else if (strEnum0 == "GH141")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->CuttingMaterial == 3)
					{
						CuttingDataLib[i]->CuttingMaterialLable = true;
					}
				}
			}
			//-------------------------------------------------------------------------------------
			//--------------------------------------------------------------------------------------


			if (strEnum02 == "粗加工")
			{

				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->ProcessingStage == 1)
					{
						CuttingDataLib[i]->ProcessingStageLable = true;
					}
				}
			}
			else if (strEnum02 == "半精加工")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->ProcessingStage == 2)
					{
						CuttingDataLib[i]->ProcessingStageLable = true;
					}
				}
			}
			else if (strEnum02 == "精加工")
			{
				for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
				{
					if (CuttingDataLib[i]->ProcessingStage == 3)
					{
						CuttingDataLib[i]->ProcessingStageLable = true;
					}
				}
			}
			//------------------------------------------------------------------------------------------------
			Showlist.clear();
			NotShowlist.clear();

			for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
				if (CuttingDataLib[i]->CutterTypeLable == true && CuttingDataLib[i]->CuttingFeatureLable == true &&
					CuttingDataLib[i]->CuttingMaterialLable == true && CuttingDataLib[i]->ProcessingStageLable == true)
				{
					Showlist.push_back(CuttingDataLib[i]);
				}
				else
				{
					NotShowlist.push_back(CuttingDataLib[i]);
				}
			}

			if (Showlist.size() == 0)
				uc1601("没有符合选项的刀具！", 1);
			//------------------------------------------------------------------------------------------------
			/*char message[30];
			UF_UI_open_listing_window();
			sprintf(message, "%d\n", Showlist.size());
			UF_UI_write_listing_window(message);*/
			//------------------------------------------------------------------------------------------------
			CuttingdataDisplay();

			std::string FileString(constFileCharString[0].GetUTF8Text());
			const char*FileCharString = FileString.data();

			PrintCsvCuttingData(FileCharString);

        }
        else if(block == button01)
        {
        //---------Enter your code here-----------
			uc1601("注意！该操作会删除列表中所有已展开刀具！", 1);
			/*for (std::vector<Cuttingdata*>::size_type i = 0; i != Showlist.size(); i++)
			{
				if (Showlist[i]->ifselect == true)
				{
					Showlist.erase(Showlist.begin() + i + 1);
				}
			}*/

			if (Showlist.size() > 0)
			{
				for (auto iter = Showlist.begin(); iter != Showlist.end();)
				{
					if ((*iter)->ifselect == true)
					{
						iter = Showlist.erase(iter);
					}
					else
					{
						iter++;
					}
				}
				CuttingdataDisplay();

				CuttingDataLib.clear();
				CuttingDataLib.insert(CuttingDataLib.end(), Showlist.begin(), Showlist.end());
				CuttingDataLib.insert(CuttingDataLib.end(), NotShowlist.begin(), NotShowlist.end());

				std::string FileString(constFileCharString[0].GetUTF8Text());
				const char*FileCharString = FileString.data();

				PrintCsvCuttingData(FileCharString);
			}
			else
				uc1601("请先点开任意刀具！", 1);
        }		
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        cutting_database::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int cutting_database::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        cutting_database::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}
//------------------------------------------------------------------------------
//ListBox specific callbacks
//------------------------------------------------------------------------------
//int cutting_database::AddCallback (NXOpen::BlockStyler::ListBox* list_box)
//{
//}

//int cutting_database::DeleteCallback(NXOpen::BlockStyler::ListBox* list_box)
//{
//}

//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* cutting_database::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

void cutting_database::ReadExcelFile()
{

	//---------调试模板-----------
	/*char message[13];
	UF_UI_open_listing_window();
	sprintf(message, "%d\n", 980502);
	UF_UI_write_listing_window("调试模板:\n");
	UF_UI_write_listing_window(message);*/
	//---------调试模板-----------

	try
	{
		PropertyList* File = nativeFileBrowser0->GetProperties();
		NXString FileNXString = File->GetString("Path");
		std::string FileString(FileNXString.GetUTF8Text());
		const char*FileCharString = FileString.data();

		/*uc1601(FileCharString, 1);*/

		constFileCharString.clear();
		constFileCharString.push_back(FileNXString);

		/*uc1601(constFileCharString[0], 1);*/

		SaveCsvCuttingData(FileCharString); // 当前总个数 -1 才是最后一行数据
//----------------------------------------------------------------------
		/*char message[30];
		UF_UI_open_listing_window();
		sprintf(message, "%d\n", CuttingDataLib.size());
		UF_UI_write_listing_window(message);
		sprintf(message, "%f\n", CuttingDataLib[6]->SpindleSpeed);
		UF_UI_write_listing_window(message);*/
//--------------------------------------------------------------------------
		uc1601("文件读取完毕!", 1);
	}

	catch (exception& ex2)
	{
		uc1601("Read Excel file failed!\n Error is:\n文件格式不匹配!", 1);  //
	}
}

void cutting_database::PrintCsvCuttingData(const char* FileCharString)
{
	FILE *fp;
	fp = fopen(FileCharString, "w");
	
	if (fp == NULL)
	{
		uc1601("Read Excel file failed!\n Error is:\n所选文件为空!", 1);
	}

	fprintf(fp, "刀具类型,加工特征,刀具材料,加工阶段,刀具直径/mm,刀具圆角半径/mm,刀具长度/mm,刀具刃长/mm,公差/mm,部件余量/mm,进给速度(mm/min),进刀速度(mm/min),退刀速度(mm/min),主轴转速(pm)\n");

	int i = 0;
	while (i < CuttingDataLib.size())
	{
		fprintf(fp, "%d,%d,%d,%d,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f\n", CuttingDataLib[i]->CutterType, CuttingDataLib[i]->CuttingFeature,
			CuttingDataLib[i]->CuttingMaterial, CuttingDataLib[i]->ProcessingStage, CuttingDataLib[i]->ToolDiameter, CuttingDataLib[i]->ToolCorner,
			CuttingDataLib[i]->ToolLength, CuttingDataLib[i]->ToolFluteLength, CuttingDataLib[i]->Tolerance, CuttingDataLib[i]->PartAllowance,
			CuttingDataLib[i]->Machining, CuttingDataLib[i]->Approach, CuttingDataLib[i]->Retract, CuttingDataLib[i]->SpindleSpeed);

		i++;
	}
	fclose(fp);
}



void cutting_database::SaveCsvCuttingData(const char* FileCharString)
{
	CuttingDataLib.clear(); //Cuttingdata类的向量	
	
	FILE *fp;
	fp = fopen(FileCharString,"r");

	if (fp == NULL)
	{
		uc1601("Read Excel file failed!\n Error is:\n文件格式不匹配!", 1);
	}

	char FileHead[1000];
	fgets(FileHead, 1000, fp);

	int i = 0;
	while (!feof(fp))
	{
		Cuttingdata *cuttingdatacase = new Cuttingdata;
		fscanf(fp, "%d,%d,%d,%d,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f", &cuttingdatacase->CutterType, &cuttingdatacase->CuttingFeature,
			&cuttingdatacase->CuttingMaterial, &cuttingdatacase->ProcessingStage, &cuttingdatacase->ToolDiameter, &cuttingdatacase->ToolCorner,
			&cuttingdatacase->ToolLength, &cuttingdatacase->ToolFluteLength, &cuttingdatacase->Tolerance, &cuttingdatacase->PartAllowance,
			&cuttingdatacase->Machining, &cuttingdatacase->Approach, &cuttingdatacase->Retract, &cuttingdatacase->SpindleSpeed);
		
		/*Trim(cuttingdatacase->CutterType);
		Trim(cuttingdatacase->CuttingFeature);
		Trim(cuttingdatacase->CuttingMaterial);
		Trim(cuttingdatacase->ProcessingStage);*/
		//去除,/t/n等空白字符

		CuttingDataLib.push_back(cuttingdatacase);

		/*char message[30];

		UF_UI_open_listing_window();
		sprintf(message, "%d\n", CuttingDataLib[i]->ProcessingStage);
		UF_UI_write_listing_window(message);
		i++;*/
	}
	fclose(fp);
	CuttingDataLib.pop_back(); //删除最后一行空元素
}

//去除string中空白符
void cutting_database::Trim(string & str)
{
	string blanks("\f\v\r\t\n");
	
	str.erase(0, str.find_first_not_of(blanks));
	str.erase(str.find_last_not_of(blanks) + 1);
}

int cutting_database::to_int(std::string s)
{

	int i = 0;
	int result = 0;
	for (i = 0; i <= s.size() - 1; i++)
	{
		if (s[i] >= '0'&&s[i] <= '9')
		{
			result = result * 10 + s[i] - 48;
		}
	}
	return result;

	/********** End **********/
}

void cutting_database::CuttingdataDisplay()
{
	for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
	{
		CuttingDataLib[i]->ifselect = false;
	}

	PropertyList* list_box0Properties = list_box0->GetProperties();
	list_box0Properties->GetStrings("ListItems").clear();
	CuttingdataDisplayStringTitle.clear();
	CuttingdataDisplayStringList.clear();
	delete list_box0Properties;

	NXString CuttingdataStringTitle = "+ 刀具库";
	CuttingdataDisplayStringTitle.push_back(CuttingdataStringTitle);

	NXString CuttingdataStringList = "- 刀具库";
	CuttingdataDisplayStringList.push_back(CuttingdataStringList);

	PropertyList* ExpressionListProperties = list_box0->GetProperties();
	ExpressionListProperties->SetStrings("ListItems", CuttingdataDisplayStringTitle);
	delete ExpressionListProperties;
}

void cutting_database::GetSelectedIndexAndFeatureName(int &Index, NXString &FeaName)//得到选中的索引和该索引下的字符串
{
	Index = -1;

	PropertyList* SpyResultDisplayProperties = list_box0->GetProperties();
	std::vector<NXString> listStrings = SpyResultDisplayProperties->GetStrings("ListItems");
	std::vector<int> index = SpyResultDisplayProperties->GetIntegerVector("SelectedItems");
	delete SpyResultDisplayProperties;

	Index = index[0];
	FeaName = listStrings[Index];
}

void cutting_database::ResponseToFeatureList(int iRowIndex, NXString FeatureName)
{
	PropertyList* list_box0Properties = list_box0->GetProperties();
	std::vector<NXOpen::NXString> listStrings = list_box0Properties->GetStrings("ListItems");

	std::string FeatureNameString(FeatureName.GetUTF8Text());

	NXString TitleNXString = "刀具库";
	std::string TitleString(TitleNXString.GetUTF8Text());

	NXString CuttingDataNXString = "刀具.";
	std::string CuttingDataString(CuttingDataNXString.GetUTF8Text());

	NXString ColonNXString = "：";
	std::string ColonString(ColonNXString.GetUTF8Text());

	if (FeatureNameString.find(TitleString) != std::string::npos)
	{
		NXString PlusNXString = "+";
		std::string PlusString(PlusNXString.GetUTF8Text());
		if (FeatureNameString.find(PlusString) != string::npos)
		{		
			listStrings = CuttingdataDisplayStringList;
			std::vector<NXString> AddStringList;
			std::vector<NXString>::iterator iter = listStrings.begin();//迭代器中的第一个字符元素
			iter += iRowIndex;
			for (std::vector<Cuttingdata*>::size_type i = 0; i != Showlist.size(); i++)
			{
				int index = i + 1;
				char* StringIndex = new char;
				sprintf(StringIndex, "%d", index);
				NXString NXStringIndex = StringIndex;
				delete StringIndex;

				NXString CutterDisplayString = "  + 刀具." + NXStringIndex;
				AddStringList.push_back(CutterDisplayString);
			}
			iter++;
			listStrings.insert(iter, AddStringList.begin(), AddStringList.end());			
		}
		else
		{
			for (std::vector<Cuttingdata*>::size_type i = 0; i != CuttingDataLib.size(); i++)
			{
				CuttingDataLib[i]->ifselect = false;
			}
			listStrings = CuttingdataDisplayStringTitle;
		}
	}

	else if (FeatureNameString.find(CuttingDataString) != std::string::npos)//
	{
		char str[5];
		int CutterNumber = to_int(FeatureNameString);

		sprintf(str, "%d", CutterNumber);
		std::string CutterNumberString = str;//G

		NXString PlusNXString = "+";
		std::string PlusString(PlusNXString.GetUTF8Text());

		if (FeatureNameString.find(PlusString) != string::npos)
		{
			Showlist[CutterNumber - 1]->ifselect = true;

			std::vector<NXString> AddStringList;
			std::vector<NXString>::iterator iter = listStrings.begin();
			iter += iRowIndex;
			*iter = "  - 刀具." + CutterNumberString;//G
			Cuttingdata* EachHoleSpyResult = Showlist[CutterNumber - 1];//G
			

			char* StringIndex1 = new char;
			sprintf(StringIndex1, "%.4f", EachHoleSpyResult->ToolDiameter);//G
			NXString NXStringIndex1 = StringIndex1;
			delete StringIndex1;
			NXString ToolDiameterString = "    刀具直径：" + NXStringIndex1 + "mm";//G
			AddStringList.push_back(ToolDiameterString);//G

			char* StringIndex2 = new char;
			sprintf(StringIndex2, "%.4f", EachHoleSpyResult->ToolCorner);//G
			NXString NXStringIndex2 = StringIndex2;
			delete StringIndex2;
			NXString ToolCornerString = "    刀具圆角半径：" + NXStringIndex2 + "mm";//G
			AddStringList.push_back(ToolCornerString);//G

			char* StringIndex3 = new char;
			sprintf(StringIndex3, "%.4f", EachHoleSpyResult->ToolLength);//G
			NXString NXStringIndex3 = StringIndex3;
			delete StringIndex3;
			NXString ToolLengthString = "    刀具长度：" + NXStringIndex3 + "mm";//G
			AddStringList.push_back(ToolLengthString);//G

			char* StringIndex4 = new char;
			sprintf(StringIndex4, "%.4f", EachHoleSpyResult->ToolFluteLength);//G
			NXString NXStringIndex4 = StringIndex4;
			delete StringIndex4;
			NXString ToolFluteLengthString = "    刀具刃长：" + NXStringIndex4 + "mm";//G
			AddStringList.push_back(ToolFluteLengthString);//G

			char* StringIndex5 = new char;
			sprintf(StringIndex5, "%.4f", EachHoleSpyResult->Tolerance);//G
			NXString NXStringIndex5 = StringIndex5;
			delete StringIndex5;
			NXString ToleranceString = "    公差：" + NXStringIndex5 + "mm";//G
			AddStringList.push_back(ToleranceString);//G

			char* StringIndex6 = new char;
			sprintf(StringIndex6, "%.4f", EachHoleSpyResult->PartAllowance);//G
			NXString NXStringIndex6 = StringIndex6;
			delete StringIndex6;
			NXString PartAllowanceString = "    部件余量：" + NXStringIndex6 + "mm";//G
			AddStringList.push_back(PartAllowanceString);//G

			char* StringIndex7 = new char;
			sprintf(StringIndex7, "%.4f", EachHoleSpyResult->Machining);//G
			NXString NXStringIndex7 = StringIndex7;
			delete StringIndex7;
			NXString MachiningString = "    进给速度：" + NXStringIndex7 + "mm/min";//G
			AddStringList.push_back(MachiningString);//G

			char* StringIndex8 = new char;
			sprintf(StringIndex8, "%.4f", EachHoleSpyResult->Approach);//G
			NXString NXStringIndex8 = StringIndex8;
			delete StringIndex8;
			NXString ApproachString = "    进刀速度：" + NXStringIndex8 + "mm/min";//G
			AddStringList.push_back(ApproachString);//G

			char* StringIndex9 = new char;
			sprintf(StringIndex9, "%.4f", EachHoleSpyResult->Retract);//G
			NXString NXStringIndex9 = StringIndex9;
			delete StringIndex9;
			NXString RetractString = "    退刀速度：" + NXStringIndex9 + "mm/min";//G
			AddStringList.push_back(RetractString);//G

			char* StringIndex10 = new char;
			sprintf(StringIndex10, "%.4f", EachHoleSpyResult->SpindleSpeed);//G
			NXString NXStringIndex10 = StringIndex10;
			delete StringIndex10;
			NXString SpindleSpeedString = "    主轴转速：" + NXStringIndex10 + "pm";//G
			AddStringList.push_back(SpindleSpeedString);//G

			iter++;
			listStrings.insert(iter, AddStringList.begin(), AddStringList.end());
		}
		else
		{
			Showlist[CutterNumber - 1]->ifselect = false;
			std::vector<NXString> DeleteStringList;
			std::vector<NXOpen::NXString>::iterator iter = listStrings.begin();
			iter += iRowIndex;
			*iter = "  + 刀具." + CutterNumberString;//G
			iter++;
			while (iter != listStrings.end())
			{
				NXString BelongHoleNXString = *iter;
				std::string BelongHoleString(BelongHoleNXString.GetUTF8Text());

				if (BelongHoleString.find(ColonString) != std::string::npos)
				{
					listStrings.erase(iter);
					iter = listStrings.begin();
					iter += iRowIndex + 1;
				}
				else break;
			}
		}
	}
	list_box0Properties->SetStrings("ListItems", listStrings);
	delete list_box0Properties;
}