//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\PRO_code\20231019刀具库\cutting_database.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 10-20-2023  (Format: mm-dd-yyyy)
//              Time: 17:18
//
//==============================================================================

#ifndef CUTTING_DATABASE_H_INCLUDED
#define CUTTING_DATABASE_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_FileSelection.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>


#include "FeaturePublicClass.h"
#include "HuNXOpen.h"
#include "uf_all.h"


#include<iostream>
#include<fstream>
#include<vector>
#include<string>


#include<cctype>
#include<algorithm>

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport cutting_database
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;

	bool ReadEXCELOK;
	std::vector<NXString>constFileCharString;
	//刀具库
	std::vector<Cuttingdata*>CuttingDataLib;
	//展示列表
	std::vector<Cuttingdata*>Showlist;
	//展示列表
	std::vector<Cuttingdata*>NotShowlist;
	//树列表相关成员
	std::vector<NXString> CuttingdataDisplayStringTitle;
	std::vector<NXString> CuttingdataDisplayStringList;


    cutting_database();
    ~cutting_database();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the cutting_database.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
    //int AddCallback (NXOpen::BlockStyler::ListBox* list_box);
    //int DeleteCallback(NXOpen::BlockStyler::ListBox* list_box);

	void ReadExcelFile();//excel文件路径读取
	void SaveCsvCuttingData(const char* FileCharString); //保存csv文件到vector中
	void PrintCsvCuttingData(const char* FileCharString); //vector中保存到csv文件
	void Trim(string & str);
	void CuttingdataDisplay();
	void GetSelectedIndexAndFeatureName(int &Index, NXString &FeaName);//树列表相关函数1
	void ResponseToFeatureList(int iRowIndex, NXString FeatureName);//树列表相关函数2
	int cutting_database::to_int(std::string s);

private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::FileSelection* nativeFileBrowser0;// Block type: NativeFileBrowser
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::ListBox* list_box0;// Block type: List Box
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum01;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum03;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum02;// Block type: Enumeration
    NXOpen::BlockStyler::Button* button03;// Block type: Button
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::Group* group4;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double05;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double06;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double07;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double04;// Block type: Double
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double08;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double09;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double01;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double02;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double03;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double0;// Block type: Double
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::Button* button02;// Block type: Button
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    NXOpen::BlockStyler::Button* button01;// Block type: Button
    
};
#endif //CUTTING_DATABASE_H_INCLUDED
