//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  Z:\xinduihuakuang\TongGrooveSideMilling.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 06-17-2024  (Format: mm-dd-yyyy)
//              Time: 10:39 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "TongGrooveSideMilling.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(TongGrooveSideMilling::theSession) = NULL;
UI *(TongGrooveSideMilling::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
TongGrooveSideMilling::TongGrooveSideMilling()
{
    try
    {
        // Initialize the NX Open C++ API environment
        TongGrooveSideMilling::theSession = NXOpen::Session::GetSession();
        TongGrooveSideMilling::theUI = UI::GetUI();
        theDlxFileName = "TongGrooveSideMilling.dlx";
        theDialog = TongGrooveSideMilling::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &TongGrooveSideMilling::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &TongGrooveSideMilling::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &TongGrooveSideMilling::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &TongGrooveSideMilling::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &TongGrooveSideMilling::dialogShown_cb));

		ParameterSet.syspart = 0;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
TongGrooveSideMilling::~TongGrooveSideMilling()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    TongGrooveSideMilling *theTongGrooveSideMilling = NULL;
    try
    {
        theTongGrooveSideMilling = new TongGrooveSideMilling();
        // The following method shows the dialog immediately
        theTongGrooveSideMilling->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theTongGrooveSideMilling != NULL)
    {
        delete theTongGrooveSideMilling;
        theTongGrooveSideMilling = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int TongGrooveSideMilling::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void TongGrooveSideMilling::initialize_cb()
{
    try
    {
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        bodySelect0 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect0"));
        nativeFileBrowser0 = dynamic_cast<NXOpen::BlockStyler::FileSelection*>(theDialog->TopBlock()->FindBlock("nativeFileBrowser0"));
        enum010 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum010"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
        enum08 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum08"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        toggle04 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle04"));
        bodySelect01 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect01"));
        toggle05 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle05"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group4 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group4"));
        toggle06 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle06"));
        toggle02 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle02"));
        face_select0 = dynamic_cast<NXOpen::BlockStyler::FaceCollector*>(theDialog->TopBlock()->FindBlock("face_select0"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        tabControl = dynamic_cast<NXOpen::BlockStyler::TabControl*>(theDialog->TopBlock()->FindBlock("tabControl"));
        tabPage = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage"));
        enum07 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum07"));
        enum02 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum02"));
        double015 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double015"));
        toggle0 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0"));
        toggle01 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle01"));
        enum09 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum09"));
        double012 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double012"));
        double013 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double013"));
        double017 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double017"));
        enum04 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum04"));
        double018 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double018"));
        enum013 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum013"));
        double019 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double019"));
        tabPage1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage1"));
        double0 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double0"));
        double011 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double011"));
        double016 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double016"));
        double01 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double01"));
        double02 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double02"));
        double03 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double03"));
        double04 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double04"));
        tabPage2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage2"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        enum05 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum05"));
        double06 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double06"));
        enum011 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum011"));
        double05 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double05"));
        enum06 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum06"));
        double07 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double07"));
        double08 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double08"));
        double09 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double09"));
        double010 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double010"));
        enum012 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum012"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        enum03 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum03"));
        plane0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPlane*>(theDialog->TopBlock()->FindBlock("plane0"));
        double014 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double014"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));

		InitialParameter();
		ReadXMLOK = false;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void TongGrooveSideMilling::dialogShown_cb()
{
	InitialParameter();
    try
    {
        //---- Enter your callback code here -----
		PropertyList* nativeFileBrowser0Props = nativeFileBrowser0->GetProperties();
		NXString FileString = "";
		nativeFileBrowser0Props->SetString("Path", FileString);
		delete nativeFileBrowser0Props;

		PropertyList* toggle02Props = toggle02->GetProperties();
		toggle02Props->SetLogical("Enable", TRUE);
		toggle02Props->SetLogical("Value", FALSE);
		delete toggle02Props;

		PropertyList* toggle06Props = toggle06->GetProperties();
		toggle06Props->SetLogical("Enable", TRUE);
		toggle06Props->SetLogical("Value", FALSE);
		delete toggle06Props;

		PropertyList* toggle04Props = toggle04->GetProperties();
		toggle04Props->SetLogical("Enable", TRUE);
		toggle04Props->SetLogical("Value", FALSE);
		delete toggle04Props;

		PropertyList* toggle05Props = toggle05->GetProperties();
		toggle05Props->SetLogical("Enable", TRUE);
		toggle05Props->SetLogical("Value", FALSE);
		delete toggle05Props;

		PropertyList* bodySelect01Props = bodySelect01->GetProperties();
		bodySelect01Props->SetLogical("Enable", FALSE);
		delete bodySelect01Props;

		PropertyList* face_select0Props = face_select0->GetProperties();
		face_select0Props->SetLogical("Enable", FALSE);
		delete face_select0Props;
		face_select0->SetFaceRules(1);

		PropertyList* enum0Props = enum0->GetProperties();
		enum0Props->SetLogical("Enable", FALSE);
		delete enum0Props;

		PropertyList* enum07Props = enum07->GetProperties();
		enum07Props->SetEnumAsString("Value", "順铣");
		delete enum07Props;

		PropertyList* enum02Props = enum02->GetProperties();
		enum02Props->SetEnumAsString("Value", "轮廓");
		delete enum02Props;

		PropertyList* toggle0Props = toggle0->GetProperties();
		toggle0Props->SetLogical("Enable", TRUE);
		toggle0Props->SetLogical("Value", FALSE);
		delete toggle0Props;

		face_select0->SetFaceRules(1);//设置单个面模式

		PropertyList* toggle01Props = toggle01->GetProperties();
		toggle01Props->SetLogical("Enable", TRUE);
		toggle01Props->SetLogical("Value", FALSE);
		delete toggle01Props;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int TongGrooveSideMilling::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int TongGrooveSideMilling::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == bodySelect0)
        {
        //---------Enter your code here-----------
			PropertyList* bodySelect0Props = bodySelect0->GetProperties();
			std::vector<NXOpen::TaggedObject *> Bodies = bodySelect0Props->GetTaggedObjectVector("SelectedObjects");
			selectedBody = dynamic_cast<NXOpen::Body*>(Bodies[0]);
			delete bodySelect0Props;

			AllFaces = selectedBody->GetFaces();

			workPart = NXOpen::Session::GetSession()->Parts()->Work();
			NXString path = workPart->FullPath();

			const char* pathName = path.GetUTF8Text();
			std::string stringName = (char*)pathName;

			std::string::size_type position;
			position = stringName.rfind("\\");

			std::string subStr = stringName.substr(0, position);
			NXString NXsubStr = (NXString)subStr;
			NXString SelectionPathNXString;
			SelectionPathNXString = NXsubStr;

			NXString namefile = SelectionPathNXString + "\\" + "groove.xml";

			if (Bodies.size() != 0)
			{
				PropertyList* nativeFileBrowser0Props = nativeFileBrowser0->GetProperties();
				nativeFileBrowser0Props->SetString("Path", namefile);
				delete nativeFileBrowser0Props;

				ReadXmlFile_PassGroove();
				ReadXMLOK = true;
				if (ListOfPassGroove.size() == 0)
				{
					ReadXMLOK = false;
				}
			}
        }
        else if(block == nativeFileBrowser0)
        {
        //---------Enter your code here-----------
			ReadXmlFile_PassGroove();
			ReadXMLOK = true;
			if (ListOfPassGroove.size() == 0)
			{
				ReadXMLOK = false;
			}
        }
        else if(block == enum010)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum01)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum08)
        {
        //---------Enter your code here-----------
        }
        else if(block == toggle04)
        {
        //---------Enter your code here-----------
			PropertyList* toggle04Props = toggle04->GetProperties();
			bool chuangjianjubu = toggle04Props->GetLogical("Value");
			delete toggle04Props;

			if (chuangjianjubu)
			{
				ParameterSet.syspart = 1;

				PropertyList* bodySelect01Props = bodySelect01->GetProperties();
				bodySelect01Props->SetLogical("Enable", TRUE);
				delete bodySelect01Props;

				PropertyList* toggle05Props = toggle05->GetProperties();
				toggle05Props->SetLogical("Enable", FALSE);
				delete toggle05Props;

				PropertyList* enum0Props = enum0->GetProperties();
				enum0Props->SetLogical("Enable", FALSE);
				delete enum0Props;
			}

			else
			{
				ParameterSet.syspart = 0;

				PropertyList* bodySelect01Props = bodySelect01->GetProperties();
				bodySelect01Props->SetLogical("Enable", FALSE);
				delete bodySelect01Props;

				PropertyList* toggle05Props = toggle05->GetProperties();
				toggle05Props->SetLogical("Enable", TRUE);
				delete toggle05Props;

				PropertyList* enum0Props = enum0->GetProperties();
				enum0Props->SetLogical("Enable", FALSE);
				delete enum0Props;
			}
        }
        else if(block == bodySelect01)
        {
        //---------Enter your code here-----------
			PropertyList* bodySelect01Props = bodySelect01->GetProperties();
			std::vector<NXOpen::TaggedObject *> Bodies = bodySelect01Props->GetTaggedObjectVector("SelectedObjects");
			selectedBlank = dynamic_cast<NXOpen::Body*>(Bodies[0]);
			delete bodySelect01Props;
        }
        else if(block == toggle05)
        {
        //---------Enter your code here-----------
			PropertyList* toggle05Props = toggle05->GetProperties();
			bool buchuangjianjubu = toggle05Props->GetLogical("Value");
			delete toggle05Props;

			if (buchuangjianjubu)
			{
				ParameterSet.syspart = 1;

				PropertyList* toggle04Props = toggle04->GetProperties();
				toggle04Props->SetLogical("Enable", FALSE);
				delete toggle04Props;

				PropertyList* bodySelect01Props = bodySelect01->GetProperties();
				bodySelect01Props->SetLogical("Enable", FALSE);
				delete bodySelect01Props;

				PropertyList* enum0Props = enum0->GetProperties();
				enum0Props->SetLogical("Enable", TRUE);
				delete enum0Props;
			}
			else
			{
				ParameterSet.syspart = 0;

				PropertyList* toggle04Props = toggle04->GetProperties();
				toggle04Props->SetLogical("Enable", TRUE);
				delete toggle04Props;

				PropertyList* bodySelect01Props = bodySelect01->GetProperties();
				bodySelect01Props->SetLogical("Enable", FALSE);
				delete bodySelect01Props;

				PropertyList* enum0Props = enum0->GetProperties();
				enum0Props->SetLogical("Enable", FALSE);
				delete enum0Props;
			}
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
        }
        else if(block == toggle06)
        {
        //---------Enter your code here-----------
			PropertyList* toggle06Props = toggle06->GetProperties();
			bool jiagongsuoyou = toggle06Props->GetLogical("Value");
			delete toggle06Props;

			if (jiagongsuoyou)
			{
				PropertyList* toggle02Props = toggle02->GetProperties();
				toggle02Props->SetLogical("Enable", FALSE);
				delete toggle02Props;
			}
			else
			{
				PropertyList* toggle02Props = toggle02->GetProperties();
				toggle02Props->SetLogical("Enable", TRUE);
				delete toggle02Props;
			}
        }
        else if(block == toggle02)
        {
        //---------Enter your code here-----------
			PropertyList* toggle02Props = toggle02->GetProperties();
			bool jiagongsuoxuan = toggle02Props->GetLogical("Value");
			delete toggle02Props;

			if (jiagongsuoxuan)
			{
				PropertyList* toggle06Props = toggle06->GetProperties();
				toggle06Props->SetLogical("Enable", FALSE);
				delete toggle06Props;

				PropertyList* face_select0Props = face_select0->GetProperties();
				face_select0Props->SetLogical("Enable", TRUE);
				delete face_select0Props;
			}
			else
			{
				PropertyList* toggle06Props = toggle06->GetProperties();
				toggle06Props->SetLogical("Enable", TRUE);
				delete toggle06Props;

				PropertyList* face_select0Props = face_select0->GetProperties();
				face_select0Props->SetLogical("Enable", FALSE);
				delete face_select0Props;
			}
        }
        else if(block == face_select0)
        {
        //---------Enter your code here-----------
			SelectedPassGrooveTopFaceList.clear();
			BlockStyler::PropertyList * face_select0Props = face_select0->GetProperties();
			std::vector<NXOpen::TaggedObject*> pTaggedObject_FaceList = face_select0Props->GetTaggedObjectVector("SelectedObjects");
			delete face_select0Props;

			int pTaggedObject_FaceListSize = pTaggedObject_FaceList.size();
			Face* SelectedPassGrooveTopFace;
			for (int i = 0; i != pTaggedObject_FaceListSize; i++)
			{
				SelectedPassGrooveTopFace = dynamic_cast<NXOpen::Face*>(pTaggedObject_FaceList[i]);
				SelectedPassGrooveTopFaceList.push_back(SelectedPassGrooveTopFace);
			}

			for (std::vector<PassGroove*>::size_type i = 0; i != ListOfPassGroove.size(); i++)
			{
				PassGroove* EachPassGroove = ListOfPassGroove[i];
				Face* PassGrooveTopFace = EachPassGroove->TopFaceVector[0];
				PassGrooveTopFaceList.push_back(PassGrooveTopFace);
			}

			SelectedFaceCampare(SelectedPassGrooveTopFaceList, PassGrooveTopFaceList);
        }
        else if(block == enum07)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum02)
        {
        //---------Enter your code here-----------
			PropertyList* enum02Props = enum02->GetProperties();
			int ToolMotionType = enum02Props->GetEnum("Value");
			delete enum02Props;

			if (ToolMotionType == 0 || ToolMotionType == 1 || ToolMotionType == 2)
			{
				PropertyList* double015Props = double015->GetProperties();
				double015Props->SetLogical("Enable", FALSE);
				delete double015Props;

				PropertyList* toggle0Props = toggle0->GetProperties();
				toggle0Props->SetLogical("Enable", FALSE);
				delete toggle0Props;

				PropertyList* toggle01Props = toggle01->GetProperties();
				toggle01Props->SetLogical("Enable", FALSE);
				delete toggle01Props;

				PropertyList* enum09Props = enum09->GetProperties();
				enum09Props->SetLogical("Enable", FALSE);
				delete enum09Props;

				PropertyList* double012Props = double012->GetProperties();
				double012Props->SetLogical("Enable", FALSE);
				delete double012Props;

				PropertyList* double013Props = double013->GetProperties();
				double013Props->SetLogical("Enable", FALSE);
				delete double013Props;

				PropertyList* enum04Props = enum04->GetProperties();
				enum04Props->SetLogical("Enable", FALSE);
				delete enum04Props;

				PropertyList* double017Props = double017->GetProperties();
				double017Props->SetLogical("Enable", FALSE);
				delete double017Props;
			}
			else if (ToolMotionType == 3)
			{
				PropertyList* double015Props = double015->GetProperties();
				double015Props->SetLogical("Enable", TRUE);
				delete double015Props;

				PropertyList* toggle0Props = toggle0->GetProperties();
				toggle0Props->SetLogical("Enable", TRUE);

				PropertyList* toggle01Props = toggle01->GetProperties();
				toggle01Props->SetLogical("Enable", TRUE);

				bool multiDepthFlag = toggle0Props->GetLogical("Value");
				delete toggle0Props;
				if (multiDepthFlag)
				{
					PropertyList* enum09Props = enum09->GetProperties();
					enum09Props->SetLogical("Enable", TRUE);
					delete enum09Props;

					PropertyList* double012Props = double012->GetProperties();
					double012Props->SetLogical("Enable", TRUE);
					delete double012Props;
				}
				else
				{
					PropertyList* enum09Props = enum09->GetProperties();
					enum09Props->SetLogical("Enable", FALSE);
					delete enum09Props;

					PropertyList* double012Props = double012->GetProperties();
					double012Props->SetLogical("Enable", FALSE);
					delete double012Props;
				}

				bool multiPathFlag = toggle01Props->GetLogical("Value");
				delete toggle01Props;
				if (multiPathFlag)
				{
					PropertyList* double013Props = double013->GetProperties();
					double013Props->SetLogical("Enable", TRUE);
					delete double013Props;

					PropertyList* enum04Props = enum04->GetProperties();
					enum04Props->SetLogical("Enable", TRUE);
					delete enum04Props;

					PropertyList* double017Props = double017->GetProperties();
					double017Props->SetLogical("Enable", TRUE);
					delete double017Props;
				}
				else
				{
					PropertyList* double013Props = double013->GetProperties();
					double013Props->SetLogical("Enable", FALSE);
					delete double013Props;

					PropertyList* enum04Props = enum04->GetProperties();
					enum04Props->SetLogical("Enable", FALSE);
					delete enum04Props;

					PropertyList* double017Props = double017->GetProperties();
					double017Props->SetLogical("Enable", FALSE);
					delete double017Props;
				}
			}
        }
        else if(block == double015)
        {
        //---------Enter your code here-----------
        }
        else if(block == toggle0)
        {
        //---------Enter your code here-----------
			PropertyList* toggle0Props = toggle0->GetProperties();
			bool multiDepthFlag = toggle0Props->GetLogical("Value");
			delete toggle0Props;

			if (multiDepthFlag)
			{
				PropertyList* enum09Props = enum09->GetProperties();
				enum09Props->SetLogical("Enable", TRUE);
				delete enum09Props;

				PropertyList* double012Props = double012->GetProperties();
				double012Props->SetLogical("Enable", TRUE);
				delete double012Props;
			}
			else
			{
				PropertyList* enum09Props = enum09->GetProperties();
				enum09Props->SetLogical("Enable", FALSE);
				delete enum09Props;

				PropertyList* double012Props = double012->GetProperties();
				double012Props->SetLogical("Enable", FALSE);
				delete double012Props;
			}
        }
        else if(block == toggle01)
        {
        //---------Enter your code here-----------
			PropertyList* toggle01Props = toggle01->GetProperties();
			bool multiPathFlag = toggle01Props->GetLogical("Value");
			delete toggle01Props;

			if (multiPathFlag)
			{
				PropertyList* double013Props = double013->GetProperties();
				double013Props->SetLogical("Enable", TRUE);
				delete double013Props;

				PropertyList* enum04Props = enum04->GetProperties();
				enum04Props->SetLogical("Enable", TRUE);
				delete enum04Props;

				PropertyList* double017Props = double017->GetProperties();
				double017Props->SetLogical("Enable", TRUE);
				delete double017Props;
			}
			else
			{
				PropertyList* double013Props = double013->GetProperties();
				double013Props->SetLogical("Enable", FALSE);
				delete double013Props;

				PropertyList* enum04Props = enum04->GetProperties();
				enum04Props->SetLogical("Enable", FALSE);
				delete enum04Props;

				PropertyList* double017Props = double017->GetProperties();
				double017Props->SetLogical("Enable", FALSE);
				delete double017Props;
			}
        }
        else if(block == enum09)
        {
        //---------Enter your code here-----------
        }
        else if(block == double012)
        {
        //---------Enter your code here-----------
        }
        else if(block == double013)
        {
        //---------Enter your code here-----------
        }
        else if(block == double017)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum04)
        {
        //---------Enter your code here-----------
        }
        else if(block == double018)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum013)
        {
        //---------Enter your code here-----------
        }
        else if(block == double019)
        {
        //---------Enter your code here-----------
        }
        else if(block == double0)
        {
        //---------Enter your code here-----------
        }
        else if(block == double011)
        {
        //---------Enter your code here-----------
        }
        else if(block == double016)
        {
        //---------Enter your code here-----------
        }
        else if(block == double01)
        {
        //---------Enter your code here-----------
        }
        else if(block == double02)
        {
        //---------Enter your code here-----------
        }
        else if(block == double03)
        {
        //---------Enter your code here-----------
        }
        else if(block == double04)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum05)
        {
        //---------Enter your code here-----------
			PropertyList* enum05Props = enum05->GetProperties();
			int ToolApproachType = enum05Props->GetEnum("Value");
			delete enum05Props;

			if (ToolApproachType == 0)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();
				double07Props->SetLogical("Enable", TRUE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				double08Props->SetLogical("Enable", FALSE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 1)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();
				double07Props->SetLogical("Enable", FALSE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				double08Props->SetLogical("Enable", TRUE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 2)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();
				double07Props->SetLogical("Enable", FALSE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				double08Props->SetLogical("Enable", FALSE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 3)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetEnumAsString("Value", "%刀具");
				enum011Props->SetLogical("Enable", TRUE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				double06Props->SetDouble("Value", 100);
				double06Props->SetLogical("Enable", TRUE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", FALSE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				double05Props->SetLogical("Enable", FALSE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();
				double07Props->SetDouble("Value", 0);
				double07Props->SetLogical("Enable", TRUE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				double08Props->SetDouble("Value", 0);
				double08Props->SetLogical("Enable", TRUE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				double09Props->SetLogical("Enable", FALSE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();
				double010Props->SetLogical("Enable", FALSE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", FALSE);
				delete enum012Props;
			}
        }
        else if(block == double06)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum011)
        {
        //---------Enter your code here-----------
        }
        else if(block == double05)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum06)
        {
        //---------Enter your code here-----------
        }
        else if(block == double07)
        {
        //---------Enter your code here-----------
        }
        else if(block == double08)
        {
        //---------Enter your code here-----------
        }
        else if(block == double09)
        {
        //---------Enter your code here-----------
        }
        else if(block == double010)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum012)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum03)
        {
        //---------Enter your code here-----------
        }
        else if(block == plane0)
        {
        //---------Enter your code here-----------
        }
        else if(block == double014)
        {
        //---------Enter your code here-----------
        }
        else if(block == button0)
        {
        //---------Enter your code here-----------
			if (!ReadXMLOK)
			{
				uc1601("请选择 正确的特征识别XML文件！", 1);
				return -1;
			}

			PropertyList* enum010Props = enum010->GetProperties();
			ParameterSet.PROGRAM = enum010Props->GetEnumAsString("Value");
			delete enum010Props;

			PropertyList* enum01Props = enum01->GetProperties();
			NXString tempToolName = enum01Props->GetEnumAsString("Value");
			const char* tempToolNameChar = tempToolName.GetUTF8Text();
			ParameterSet.ToolMsg.ToolName = tempToolName;
			delete enum01Props;

			PropertyList* enum0Props = enum0->GetProperties();
			ParameterSet.GeomtryMCS = enum0Props->GetEnumAsString("Value");
			delete enum0Props;

			PropertyList* enum08Props = enum08->GetProperties();
			ParameterSet.METHOD = enum08Props->GetEnumAsString("Value");
			delete enum08Props;

			for (std::vector<NXString>::size_type n = 0; n != ToolStringList.size(); n++)
			{
				NXString nToolName = ToolStringList[n];
				const char* nToolNameChar = nToolName.GetUTF8Text();
				if (lstrcmp(nToolNameChar, tempToolNameChar) == 0)
				{
					NXOpen::CAM::CAMObject* EachMember = ToolMembers[n + 1];
					CAM::MillToolBuilder* millToolBuilder1;
					millToolBuilder1 = workPart->CAMSetup()->CAMGroupCollection()->CreateMillToolBuilder(dynamic_cast<CAM::Tool*>(EachMember));

					ParameterSet.ToolMsg.ToolDiameter = millToolBuilder1->TlDiameterBuilder()->Value();
					ParameterSet.ToolMsg.ToolCorner = millToolBuilder1->TlTaperAngBuilder()->Value();
					ParameterSet.ToolMsg.ToolLength = millToolBuilder1->TlHeightBuilder()->Value();
					ParameterSet.ToolMsg.ToolFluteLength = millToolBuilder1->TlFluteLnBuilder()->Value();
				}
			}

			PropertyList* toggle04Props = toggle04->GetProperties();
			ParameterSet.LCsys = toggle04Props->GetLogical("Value");
			delete toggle04Props;

			PropertyList* toggle05Props = toggle05->GetProperties();
			ParameterSet.NotLCsys = toggle05Props->GetLogical("Value");
			delete toggle05Props;

			PropertyList* toggle02Props = toggle02->GetProperties();
			ParameterSet.FaceSelect = toggle02Props->GetLogical("Value");
			delete toggle02Props;

			PropertyList* toggle06Props = toggle06->GetProperties();
			ParameterSet.AllGroove = toggle06Props->GetLogical("Value");
			delete toggle06Props;

			PropertyList* enum07Props = enum07->GetProperties();
			ParameterSet.CuttingDirection = enum07Props->GetEnum("Value");
			delete enum07Props;

			PropertyList* enum02Props = enum02->GetProperties();
			ParameterSet.CuttingMode = enum02Props->GetEnum("Value");
			delete enum02Props;

			PropertyList* double015Props = double015->GetProperties();
			ParameterSet.BoundaryOffset = double015Props->GetDouble("Value");
			delete double015Props;

			PropertyList* toggle0Props = toggle0->GetProperties();
			ParameterSet.MultiDepthFlag = toggle0Props->GetLogical("Value");
			delete toggle0Props;

			PropertyList* enum09Props = enum09->GetProperties();
			ParameterSet.MultiDepthStepUnit = enum09Props->GetEnum("Value");
			delete enum09Props;

			PropertyList* double012Props = double012->GetProperties();
			ParameterSet.MultiDepthStepAmount = double012Props->GetDouble("Value");
			delete double012Props;

			PropertyList* toggle01Props = toggle01->GetProperties();
			ParameterSet.MultiPathFlag = toggle01Props->GetLogical("Value");
			delete toggle01Props;

			PropertyList* double013Props = double013->GetProperties();
			ParameterSet.MultiPathNum = double013Props->GetDouble("Value");
			delete double013Props;

			PropertyList* enum04Props = enum04->GetProperties();
			ParameterSet.MultiPathStepUnit = enum04Props->GetEnum("Value");
			delete enum04Props;

			PropertyList* double017Props = double017->GetProperties();
			ParameterSet.MultiPathStepAmount = double017Props->GetDouble("Value");
			delete double017Props;

			PropertyList* double018Props = double018->GetProperties();
			ParameterSet.StepDistance = double018Props->GetDouble("Value");
			delete double018Props;

			PropertyList* enum013Props = enum013->GetProperties();
			ParameterSet.StepDistanceunit = enum013Props->GetEnum("Value");
			delete enum013Props;

			PropertyList* double019Props = double019->GetProperties();
			ParameterSet.depth = double019Props->GetDouble("Value");
			delete double019Props;

			PropertyList* double0Props = double0->GetProperties();
			ParameterSet.Tolerance = double0Props->GetDouble("Value");
			delete double0Props;

			PropertyList* double011Props = double011->GetProperties();
			ParameterSet.PartAllowance = double011Props->GetDouble("Value");
			delete double011Props;

			PropertyList* double016Props = double016->GetProperties();
			ParameterSet.PartSafetyDistance = double016Props->GetDouble("Value");
			delete double016Props;

			PropertyList* double01Props = double01->GetProperties();
			ParameterSet.SpindleSpeed = double01Props->GetDouble("Value");
			delete double01Props;

			PropertyList* double02Props = double02->GetProperties();
			ParameterSet.Machining = double02Props->GetDouble("Value");
			delete double02Props;

			PropertyList* double03Props = double03->GetProperties();
			ParameterSet.Approach = double03Props->GetDouble("Value");
			delete double03Props;

			PropertyList* double04Props = double04->GetProperties();
			ParameterSet.Retract = double04Props->GetDouble("Value");
			delete double04Props;


			PropertyList* enum05Props = enum05->GetProperties();
			ParameterSet.ToolMotion.ToolMotionType = enum05Props->GetEnum("Value");
			delete enum05Props;

			PropertyList* enum011Props = enum011->GetProperties();
			ParameterSet.ToolMotion.ToolMotionDistanceUnit = enum011Props->GetEnum("Value");
			delete enum011Props;

			PropertyList* double06Props = double06->GetProperties();
			ParameterSet.ToolMotion.ToolMotionDistance = double06Props->GetDouble("Value");
			delete double06Props;

			PropertyList* enum06Props = enum06->GetProperties();
			ParameterSet.ToolMotion.CircleRadiusUnit = enum06Props->GetEnum("Value");
			delete enum06Props;

			PropertyList* double05Props = double05->GetProperties();
			ParameterSet.ToolMotion.CircleRadius = double05Props->GetDouble("Value");
			delete double05Props;

			PropertyList* double07Props = double07->GetProperties();
			ParameterSet.ToolMotion.RotationAngle = double07Props->GetDouble("Value");
			delete double07Props;

			PropertyList* double08Props = double08->GetProperties();
			ParameterSet.ToolMotion.TiltAngle = double08Props->GetDouble("Value");
			delete double08Props;

			PropertyList* double09Props = double09->GetProperties();
			ParameterSet.ToolMotion.CircleAngle = double09Props->GetDouble("Value");
			delete double09Props;

			PropertyList* enum012Props = enum012->GetProperties();
			ParameterSet.ToolMotion.LinearExtensionUnit = enum012Props->GetEnum("Value");
			delete enum012Props;

			PropertyList* double010Props = double010->GetProperties();
			ParameterSet.ToolMotion.LinearExtension = double010Props->GetDouble("Value");
			delete double010Props;


			PropertyList* enum03Props = enum03->GetProperties();
			ParameterSet.SafeSetType = enum03Props->GetEnum("Value");
			delete enum03Props;

			PropertyList* double014Props = double014->GetProperties();
			ParameterSet.SafeSetOffset = double014Props->GetDouble("Value");
			delete double014Props;

			PassGrooveSideMillingCmd*CasingTongGrooveMilling = new PassGrooveSideMillingCmd(ListOfPassGroove, ParameterSet, workPart, selectedBody, selectedBlank, SelectedPassGrooveTopFaceList);
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int TongGrooveSideMilling::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* TongGrooveSideMilling::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

void TongGrooveSideMilling::focusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus)
{
	try
	{
		//---- Enter your callback code here -----
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
}

void TongGrooveSideMilling::keyboardFocusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus)
{
	try
	{
		//---- Enter your callback code here -----
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		TongGrooveSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
}

void TongGrooveSideMilling::InitialParameter()
{
	NXOpen::Session *theSession = NXOpen::Session::GetSession();
	workPart = theSession->Parts()->Work();
	theSession->CreateCamSession();

	CAM::NCGroup *nCGroup010(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NC_PROGRAM")));
	ProgramMembers = nCGroup010->GetMembers();
	int ProgramMemberSize = ProgramMembers.size();
	ProgramStringList.clear();
	for (int i = 1; i < ProgramMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = ProgramMembers[i];
		NXString EachMemberstr = EachMember->Name();
		ProgramStringList.push_back(EachMemberstr);
	}
	PropertyList* enum010Props = enum010->GetProperties();
	enum010Props->SetEnumMembers("Value", ProgramStringList);
	delete enum010Props;

	CAM::NCGroup* nCGroup01(dynamic_cast<CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("GENERIC_MACHINE")));
	ToolMembers = nCGroup01->GetMembers();
	int ToolMemberSize = ToolMembers.size();
	ToolStringList.clear();
	for (int i = 1; i < ToolMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = ToolMembers[i];
		NXString EachMemberstr = EachMember->Name();
		ToolStringList.push_back(EachMemberstr);
	}
	PropertyList* enum01Props = enum01->GetProperties();
	enum01Props->SetEnumMembers("Value", ToolStringList);
	delete enum01Props;

	CAM::NCGroup *nCGroup0(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("GEOMETRY")));
	MCSMembers = nCGroup0->GetMembers();
	int MCSMemberSize = MCSMembers.size();
	MCSStringList.clear();
	NXString MCS_name = "MCS_MILL";
	MCSStringList.push_back(MCS_name);
	/*for (int i = 1; i < MCSMemberSize; i++)
	{
	NXOpen::CAM::CAMObject* EachMember = MCSMembers[i];
	NXString EachMemberstr = EachMember->Name();
	MCSStringList.push_back(EachMemberstr);
	}*/
	PropertyList* enum0Props = enum0->GetProperties();
	enum0Props->SetEnumMembers("Value", MCSStringList);
	delete enum0Props;

	CAM::NCGroup *nCGroup08(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
	MethodMembers = nCGroup08->GetMembers();
	int MethodMemberSize = MethodMembers.size();
	MethodStringList.clear();
	for (int i = 1; i < MethodMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = MethodMembers[i];
		NXString EachMemberstr = EachMember->Name();
		MethodStringList.push_back(EachMemberstr);
	}
	PropertyList* enum08Props = enum08->GetProperties();
	enum08Props->SetEnumMembers("Value", MethodStringList);
	delete enum08Props;




	PropertyList* enum07Props = enum07->GetProperties();
	enum07Props->SetEnumAsString("Value", "順铣");
	delete enum07Props;

	PropertyList* enum02Props = enum02->GetProperties();
	enum02Props->SetEnumAsString("Value", "轮廓");
	delete enum02Props;

	PropertyList* double015Props = double015->GetProperties();
	double015Props->SetDouble("Value", 0.005);
	delete double015Props;

	PropertyList* enum09Props = enum09->GetProperties();
	enum09Props->SetEnumAsString("Value", "增量");
	enum09Props->SetLogical("Enable", FALSE);
	delete enum09Props;

	PropertyList* double012Props = double012->GetProperties();
	double012Props->SetDouble("Value", 4);
	double012Props->SetLogical("Enable", FALSE);
	delete double012Props;

	PropertyList* double013Props = double013->GetProperties();
	double013Props->SetDouble("Value", 0);
	double013Props->SetLogical("Enable", FALSE);
	delete double013Props;

	PropertyList* enum04Props = enum04->GetProperties();
	enum04Props->SetEnumAsString("Value", "%刀具");
	enum04Props->SetLogical("Enable", FALSE);
	delete enum04Props;

	PropertyList* double017Props = double017->GetProperties();
	double017Props->SetDouble("Value", 50);
	double017Props->SetLogical("Enable", FALSE);
	delete double017Props;

	PropertyList* double018Props = double018->GetProperties();
	double018Props->SetDouble("Value", 50);
	double018Props->SetLogical("Enable", TRUE);
	delete double018Props;

	PropertyList* enum013Props = enum013->GetProperties();
	enum013Props->SetEnumAsString("Value", "%刀具");
	enum013Props->SetLogical("Enable", TRUE);
	delete enum013Props;

	PropertyList* double0Props = double0->GetProperties();
	double0Props->SetDouble("Value", 0.03);
	delete double0Props;

	PropertyList* double019Props = double019->GetProperties();
	double019Props->SetDouble("Value", 1);
	double019Props->SetLogical("Enable", TRUE);
	delete double019Props;

	PropertyList* double011Props = double011->GetProperties();
	double011Props->SetDouble("Value", 0);
	delete double011Props;

	PropertyList* double016Props = double016->GetProperties();
	double016Props->SetDouble("Value", 3);
	delete double016Props;

	PropertyList* double01Props = double01->GetProperties();
	double01Props->SetDouble("Value", 8000);
	delete double01Props;

	PropertyList* double02Props = double02->GetProperties();
	double02Props->SetDouble("Value", 1000);
	delete double02Props;

	PropertyList* double03Props = double03->GetProperties();
	double03Props->SetDouble("Value", 2000);
	delete double03Props;

	PropertyList* double04Props = double04->GetProperties();
	double04Props->SetDouble("Value", 6000);
	delete double04Props;

	PropertyList* enum05Props = enum05->GetProperties();
	enum05Props->SetEnumAsString("Value", "圆弧-平行于刀轴");
	delete enum05Props;

	PropertyList* enum011Props = enum011->GetProperties();
	enum011Props->SetEnumAsString("Value", "%刀具");
	enum011Props->SetLogical("Enable", FALSE);
	delete enum011Props;

	PropertyList* double06Props = double06->GetProperties();
	double06Props->SetDouble("Value", 100);
	double06Props->SetLogical("Enable", FALSE);
	delete double06Props;

	PropertyList* enum06Props = enum06->GetProperties();
	enum06Props->SetEnumAsString("Value", "%刀具");
	enum06Props->SetLogical("Enable", TRUE);
	delete enum06Props;

	PropertyList* double05Props = double05->GetProperties();
	double05Props->SetDouble("Value", 50);
	double05Props->SetLogical("Enable", TRUE);
	delete double05Props;

	PropertyList* double07Props = double07->GetProperties();
	double07Props->SetDouble("Value", 0);
	double07Props->SetLogical("Enable", TRUE);
	delete double07Props;

	PropertyList* double08Props = double08->GetProperties();
	double08Props->SetDouble("Value", 0);
	double08Props->SetLogical("Enable", FALSE);
	delete double08Props;

	PropertyList* double09Props = double09->GetProperties();
	double09Props->SetDouble("Value", 90);
	double09Props->SetLogical("Enable", TRUE);
	delete double09Props;

	PropertyList* double010Props = double010->GetProperties();
	double010Props->SetDouble("Value", 0);
	double010Props->SetLogical("Enable", TRUE);
	delete double010Props;

	PropertyList* enum012Props = enum012->GetProperties();
	enum012Props->SetEnumAsString("Value", "mm");
	enum012Props->SetLogical("Enable", TRUE);
	delete enum012Props;

	PropertyList* enum03Props = enum03->GetProperties();
	enum03Props->SetEnumAsString("Value", "包容圆柱体");
	delete enum03Props;

	PropertyList* plane0Props = plane0->GetProperties();
	plane0Props->SetLogical("Enable", FALSE);
	delete plane0Props;

	PropertyList* double014Props = double014->GetProperties();
	double014Props->SetDouble("Value", 30);
	delete double014Props;
}

void TongGrooveSideMilling::ReadXmlFile_PassGroove()
{
	try
	{
		ListOfCavity.clear();
		ListOfPassGroove.clear();

		PropertyList* File = nativeFileBrowser0->GetProperties();
		NXString FileString = File->GetString("Path");

		IXMLDOMDocumentPtr pXMLDom;
		HRESULT hr;
		CoInitialize(NULL);
		hr = pXMLDom.CreateInstance("msxml2.domdocument");
		if (FAILED(hr))
		{
			uc1601("Load XML file failed!", 1);
			return;
		}

		VARIANT var;
		VariantInit(&var);
		VARIANT_BOOL bFlag;
		BSTR FileName = ConvertToBSTR(FileString);
		V_BSTR(&var) = SysAllocString(FileName);
		V_VT(&var) = VT_BSTR;
		hr = pXMLDom->load(var, &bFlag);

		IXMLDOMElementPtr rootPtr;

		IXMLDOMNodeListPtr AllFeatureNodeList;
		pXMLDom->get_documentElement(&rootPtr);

		BSTR TagName;
		NXString NodeStr;

		rootPtr->get_nodeName(&TagName);

		char* CharString = _com_util::ConvertBSTRToString(TagName);

		NodeStr = CharString;

		char* nodename = "特征识别结果列表";
		if (!strstr(CharString, nodename))
		{
			uc1601("读入的不是特征识别结果列表！", 1);
			return;
		}

		rootPtr->get_childNodes(&AllFeatureNodeList);

		IXMLDOMNodePtr CavityNode;
		AllFeatureNodeList->get_item(3, &CavityNode);

		IXMLDOMNodeListPtr AllCavityNodeList;
		CavityNode->get_childNodes(&AllCavityNodeList);

		long CavitylistLength;
		AllCavityNodeList->get_length(&CavitylistLength);

		for (int i = 0; i < CavitylistLength; i++)
		{
			IXMLDOMNodePtr EachCavityNode;
			AllCavityNodeList->get_item(i, &EachCavityNode);

			IXMLDOMNodeListPtr EachCavityNodeList;
			EachCavityNode->get_childNodes(&EachCavityNodeList);

			BSTR CavityTagName;
			NXString CavityNodeStr;
			EachCavityNode->get_nodeName(&CavityTagName);
			char* CavityCharString = _com_util::ConvertBSTRToString(CavityTagName);
			CavityNodeStr = CavityCharString;

			char*PassGrooveNodeName = "通槽";

			if (strstr(CavityCharString, PassGrooveNodeName) != NULL)
			{
				PassGroove* pTempCavity = new PassGroove;
				pTempCavity->name = CavityCharString;


				IXMLDOMNodePtr EachPassGrooveTopNode;
				EachCavityNodeList->get_item(0, &EachPassGrooveTopNode);

				IXMLDOMNodeListPtr EachPassGrooveTopNodeList;
				EachPassGrooveTopNode->get_childNodes(&EachPassGrooveTopNodeList);

				long EachPassGrooveTopNodeListLength;
				EachPassGrooveTopNodeList->get_length(&EachPassGrooveTopNodeListLength);

				for (int j = 0; j < EachPassGrooveTopNodeListLength; j++)
				{
					IXMLDOMNodePtr EachPassGrooveTop;
					EachPassGrooveTopNodeList->get_item(j, &EachPassGrooveTop);

					BSTR TopFaceTag_bstr;
					EachPassGrooveTop->get_text(&TopFaceTag_bstr);

					NXString iStringTopFaceTag = ConvertToString(TopFaceTag_bstr);
					std::string TopFaceTagString(iStringTopFaceTag.GetUTF8Text());
					int TopFaceTag = atoi(TopFaceTagString.c_str());

					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == TopFaceTag)
						{
							pTempCavity->TopFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachPassGrooveBottomNode;
				EachCavityNodeList->get_item(1, &EachPassGrooveBottomNode);

				IXMLDOMNodeListPtr EachPassGrooveBottomNodeList;
				EachPassGrooveBottomNode->get_childNodes(&EachPassGrooveBottomNodeList);

				long EachPassGrooveBottomNodeListLength;
				EachPassGrooveBottomNodeList->get_length(&EachPassGrooveBottomNodeListLength);

				for (int j = 0; j < EachPassGrooveBottomNodeListLength; j++)
				{
					IXMLDOMNodePtr EachPassGrooveBottom;
					EachPassGrooveBottomNodeList->get_item(j, &EachPassGrooveBottom);

					BSTR BottomFaceTag_bstr;
					EachPassGrooveBottom->get_text(&BottomFaceTag_bstr);

					NXString iStringBottomFaceTag = ConvertToString(BottomFaceTag_bstr);
					std::string BottomFaceTagString(iStringBottomFaceTag.GetUTF8Text());
					int BottomFaceTag = atoi(BottomFaceTagString.c_str());

					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == BottomFaceTag)
						{
							pTempCavity->BottomFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachPassGrooveRightNode;
				EachCavityNodeList->get_item(2, &EachPassGrooveRightNode);

				IXMLDOMNodeListPtr EachPassGrooveRightNodeList;
				EachPassGrooveRightNode->get_childNodes(&EachPassGrooveRightNodeList);

				long EachPassGrooveRightNodeListLength;
				EachPassGrooveRightNodeList->get_length(&EachPassGrooveRightNodeListLength);

				for (int j = 0; j < EachPassGrooveRightNodeListLength; j++)
				{
					IXMLDOMNodePtr EachPassGrooveRight;
					EachPassGrooveRightNodeList->get_item(j, &EachPassGrooveRight);

					BSTR RightFaceTag_bstr;
					EachPassGrooveRight->get_text(&RightFaceTag_bstr);

					NXString iStringRightFaceTag = ConvertToString(RightFaceTag_bstr);
					std::string RightFaceTagString(iStringRightFaceTag.GetUTF8Text());
					int RightFaceTag = atoi(RightFaceTagString.c_str());

					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == RightFaceTag)
						{
							pTempCavity->RightFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachPassGrooveSideNode;
				EachCavityNodeList->get_item(3, &EachPassGrooveSideNode);

				IXMLDOMNodeListPtr EachPassGrooveSideNodeList;
				EachPassGrooveSideNode->get_childNodes(&EachPassGrooveSideNodeList);

				long EachPassGrooveSideNodeListLength;
				EachPassGrooveSideNodeList->get_length(&EachPassGrooveSideNodeListLength);

				for (int j = 0; j < EachPassGrooveSideNodeListLength; j++)
				{
					IXMLDOMNodePtr EachPassGrooveSide;
					EachPassGrooveSideNodeList->get_item(j, &EachPassGrooveSide);

					BSTR SideFaceTag_bstr;
					EachPassGrooveSide->get_text(&SideFaceTag_bstr);

					NXString iStringSideFaceTag = ConvertToString(SideFaceTag_bstr);
					std::string SideFaceTagString(iStringSideFaceTag.GetUTF8Text());
					int SideFaceTag = atoi(SideFaceTagString.c_str());

					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == SideFaceTag)
						{
							pTempCavity->SideFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}


				if (pTempCavity->SideFaceVector.size() != 0)
				{
					ListOfPassGroove.push_back(pTempCavity);
				}
			}
		}
		if (ListOfPassGroove.size() == 0)
		{
			uc1601("Read XML file failed!\n Error is:\n待加工零件模型与特征识别文件所属模型 不完全匹配!", 1);

			return;
		}


		IXMLDOMNodePtr NormalNode;
		AllFeatureNodeList->get_item(5, &NormalNode);

		IXMLDOMNodeListPtr NormalNodeList;
		NormalNode->get_childNodes(&NormalNodeList);

		IXMLDOMNodePtr NormalX;
		NormalNodeList->get_item(0, &NormalX);

		BSTR NormalX_bstr;
		NormalX->get_text(&NormalX_bstr);

		NXString iStringNormalX = ConvertToString(NormalX_bstr);
		std::string NormalXString(iStringNormalX.GetUTF8Text());

		std::string::size_type position;
		position = NormalXString.find(",");
		std::string subStr = NormalXString.substr(0, position);
		double X = atof(subStr.c_str());

		std::string::size_type EndY;
		EndY = NormalXString.length();
		std::string NormalYString = NormalXString.substr(position + 1, EndY);
		std::string::size_type position1;
		position1 = NormalYString.find(",");
		std::string subStr1 = NormalYString.substr(0, position1);
		double Y = atof(subStr1.c_str());

		std::string::size_type EndZ;
		EndZ = NormalYString.length();
		std::string NormalZString = NormalYString.substr(position1 + 1, EndZ);
		double Z = atof(NormalZString.c_str());

		NXOpen::Vector3d _Normal(X, Y, Z);
		ParameterSet.Approch_Normal = _Normal;
	}
	catch (exception& ex2)
	{
		uc1601("Read XML file failed!\n Error is:\n几何模型与特征识别模型不完全匹配!", 1);

	}
}

BSTR TongGrooveSideMilling::ConvertToBSTR(NXString iString)
{
	char* istr = (char*)iString.GetUTF8Text();
	BSTR bstr = _com_util::ConvertStringToBSTR(istr);
	return bstr;
}

NXString TongGrooveSideMilling::ConvertToString(BSTR bstr)
{
	char* istr = _com_util::ConvertBSTRToString(bstr);
	NXString str(istr);
	return str;
}

void TongGrooveSideMilling::SelectedFaceCampare(std::vector<NXOpen::Face*> SelectedFaceList, std::vector<NXOpen::Face*> FaceList)
{
	bool SearchFaceFlag;
	std::vector<Face*>::iterator iter = SelectedFaceList.begin();
	while (iter != SelectedFaceList.end())
	{
		Face* SelectedFace = *iter;

		int FaceListSize = FaceList.size();
		for (int j = 0; j != FaceListSize; j++)
		{
			Face* PassGrooveTopFace = PassGrooveTopFaceList[j];
			tag_t SelectedFaceTag = SelectedFace->Tag();
			tag_t PassGrooveTopFaceTag = PassGrooveTopFace->Tag();

			if (SelectedFaceTag == PassGrooveTopFaceTag)
			{
				SearchFaceFlag = TRUE;
				break;
			}
			else
			{
				SearchFaceFlag = FALSE;
			}
		}

		if (SearchFaceFlag)
		{
			iter++;
		}

		else
		{
			char* str("请选择正确的通槽顶面");
			uc1601(str, 1);
			break;
		}
	}
}