//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  Z:\02_430\Code\23FBM_NX11.0VS2013\FBM_NX11_NUAA_Win32_D0507\xin\HoleDrilling.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 05-10-2024  (Format: mm-dd-yyyy)
//              Time: 14:13
//
//==============================================================================

#ifndef HOLEDRILLING_H_INCLUDED
#define HOLEDRILLING_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_FileSelection.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/BlockStyler_FaceCollector.hxx>
#include <NXOpen/BlockStyler_IntegerBlock.hxx>
#include <NXOpen/BlockStyler_Label.hxx>
#include <NXOpen/BlockStyler_TabControl.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_Button.hxx>

#include <NXOpen/Part.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/NXObjectManager.hxx>
#include <NXOpen/CAM_CAMObject.hxx>
#include <NXOpen/CartesianCoordinateSystem.hxx>
#include <NXOpen/CAM_NCGroup.hxx>
#include <NXOpen/CAM_MillToolBuilder.hxx>
#include <NXOpen/CAM_CAMSetup.hxx>
#include <NXOpen/CAM_NCGroupCollection.hxx>
#include <NXOpen/CAM_Tool.hxx>
#include <NXOpen/CAM_InheritableDoubleBuilder.hxx>
#include <uf_ui.h>
#include <uf.h>

#include <comdef.h>
#include <comutil.h>
#include <vector>
#include <math.h>
#include <algorithm>


#include "PublicFunctions.h"
#include "FeaturePublicClass.h"
#include "ProcessPublicClass.h"
#include "SLHoleDrillingcmd.h"


#include <NXSigningResource.cpp>


//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport HoleDrilling
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    HoleDrilling();
    ~HoleDrilling();
    int Show();

	bool ReadXMLOK;
	NXOpen::Part * workPart;
	NXOpen::Body * selectedBody;
	std::vector<Hole*> ListOfHole;      //读取的hole列表
	std::vector<Hole*> SelectedHoleList;
	std::vector<double> HoleDiameter;
	std::vector<NXString>DiameterOfHoleList;
	std::vector<NXOpen::Face*> RemoveHoleWallFaceList;
	std::vector<Face*> AllFaces;
	//230705新增
	std::vector<DirectionNormalHole*> ListOfDirectionNormalHole;//轴向普通孔列表1
	std::vector<DirectionRightHole*> ListOfDirectionRightHole;//轴向单侧斜角通孔1
	std::vector<DirectionBlindHole*> ListOfDirectionBlindHole;//轴向无倒角盲孔1
	std::vector<WallNormalHole*> ListOfWallNormalHole;//壁面普通通孔1	
	std::vector<WallCircleCombineHole*>ListOfWallCircleCombineHole;//壁面复合通孔1	
	std::vector<RibCombineHole*>ListOfRibCombineHole;//筋面复合通孔	
	std::vector<BossNormalHole*>ListOfBossNormalHole;//凸台无倒角通孔1
	std::vector<BossOneRightHole*> ListOfBossOneRightHole;//凸台单侧斜角通孔1
	std::vector<BossOneCircleHole*> ListOfBossOneCircleHole;//凸台单侧圆角通孔1
	std::vector<BossDoubleRightHole*> ListOfBossDoubleRightHole; //凸台双侧斜角通孔1
	std::vector<BossDoubleCircleHole*> ListOfBossDoubleCircleHole;//凸台双侧圆角通孔1
	std::vector<BossOneRightOneCircleHole*> ListOfBossOneRightOneCircleHole;//凸台单侧斜角单侧圆角通孔1
	std::vector<BossManyLayerHole*> ListOfBossManyLayerHole;//凸台多层通孔
	std::vector<BossOutsideWideCombineHole*> ListOfBossOutsideWideCombineHole;//凸台外宽内窄复合通孔1
	std::vector<BossInsideWideCombineHole*> ListOfBossInsideWideCombineHole;//凸台内宽外窄复合通孔1
	std::vector<BossMidCricleCombineHole*> ListOfBossMidCricleCombineHole;//凸台中圆角复合通孔
	std::vector<BossNormalBlindHole*> ListOfBossNormalBlindHole;//凸台无倒角盲孔1
	std::vector<BossRightBlindHole*> ListOfBossRightBlindHole;//凸台倒斜角盲孔1
	std::vector<Other3Hole*>ListOfBossOtherHole;//凸台其它孔
	AllFeatureHole allFeatureHolelist;//孔特征列表集合


	HoleProcessParameter ParameterSet;//中心钻工艺参数

	std::vector<CAM::CAMObject*> ProgramMembers;
	std::vector<NXString> ProgramStringList;
	std::vector<CAM::CAMObject*> ToolMembers;
	std::vector<NXString> ToolStringList;
	std::vector<CAM::CAMObject*> MCSMembers;
	std::vector<NXString> MCSStringList;
	std::vector<CAM::CAMObject*> MethodMembers;
	std::vector<NXString> MethodStringList;

	std::vector<NXOpen::Face*> SelectedHoleInWallFaceList0;
	std::vector<NXOpen::Face*> SelectedHoleInWallFaceList;
	std::vector<NXOpen::Face*> HoleInWallFaceList;

    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the HoleDrilling.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);

	void InitialParameter();
	void ReadXmlFile_Hole();
	void SelectedFaceCampare(std::vector<NXOpen::Face*> SelectedHoleInWallFace, std::vector<NXOpen::Face*> HoleInWallFace);
	BSTR ConvertToBSTR(NXString iString);
	NXString ConvertToString(BSTR bstr);
	//void get_Allhole_Diam(std::vector<Hole*> List);
	/*void get_hole_Diam2() ;*/
	void get_face_minRad(Face* iFace, double & MinFaceRad);
	void get_onehole_diameter(Hole* SomeHole, double &Diameter);
	std::vector<NXOpen::Face*> HoleDrilling::Transfer_to_select_hole_in_face(std::vector<NXOpen::Face*> SelectedHoleInWallFaceList0, std::vector<NXOpen::Face*> SelectedHoleInWallFaceList, AllFeatureHole allFeatureHolelist);
	bool HoleDrilling::Avoid_repetition_hole(std::vector<Face*> SelectedHoleInWallFaceList0, tag_t InWallFaceTag);

    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* bodySelect0;// Block type: Body Collector
    NXOpen::BlockStyler::FileSelection* nativeFileBrowser0;// Block type: NativeFileBrowser
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group9;// Block type: Group
    NXOpen::BlockStyler::Toggle* toggle0;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle09;// Block type: Toggle
    NXOpen::BlockStyler::Enumeration* enum01;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group10;// Block type: Group
    NXOpen::BlockStyler::Toggle* toggle01;// Block type: Toggle
    NXOpen::BlockStyler::FaceCollector* face_select0;// Block type: Face Collector
    NXOpen::BlockStyler::Toggle* toggle011;// Block type: Toggle
    NXOpen::BlockStyler::IntegerBlock* integer01;// Block type: Integer
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::Label* label0;// Block type: Label
    NXOpen::BlockStyler::Toggle* toggle02;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle03;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle04;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle05;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle06;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle07;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle08;// Block type: Toggle
    NXOpen::BlockStyler::TabControl* tabControl;// Block type: Tabs Page
    NXOpen::BlockStyler::Group* tabPage;// Block type: Group
    NXOpen::BlockStyler::Group* group4;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum11;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum12;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum13;// Block type: Enumeration
    NXOpen::BlockStyler::Label* label01;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double15;// Block type: Double
    NXOpen::BlockStyler::Label* label02;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double16;// Block type: Double
    NXOpen::BlockStyler::Label* label03;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double17;// Block type: Double
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double13;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double14;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage3;// Block type: Group
    NXOpen::BlockStyler::Group* group5;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum21;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum22;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum23;// Block type: Enumeration
    NXOpen::BlockStyler::Label* label04;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double25;// Block type: Double
    NXOpen::BlockStyler::Label* label05;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double26;// Block type: Double
    NXOpen::BlockStyler::Label* label06;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double27;// Block type: Double
    NXOpen::BlockStyler::Group* group6;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double23;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double24;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage1;// Block type: Group
    NXOpen::BlockStyler::Group* group41;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum111;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum121;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum131;// Block type: Enumeration
    NXOpen::BlockStyler::Label* label07;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double151;// Block type: Double
    NXOpen::BlockStyler::Label* label08;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double161;// Block type: Double
    NXOpen::BlockStyler::Label* label09;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double171;// Block type: Double
    NXOpen::BlockStyler::Group* group31;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double131;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double141;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage4;// Block type: Group
    NXOpen::BlockStyler::Group* group42;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum112;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum122;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum132;// Block type: Enumeration
    NXOpen::BlockStyler::Label* label010;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double152;// Block type: Double
    NXOpen::BlockStyler::Label* label011;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double162;// Block type: Double
    NXOpen::BlockStyler::Label* label012;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double172;// Block type: Double
    NXOpen::BlockStyler::Group* group32;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double132;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double142;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage41;// Block type: Group
    NXOpen::BlockStyler::Group* group421;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum1121;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum1221;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum1321;// Block type: Enumeration
    NXOpen::BlockStyler::Label* label013;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double1521;// Block type: Double
    NXOpen::BlockStyler::Label* label014;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double1621;// Block type: Double
    NXOpen::BlockStyler::Label* label015;// Block type: Label
    NXOpen::BlockStyler::DoubleBlock* double1721;// Block type: Double
    NXOpen::BlockStyler::Group* group321;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double1321;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double1421;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage34;// Block type: Group
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum214;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum224;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum234;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double204;// Block type: Double
    NXOpen::BlockStyler::Enumeration* enum02;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double2041;// Block type: Double
    NXOpen::BlockStyler::Enumeration* enum021;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double214;// Block type: Double
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double0;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double02;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double011;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double234;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double244;// Block type: Double
    NXOpen::BlockStyler::Group* group7;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum05;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double07;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage35;// Block type: Group
    NXOpen::BlockStyler::Group* group8;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum215;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum225;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double205;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double215;// Block type: Double
    NXOpen::BlockStyler::IntegerBlock* integer0;// Block type: Integer
    NXOpen::BlockStyler::Group* group22;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double01;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double012;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double0111;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double2341;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double2441;// Block type: Double
    NXOpen::BlockStyler::Group* group71;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum051;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double0101;// Block type: Double
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    
};
#endif //HOLEDRILLING_H_INCLUDED
