//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\ug12\Desktop\HuNXTool\Application\setholecolor.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: ug12
//              Version: NX 12
//              Date: 04-09-2026  (Format: mm-dd-yyyy)
//              Time: 20:52 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//==============================================================================

//------------------------------------------------------------------------------
// These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "setholecolor.hpp"

#include <vector>
#include <set>
#include <string>
#include <sstream>
#include <cmath>

#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/BodyCollection.hxx>

#include <NXOpen/Body.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Edge.hxx>
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/ListingWindow.hxx>
#include <NXOpen/NXObjectManager.hxx>

#include <uf.h>
#include <uf_obj.h>
#include <uf_modl.h>

using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// 全局缓存：识别出来的孔面
//------------------------------------------------------------------------------
namespace
{
	std::vector<NXOpen::DisplayableObject*> g_holeFaces;

	struct DiagnoseInfo
	{
		std::string partName;
		int totalBodies;
		int solidBodies;
		int totalFaces;
		int planarFaces;
		int cylindricalFaces;
		int conicalFaces;
		int otherFaces;
		int candidateHoleFaces;

		DiagnoseInfo()
		{
			partName = "";
			totalBodies = 0;
			solidBodies = 0;
			totalFaces = 0;
			planarFaces = 0;
			cylindricalFaces = 0;
			conicalFaces = 0;
			otherFaces = 0;
			candidateHoleFaces = 0;
		}
	};

	double Dot3(const double a[3], const double b[3])
	{
		return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
	}

	double Norm3(const double v[3])
	{
		return std::sqrt(Dot3(v, v));
	}

	bool Normalize3(double v[3])
	{
		double n = Norm3(v);
		if (n < 1.0e-9)
			return false;
		v[0] /= n;
		v[1] /= n;
		v[2] /= n;
		return true;
	}

	bool IsParallel(const double a[3], const double b[3], double tolCos)
	{
		double aa[3] = { a[0], a[1], a[2] };
		double bb[3] = { b[0], b[1], b[2] };

		if (!Normalize3(aa) || !Normalize3(bb))
			return false;

		return std::fabs(Dot3(aa, bb)) >= tolCos;
	}

	bool AskFaceData(
		tag_t faceTag,
		int& type,
		double point[3],
		double dir[3],
		double box[6],
		double& radius,
		double& radData,
		int& normDir)
	{
		int rc = UF_MODL_ask_face_data(
			faceTag,
			&type,
			point,
			dir,
			box,
			&radius,
			&radData,
			&normDir);

		return (rc == 0);
	}

	bool GetPlanarFaceNormal(tag_t faceTag, double normal[3])
	{
		int type = 0;
		int normDir = 0;
		double point[3] = { 0.0, 0.0, 0.0 };
		double dir[3] = { 0.0, 0.0, 0.0 };
		double box[6] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
		double radius = 0.0;
		double radData = 0.0;

		if (!AskFaceData(faceTag, type, point, dir, box, radius, radData, normDir))
			return false;

		if (type != UF_MODL_PLANAR_FACE)
			return false;

		normal[0] = dir[0];
		normal[1] = dir[1];
		normal[2] = dir[2];
		return Normalize3(normal);
	}

	bool GetCylOrConeAxis(tag_t faceTag, int& outType, double axis[3], double& radius)
	{
		int type = 0;
		int normDir = 0;
		double point[3] = { 0.0, 0.0, 0.0 };
		double dir[3] = { 0.0, 0.0, 0.0 };
		double box[6] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
		double r = 0.0;
		double radData = 0.0;

		if (!AskFaceData(faceTag, type, point, dir, box, r, radData, normDir))
			return false;

		if (type != UF_MODL_CYLINDRICAL_FACE && type != UF_MODL_CONICAL_FACE)
			return false;

		axis[0] = dir[0];
		axis[1] = dir[1];
		axis[2] = dir[2];
		if (!Normalize3(axis))
			return false;

		outType = type;
		radius = r;
		return true;
	}

	int GetSimpleFaceType(tag_t faceTag)
	{
		int type = 0;
		int normDir = 0;
		double point[3] = { 0.0, 0.0, 0.0 };
		double dir[3] = { 0.0, 0.0, 0.0 };
		double box[6] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
		double radius = 0.0;
		double radData = 0.0;

		if (!AskFaceData(faceTag, type, point, dir, box, radius, radData, normDir))
			return -1;

		return type;
	}

	void ClearHighlight()
	{
		for (size_t i = 0; i < g_holeFaces.size(); ++i)
		{
			try
			{
				if (g_holeFaces[i] != NULL)
					g_holeFaces[i]->Unhighlight();
			}
			catch (...)
			{
			}
		}
		g_holeFaces.clear();
	}

	void HighlightFaces(const std::vector<NXOpen::DisplayableObject*>& faces)
	{
		for (size_t i = 0; i < faces.size(); ++i)
		{
			if (faces[i] != NULL)
				faces[i]->Highlight();
		}
	}

	void ColorFacesRed(const std::vector<NXOpen::DisplayableObject*>& faces)
	{
		for (size_t i = 0; i < faces.size(); ++i)
		{
			if (faces[i] != NULL)
			{
				faces[i]->SetColor(186);
				faces[i]->RedisplayObject();
			}
		}
	}

	bool CandidateFaceLooksLikeHoleWall(
		NXOpen::Face* face,
		NXOpen::ListingWindow* lw)
	{
		if (face == NULL)
			return false;

		int faceType = 0;
		double axis[3] = { 0.0, 0.0, 0.0 };
		double radius = 0.0;

		if (!GetCylOrConeAxis(face->Tag(), faceType, axis, radius))
			return false;

		if (radius < 1.0e-4)
			return false;

		std::vector<NXOpen::Edge*> edges = face->GetEdges();

		int planarPerpCount = 0;
		int coaxialConeCount = 0;

		for (size_t i = 0; i < edges.size(); ++i)
		{
			NXOpen::Edge* edge = edges[i];
			if (edge == NULL)
				continue;

			std::vector<NXOpen::Face*> nbrFaces = edge->GetFaces();

			for (size_t j = 0; j < nbrFaces.size(); ++j)
			{
				NXOpen::Face* nbr = nbrFaces[j];
				if (nbr == NULL || nbr->Tag() == face->Tag())
					continue;

				double planeNormal[3] = { 0.0, 0.0, 0.0 };
				if (GetPlanarFaceNormal(nbr->Tag(), planeNormal))
				{
					if (IsParallel(planeNormal, axis, 0.97))
					{
						++planarPerpCount;
					}
					continue;
				}

				int nbrType = 0;
				double nbrAxis[3] = { 0.0, 0.0, 0.0 };
				double nbrRadius = 0.0;
				if (GetCylOrConeAxis(nbr->Tag(), nbrType, nbrAxis, nbrRadius))
				{
					if (nbrType == UF_MODL_CONICAL_FACE && IsParallel(nbrAxis, axis, 0.97))
					{
						++coaxialConeCount;
					}
				}
			}
		}

		if (lw != NULL)
		{
			std::ostringstream oss;
			oss << "候选检查 faceTag=" << face->Tag()
				<< ", planarPerpCount=" << planarPerpCount
				<< ", coaxialConeCount=" << coaxialConeCount
				<< ", radius=" << radius;
			lw->WriteLine(oss.str().c_str());
		}

		if (planarPerpCount >= 1)
			return true;

		if (coaxialConeCount >= 1)
			return true;

		return false;
	}

	void DiagnoseAndFindHoleFaces(
		NXOpen::Part* partToScan,
		std::vector<NXOpen::DisplayableObject*>& outFaces,
		DiagnoseInfo& info,
		NXOpen::ListingWindow* lw)
	{
		outFaces.clear();
		info = DiagnoseInfo();

		if (partToScan == NULL)
			return;

		info.partName = partToScan->Leaf().GetText();

		std::set<tag_t> uniqueFaceTags;

		NXOpen::BodyCollection* bodyCollection = partToScan->Bodies();
		if (bodyCollection == NULL)
			return;

		for (NXOpen::BodyCollection::iterator it = bodyCollection->begin();
		it != bodyCollection->end();
			++it)
		{
			NXOpen::Body* body = *it;
			if (body == NULL)
				continue;

			++info.totalBodies;

			if (!body->IsSolidBody())
				continue;

			++info.solidBodies;

			std::vector<NXOpen::Face*> faces = body->GetFaces();

			if (lw != NULL)
			{
				std::ostringstream oss;
				oss << "扫描 Part=" << info.partName
					<< " , Body tag=" << body->Tag()
					<< " , faceCount=" << faces.size();
				lw->WriteLine(oss.str().c_str());
			}

			for (size_t j = 0; j < faces.size(); ++j)
			{
				NXOpen::Face* face = faces[j];
				if (face == NULL)
					continue;

				++info.totalFaces;

				int simpleType = GetSimpleFaceType(face->Tag());
				if (simpleType == UF_MODL_PLANAR_FACE)
				{
					++info.planarFaces;
				}
				else if (simpleType == UF_MODL_CYLINDRICAL_FACE)
				{
					++info.cylindricalFaces;
				}
				else if (simpleType == UF_MODL_CONICAL_FACE)
				{
					++info.conicalFaces;
				}
				else
				{
					++info.otherFaces;
				}

				if (CandidateFaceLooksLikeHoleWall(face, lw))
				{
					if (uniqueFaceTags.insert(face->Tag()).second)
					{
						outFaces.push_back(face);
						++info.candidateHoleFaces;
					}
				}
			}
		}
	}
}

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(setholecolor::theSession) = NULL;
UI *(setholecolor::theUI) = NULL;

//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
setholecolor::setholecolor()
{
	try
	{
		setholecolor::theSession = NXOpen::Session::GetSession();
		setholecolor::theUI = UI::GetUI();
		theDlxFileName = "setholecolor.dlx";
		theDialog = setholecolor::theUI->CreateDialog(theDlxFileName);
		theDialog->AddOkHandler(make_callback(this, &setholecolor::ok_cb));
		theDialog->AddUpdateHandler(make_callback(this, &setholecolor::update_cb));
		theDialog->AddInitializeHandler(make_callback(this, &setholecolor::initialize_cb));
		theDialog->AddDialogShownHandler(make_callback(this, &setholecolor::dialogShown_cb));
	}
	catch (exception& ex)
	{
		throw;
	}
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
setholecolor::~setholecolor()
{
	if (theDialog != NULL)
	{
		delete theDialog;
		theDialog = NULL;
	}
}

//------------------------------- DIALOG LAUNCHING ---------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
	setholecolor *thesetholecolor = NULL;
	try
	{
		thesetholecolor = new setholecolor();
		thesetholecolor->Show();
	}
	catch (exception& ex)
	{
		setholecolor::theUI->NXMessageBox()->Show(
			"Block Styler",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what());
	}
	if (thesetholecolor != NULL)
	{
		delete thesetholecolor;
		thesetholecolor = NULL;
	}
}

//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
	return (int)Session::LibraryUnloadOptionImmediately;
}

//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
	try
	{
	}
	catch (exception& ex)
	{
		setholecolor::theUI->NXMessageBox()->Show(
			"Block Styler",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what());
	}
}

int setholecolor::Show()
{
	try
	{
		theDialog->Show();
	}
	catch (exception& ex)
	{
		setholecolor::theUI->NXMessageBox()->Show(
			"Block Styler",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what());
	}
	return 0;
}

//------------------------------------------------------------------------------
// Callback Name: initialize_cb
//------------------------------------------------------------------------------
void setholecolor::initialize_cb()
{
	try
	{
		group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
		toggle0 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0"));
		toggle01 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle01"));
	}
	catch (exception& ex)
	{
		setholecolor::theUI->NXMessageBox()->Show(
			"Block Styler",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what());
	}
}

//------------------------------------------------------------------------------
// Callback Name: dialogShown_cb
//------------------------------------------------------------------------------
void setholecolor::dialogShown_cb()
{
	try
	{
	}
	catch (exception& ex)
	{
		setholecolor::theUI->NXMessageBox()->Show(
			"Block Styler",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what());
	}
}

//------------------------------------------------------------------------------
// Callback Name: update_cb
//------------------------------------------------------------------------------
int setholecolor::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
	try
	{
		Part* workPart = theSession->Parts()->Work();
		Part* displayPart = theSession->Parts()->Display();
		ListingWindow* lw = theSession->ListingWindow();
		lw->Open();

		if (workPart == NULL && displayPart == NULL)
		{
			theUI->NXMessageBox()->Show(
				"提示",
				NXOpen::NXMessageBox::DialogTypeWarning,
				"当前没有打开的工作部件或显示部件。");
			return 0;
		}

		if (block == toggle0)
		{
			if (toggle0->Value())
			{
				ClearHighlight();

				DiagnoseInfo workInfo;
				DiagnoseInfo displayInfo;
				std::vector<NXOpen::DisplayableObject*> workFaces;
				std::vector<NXOpen::DisplayableObject*> displayFaces;

				if (workPart != NULL)
					DiagnoseAndFindHoleFaces(workPart, workFaces, workInfo, lw);

				if (displayPart != NULL)
				{
					if (displayPart != workPart)
						DiagnoseAndFindHoleFaces(displayPart, displayFaces, displayInfo, lw);
					else
						displayInfo = workInfo;
				}

				bool useDisplayPart = false;

				// 优先用 workPart；如果 workPart 没拿到 body，而 displayPart 拿到了，则回退到 displayPart
				if (workInfo.totalBodies > 0 || workInfo.solidBodies > 0)
				{
					g_holeFaces = workFaces;
					useDisplayPart = false;
				}
				else if (displayInfo.totalBodies > 0 || displayInfo.solidBodies > 0)
				{
					g_holeFaces = displayFaces;
					useDisplayPart = true;
				}
				else
				{
					g_holeFaces.clear();
				}

				HighlightFaces(g_holeFaces);

				std::ostringstream oss;
				oss << "诊断完成。\n\n";

				if (workPart != NULL)
				{
					oss << "[Work Part] " << workInfo.partName << "\n"
						<< "Body总数: " << workInfo.totalBodies << "\n"
						<< "实体Body数: " << workInfo.solidBodies << "\n"
						<< "总面数: " << workInfo.totalFaces << "\n"
						<< "平面数: " << workInfo.planarFaces << "\n"
						<< "圆柱面数: " << workInfo.cylindricalFaces << "\n"
						<< "圆锥面数: " << workInfo.conicalFaces << "\n"
						<< "其他面数: " << workInfo.otherFaces << "\n"
						<< "疑似孔面数: " << workInfo.candidateHoleFaces << "\n\n";
				}

				if (displayPart != NULL)
				{
					oss << "[Display Part] " << displayInfo.partName << "\n"
						<< "Body总数: " << displayInfo.totalBodies << "\n"
						<< "实体Body数: " << displayInfo.solidBodies << "\n"
						<< "总面数: " << displayInfo.totalFaces << "\n"
						<< "平面数: " << displayInfo.planarFaces << "\n"
						<< "圆柱面数: " << displayInfo.cylindricalFaces << "\n"
						<< "圆锥面数: " << displayInfo.conicalFaces << "\n"
						<< "其他面数: " << displayInfo.otherFaces << "\n"
						<< "疑似孔面数: " << displayInfo.candidateHoleFaces << "\n\n";
				}

				if (useDisplayPart)
					oss << "本次高亮使用的是 Display Part 的扫描结果。";
				else
					oss << "本次高亮使用的是 Work Part 的扫描结果。";

				theUI->NXMessageBox()->Show(
					"模型/孔识别诊断结果",
					NXOpen::NXMessageBox::DialogTypeInformation,
					oss.str().c_str());

				toggle0->SetValue(false);
			}
		}
		else if (block == toggle01)
		{
			if (toggle01->Value())
			{
				if (g_holeFaces.empty())
				{
					DiagnoseInfo workInfo;
					DiagnoseInfo displayInfo;
					std::vector<NXOpen::DisplayableObject*> workFaces;
					std::vector<NXOpen::DisplayableObject*> displayFaces;

					if (workPart != NULL)
						DiagnoseAndFindHoleFaces(workPart, workFaces, workInfo, lw);

					if (displayPart != NULL)
					{
						if (displayPart != workPart)
							DiagnoseAndFindHoleFaces(displayPart, displayFaces, displayInfo, lw);
						else
							displayInfo = workInfo;
					}

					if (workInfo.totalBodies > 0 || workInfo.solidBodies > 0)
						g_holeFaces = workFaces;
					else
						g_holeFaces = displayFaces;

					HighlightFaces(g_holeFaces);
				}

				if (g_holeFaces.empty())
				{
					theUI->NXMessageBox()->Show(
						"提示",
						NXOpen::NXMessageBox::DialogTypeWarning,
						"当前没有可标红的疑似孔面。请先点第一个按钮查看诊断结果。");
				}
				else
				{
					ColorFacesRed(g_holeFaces);

					std::ostringstream oss;
					oss << "标红完成。\n"
						<< "已标红孔面数量: " << g_holeFaces.size();

					theUI->NXMessageBox()->Show(
						"孔着色结果",
						NXOpen::NXMessageBox::DialogTypeInformation,
						oss.str().c_str());
				}

				toggle01->SetValue(false);
			}
		}
	}
	catch (exception& ex)
	{
		setholecolor::theUI->NXMessageBox()->Show(
			"Block Styler",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what());
	}
	return 0;
}


//------------------------------------------------------------------------------
// Callback Name: ok_cb
//------------------------------------------------------------------------------
int setholecolor::ok_cb()
{
	int errorCode = 0;
	try
	{
	}
	catch (exception& ex)
	{
		errorCode = 1;
		setholecolor::theUI->NXMessageBox()->Show(
			"Block Styler",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what());
	}
	return errorCode;
}

//------------------------------------------------------------------------------
// Function Name: GetBlockProperties
//------------------------------------------------------------------------------
PropertyList* setholecolor::GetBlockProperties(const char *blockID)
{
	return theDialog->GetBlockProperties(blockID);
}