//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  Z:\UG\FBM2023\FBM\BatchModifyParameter\BatchModifyParameter.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 07-25-2023  (Format: mm-dd-yyyy)
//              Time: 15:14
//
//==============================================================================

#ifndef BATCHMODIFYPARAMETER_H_INCLUDED
#define BATCHMODIFYPARAMETER_H_INCLUDED

#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_Button.hxx>

#include  "uf_cutter.h" 
#include "uf_all.h"
#include "uf_cam_all.h"
#include "HuNXOpen.h"
#include "NXOpen_CAM_ALL_8.5.3.3.h"
#include  "uf_ui_ont.h"
//#include  "uf_cutter.h" 
//#include  "uf_param.h"
//#include  "uf_object_types.h"
//#include <uf_param_indices.h>


using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport BatchModifyParameter
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    BatchModifyParameter();
    ~BatchModifyParameter();
    int Show();
    
    void initialize_cb();
    void dialogShown_cb();
	
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
	void GetAllOperTag(tag_t groupTag, vector<tag_t> &vOperTags);
	void GetAllToolTag(tag_t groupTag, vector<tag_t> &vToolTags);
	void GetAllToolNames(tag_t groupTag, vector<string> &vAllToolNames);
	void BatchModifyParameter::GetAllToolTag2(tag_t groupTag, vector<tag_t> &vToolTags);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* doubleJingeilv;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* doubleZhuanshu;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* doubleYuliang;// Block type: Double
    //NXOpen::BlockStyler::DoubleBlock* doublesaftdistance;// Block type: Double
    //NXOpen::BlockStyler::Enumeration* steptype;// Block type: Enumeration
    //NXOpen::BlockStyler::DoubleBlock* doublestepvalue;// Block type: Double
    NXOpen::BlockStyler::Button* buttonshengcheng;// Block type: Button
    
};
#endif //BATCHMODIFYPARAMETER_H_INCLUDED
