//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  Z:\UG\FBM2023\FBM\BatchModifyParameter\BatchModifyParameter.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: @Fengliang
//              Version: NX 11
//              Date: 07-25-2023  (Format: mm-dd-yyyy)
//              Time: 15:14 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//==============================================================================

//These includes are needed for the following template code
#include "BatchModifyParameter.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

Session *(BatchModifyParameter::theSession) = NULL;
UI *(BatchModifyParameter::theUI) = NULL;
BatchModifyParameter::BatchModifyParameter()
{
    try
    {
        BatchModifyParameter::theSession = NXOpen::Session::GetSession();
        BatchModifyParameter::theUI = UI::GetUI();
        theDlxFileName = "BatchModifyParameter.dlx";
        theDialog = BatchModifyParameter::theUI->CreateDialog(theDlxFileName);
        theDialog->AddOkHandler(make_callback(this, &BatchModifyParameter::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &BatchModifyParameter::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &BatchModifyParameter::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &BatchModifyParameter::dialogShown_cb));
    }
    catch(exception& ex)
    {
        throw;
    }
}

BatchModifyParameter::~BatchModifyParameter()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
	UF_initialize();
    BatchModifyParameter *theBatchModifyParameter = NULL;
    try
    {
        theBatchModifyParameter = new BatchModifyParameter();
        theBatchModifyParameter->Show();
    }
    catch(exception& ex)
    {
        BatchModifyParameter::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theBatchModifyParameter != NULL)
    {
        delete theBatchModifyParameter;
        theBatchModifyParameter = NULL;
    }
	UF_terminate();
}

extern "C" DllExport int ufusr_ask_unload()
{
    return (int)Session::LibraryUnloadOptionImmediately;  
}

extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
    }
    catch(exception& ex)
    {
        BatchModifyParameter::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int BatchModifyParameter::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        BatchModifyParameter::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}


//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void BatchModifyParameter::initialize_cb()
{
    try
    {
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        doubleJingeilv = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("doubleJingeilv"));
        doubleZhuanshu = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("doubleZhuanshu"));
        doubleYuliang = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("doubleYuliang"));    
        buttonshengcheng = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("buttonshengcheng"));
    }
    catch(exception& ex)
    {
        BatchModifyParameter::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//------------------------------------------------------------------------------
void BatchModifyParameter::dialogShown_cb()
{
	PropertyList* double012Props = doubleJingeilv->GetProperties();
	double012Props->SetDouble("Value", 0);
	delete double012Props;

	PropertyList* double0121Props = doubleZhuanshu->GetProperties();
	double0121Props->SetDouble("Value", 0);
	delete double0121Props;

	PropertyList* double0122Props = doubleYuliang->GetProperties();
	double0122Props->SetDouble("Value", 0);
	delete double0122Props;

    try
    {
		//获取加工设置的TAG
		tag_t setup_tag = NULL_TAG;
		UF_SETUP_ask_setup(&setup_tag);
		if (setup_tag == NULL_TAG)
		{
			uc1601("请先初始化加工环境", 1);
			return;
		}

		//获得程序视图下的根节点
		tag_t programRootgroup = NULL_TAG;
		UF_SETUP_ask_program_root(setup_tag, &programRootgroup);

		//递归方式获得所有的toolTAG
		vector<tag_t> vToolTags;
		
		GetAllToolTag2(programRootgroup, vToolTags);
		vector<NXOpen::NXString> vAllToolNames;
		vector<string> vToolNames;
		for (int i = 0; i < vToolTags.size(); i++)
		{
			char name[500];
			UF_OBJ_ask_name(vToolTags[i], name);
			vAllToolNames.push_back(name);
			
		}
		enum0->SetEnumMembers(vAllToolNames);
    }
    catch(exception& ex)
    {
        BatchModifyParameter::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int BatchModifyParameter::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == enum0)
        {
        }
        else if(block == doubleJingeilv)
        {
        }
        else if(block == doubleZhuanshu)
        {
        }
        else if(block == doubleYuliang)
        {
        }
        else if(block == buttonshengcheng)
        {
			double jingheilv = doubleJingeilv->Value();
			double zhuanshu = doubleZhuanshu->Value();
			double yuliang = doubleYuliang->Value();			
			//由刀具名称获取tag
			tag_t setup_tag = NULL_TAG;
			UF_SETUP_ask_setup(&setup_tag);

			tag_t mctRootgroup = NULL_TAG;
			UF_SETUP_ask_mct_root(setup_tag, &mctRootgroup);
			tag_t toolTag = NULL_TAG;

			string strToolName = enum0->ValueAsString().GetLocaleText();
			const char* ToolName1 = nullptr;
			ToolName1 = strToolName.c_str();

			char* ToolName = nullptr;                       //初始化char*类型
			ToolName = const_cast<char*>(ToolName1);           //const char*类型转char*类型
			UF_NCGROUP_ask_object_of_name(mctRootgroup, ToolName, &toolTag);

			int count = 0;
			tag_t * objects;
			UF_UI_ONT_ask_selected_nodes(&count, &objects);
			for (int i = 0; i < count; i++)
			{
				tag_t operTag = objects[i];
				int type = 0, subtype = 0;
				UF_OBJ_ask_type_and_subtype(operTag, &type, &subtype);
				if (type == UF_machining_operation_type)
				{
					UF_NCGROUP_accept_member(toolTag, objects[i]);
					/*UF_NCGROUP_accept_member(toolTag, objects[i]);*/
					//设置转数	
					if (zhuanshu !=0)
					{
						UF_PARAM_set_double_value(objects[i], UF_PARAM_SPINDLE_RPM, zhuanshu);
					}
					
					if (jingheilv != 0)
					{
						//设置进给率
						UF_PARAM_feedrate_t feed_value;
						UF_PARAM_ask_subobj_ptr_value(objects[i], UF_PARAM_FEED_CUT, &feed_value);
						feed_value.value = jingheilv;
						UF_PARAM_set_subobj_ptr_value(objects[i], UF_PARAM_FEED_CUT, &feed_value);
					}
					
					if (yuliang !=0)
					{
						//设置部件余量
						UF_PARAM_set_double_value(objects[i], UF_PARAM_STOCK_PART, yuliang);
					}
					//生成刀轨
					logical generated;
					UF_PARAM_generate(operTag, &generated);
					
					
				}
				UF_UI_ONT_refresh();
				
				
			}
			//uc1601("生成刀轨！", 1);

        }
    }
    catch(exception& ex)
    {
        BatchModifyParameter::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int BatchModifyParameter::ok_cb()
{
    int errorCode = 0;
    try
    {
		

		double jingheilv = doubleJingeilv->Value();
		double zhuanshu = doubleZhuanshu->Value();
		double yuliang = doubleYuliang->Value();
		

		tag_t setup_tag = NULL_TAG;
		UF_SETUP_ask_setup(&setup_tag);

		
		tag_t mctRootgroup = NULL_TAG;
		UF_SETUP_ask_mct_root(setup_tag, &mctRootgroup);
		tag_t toolTag = NULL_TAG;

		string strToolName = enum0->ValueAsString().GetLocaleText();
		const char* ToolName1 = nullptr;
		ToolName1 = strToolName.c_str();
		
		char* ToolName = nullptr;                       //初始化char*类型
		ToolName = const_cast<char*>(ToolName1);           //const char*类型转char*类型

	
		
		UF_NCGROUP_ask_object_of_name(mctRootgroup, ToolName, &toolTag);
		
		int count = 0;
		tag_t * objects;
		UF_UI_ONT_ask_selected_nodes(&count, &objects);
		for (int i = 0; i<count; i++)
		{
			tag_t operTag = objects[i];
			int type = 0, subtype = 0;
			UF_OBJ_ask_type_and_subtype(operTag, &type, &subtype);
			if (type == UF_machining_operation_type)
			{
				UF_NCGROUP_accept_member(toolTag, objects[i]);
				
				if (zhuanshu != 0)
				{
					UF_PARAM_set_double_value(objects[i], UF_PARAM_SPINDLE_RPM, zhuanshu);
				}

				if (jingheilv != 0)
				{
					//设置进给率
					UF_PARAM_feedrate_t feed_value;
					UF_PARAM_ask_subobj_ptr_value(objects[i], UF_PARAM_FEED_CUT, &feed_value);
					feed_value.value = jingheilv;
					UF_PARAM_set_subobj_ptr_value(objects[i], UF_PARAM_FEED_CUT, &feed_value);
				}

				if (yuliang != 0)
				{
					//设置部件余量
					UF_PARAM_set_double_value(objects[i], UF_PARAM_STOCK_PART, yuliang);
				}

				
			}
			
			UF_UI_ONT_refresh();
			//uc1601("完成参数批修改！", 1);
		}

    }
    catch(exception& ex)
    {
        errorCode = 1;
        BatchModifyParameter::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}


PropertyList* BatchModifyParameter::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}


void BatchModifyParameter::GetAllToolTag2(tag_t groupTag, vector<tag_t> &vToolTags)
{
	std::vector<tag_t>tool_tag;
	tag_t ObjectTag = NULL_TAG;
	int Type, SubType;
	UF_OBJ_cycle_objs_in_part(UF_PART_ask_display_part(), UF_machining_tool_type, &ObjectTag);
	while (ObjectTag != NULL_TAG)
	{
		UF_OBJ_ask_extended_type_and_subtype(ObjectTag, &Type, &SubType);
		if (Type == UF_machining_tool_type&&SubType == UF_mach_tool_subtype)
		{
			vToolTags.push_back(ObjectTag);
		}
		UF_OBJ_cycle_objs_in_part(UF_PART_ask_display_part(), UF_machining_tool_type, &ObjectTag);
	}

}
