//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\PRO_code\FBM_NX11_NUAA_Win32_D0325\Postprocess.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 05-08-2024  (Format: mm-dd-yyyy)
//              Time: 20:41
//
//==============================================================================

#ifndef POSTPROCESS_H_INCLUDED
#define POSTPROCESS_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Button.hxx>

#include "FeaturePublicClass.h"
#include "HuNXOpen.h"
#include "uf_all.h"
#include "uf_cutter.h" 
#include "uf_ui_ont.h"
#include "NXOpen_CAM_ALL_8.5.3.3.h"
#include "uf_cam_all.h"
#include <iostream>
#include <vector>
#include <cmath>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport Postprocess
{
    // class members
public:

	struct Vector3D //三维向量
	{
		double x, y, z;
	};

	struct Matrix3D //三维矩阵
	{
		double mat[3][3];
	};


	struct Vector3
	{
		double x, y, z;
	};

	// 定义矩阵结构体
	struct Matrix3x3
	{
		double data[3][3];
	};

	double determinant(Matrix3x3& mat);
	Matrix3x3 inverse(Matrix3x3& mat);
	Matrix3x3 transfer(Matrix3x3& mat);
	Matrix3x3 multiply(Matrix3x3& A, Matrix3x3& B);

	Vector3 crossProduct(const Vector3& v1, const Vector3& v2);// 向量叉乘

	// 向量点乘
	double dotProduct(const Vector3& v1, const Vector3& v2);

	// 标准化向量
	Vector3 normalize(const Vector3& v);

	// 计算旋转矩阵和平移向量
	void computeTransform(const Vector3& original_pos, const Vector3& original_x, const Vector3& original_y, const Vector3& original_z,
		const Vector3& transformed_pos, const Vector3& transformed_x, const Vector3& transformed_y, const Vector3& transformed_z,
		Matrix3x3& rotation_matrix, Vector3& translation_vector);

	// 提取绕 Z 轴的旋转角度
	double extractRotationAngleZ(const Matrix3x3& rotationMatrix);
	// 提取绕 Y 轴的旋转角度
	double extractRotationAngleY(const Matrix3x3& rotationMatrix);
	// 提取绕 X 轴的旋转角度
	double extractRotationAngleX(const Matrix3x3& rotationMatrix);


	double global_csys_origin[3];
	double global_matrix_values[9];

	double csys_origin[3];
	double matrix_values[9];
	int lable1 = 0;
	int lable2 = 0;


    static Session *theSession;
    static UI *theUI;
    Postprocess();
    ~Postprocess();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the Postprocess.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum01;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::Button* button01;// Block type: Button
    NXOpen::BlockStyler::Button* button02;// Block type: Button
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    
};
#endif //POSTPROCESS_H_INCLUDED
