//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\PRO_code\FBM_NX11_NUAA_Win32_D0325\Postprocess.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 05-08-2024  (Format: mm-dd-yyyy)
//              Time: 20:41 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "Postprocess.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(Postprocess::theSession) = NULL;
UI *(Postprocess::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
Postprocess::Postprocess()
{
    try
    {
        // Initialize the NX Open C++ API environment
        Postprocess::theSession = NXOpen::Session::GetSession();
        Postprocess::theUI = UI::GetUI();
        theDlxFileName = "Postprocess.dlx";
        theDialog = Postprocess::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &Postprocess::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &Postprocess::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &Postprocess::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &Postprocess::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &Postprocess::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
Postprocess::~Postprocess()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
	UF_initialize();
    Postprocess *thePostprocess = NULL;
    try
    {
        thePostprocess = new Postprocess();
        // The following method shows the dialog immediately
        thePostprocess->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        Postprocess::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(thePostprocess != NULL)
    {
        delete thePostprocess;
        thePostprocess = NULL;
    }
	UF_terminate();
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        Postprocess::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int Postprocess::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        Postprocess::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void Postprocess::initialize_cb()
{
    try
    {
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        button01 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        button02 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button02"));
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        Postprocess::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void Postprocess::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
		int ty_count = 0;
		const char **type_nemas = NULL;
		tag_t setup_tag = NULL_TAG;
		UF_SETUP_ask_setup(&setup_tag);
		tag_t programmer_root = NULL_TAG;
		UF_SETUP_ask_program_root(setup_tag, &programmer_root);

		vector<NXOpen::NXString> vAllNames;
		char msg[256];
		UF_CAM_opt_ask_post_names(&ty_count, &type_nemas);
		UF_UI_open_listing_window();
		for (int i = 0; i < ty_count; i++)
		{
			/*sprintf_s(msg, "类型：%s\n", type_nemas[i]);
			UF_UI_write_listing_window(msg);*/
			vAllNames.push_back(type_nemas[i]);
		}
		enum01->SetEnumMembers(vAllNames);

		uc1601("请先进入 工序导航器-几何 模块", 1);

		PropertyList* button0Props = button0->GetProperties();
		button0Props->SetLogical("Enable", false);
		delete button0Props;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        Postprocess::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int Postprocess::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        Postprocess::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int Postprocess::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
		

        if(block == enum01)
        {
        //---------Enter your code here-----------
        }
        else if(block == button01)
        {
        //---------Enter your code here-----------
			int count = 0;
			tag_t * objects = NULL;
			UF_UI_ONT_ask_selected_nodes(&count, &objects);
			if (count > 0)
			{
				lable1 = 1;
				tag_t value = NULL_TAG;
				UF_PARAM_ask_tag_value(objects[0], UF_PARAM_MCS, &value);

				tag_t matrix_id = NULL_TAG;

				UF_CSYS_ask_csys_info(value, &matrix_id, global_csys_origin);
				UF_CSYS_ask_matrix_values(matrix_id, global_matrix_values);

				char msg[256];
				sprintf(msg, "当前选中的全局MCS原点为：%f, %f, %f\n\n", global_csys_origin[0], global_csys_origin[1], global_csys_origin[2]);
				UF_UI_open_listing_window();
				UF_UI_write_listing_window(msg);

				sprintf(msg, "当前选中的全局MCS矩阵为：\n%f, %f, %f,\n%f, %f, %f, \n%f, %f, %f\n\n",
					global_matrix_values[0], global_matrix_values[1], global_matrix_values[2],
					global_matrix_values[3], global_matrix_values[4], global_matrix_values[5],
					global_matrix_values[6], global_matrix_values[7], global_matrix_values[8]);

				UF_UI_write_listing_window(msg);

				char name[256];
				UF_OBJ_ask_name(objects[0], name);
				string Operate_name;
				Operate_name = name;
				string str = "已保存全局坐标系:" + Operate_name + "\n在选择待加工操作时请勿选中全局坐标系！";
				char tip1[256];
				strcpy(tip1, str.c_str());
				uc1601(tip1, 1);

				PropertyList* button01Props = button01->GetProperties();
				button01Props->SetLogical("Enable", false);
				delete button01Props;
				

			}
			else
			{
				uc1601("请选择MCS全局坐标系！", 1);
			}
        }
        else if(block == button02)
        {
        //---------Enter your code here-----------
			//获取当前加工导航器中选中的对象数量和TAG
			string str = "已选中操作:\n";
			int count = 0;
			tag_t* objects = NULL_TAG;
			UF_UI_ONT_ask_selected_nodes(&count, &objects);

			if (count > 0)
			{
				lable2 = 1;
				for (int i = 0; i < count; i++)
				{
					//得到当前操作名称
					char name[256];
					UF_OBJ_ask_name(objects[i], name);
					string Operate_name;
					Operate_name = name;
					str = str + Operate_name + "\n";
				}

				UF_free(objects);

				char tip1[256];
				strcpy(tip1, str.c_str());
				uc1601(tip1, 1);

				if (lable1 == 1 && lable2 == 1)
				{
					PropertyList* button0Props = button0->GetProperties();
					button0Props->SetLogical("Enable", true);
					delete button0Props;
					lable2 = 0;
				}
			}
			else
				uc1601("请选择待输出操作！", 1);
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
        }
        else if(block == button0)
        {
        //---------Enter your code here-----------
			string str = "已选中操作:\n";

			//得到输出文件扩展名
			string strEnum0;
			BlockStyler::PropertyList * strEnum0Props = enum0->GetProperties();
			NXString nxStrEnum0 = strEnum0Props->GetEnumAsString("Value");
			delete strEnum0Props;
			char crstring02[133] = "";
			strcpy_s(crstring02, 133, nxStrEnum0.GetLocaleText());
			strEnum0 = crstring02;

			//获取加工设置
			tag_t setup_tag = NULL_TAG;
			UF_SETUP_ask_setup(&setup_tag);
			//tag_t programmer_root = NULL_TAG;
			//UF_SETUP_ask_program_root(setup_tag, &programmer_root);



			if (setup_tag == NULL_TAG)
			{
				uc1601("请先初始化加工环境", 1);
				return 0;
			}

			//获取当前加工导航器中选中的对象数量和TAG
			int count = 0;
			tag_t* objects = NULL_TAG;
			UF_UI_ONT_ask_selected_nodes(&count, &objects);

			for (int i = 0; i < count; i++)
			{
				//得到当前操作名称
				char name[256];
				UF_OBJ_ask_name(objects[i], name);
				string Operate_name;
				Operate_name = name;
				str = str + Operate_name + "\n";


				//得到当前局部坐标系
				tag_t value = NULL_TAG;
				UF_PARAM_ask_tag_value(objects[i], UF_PARAM_MCS, &value);

				tag_t matrix_id = NULL_TAG;

				UF_CSYS_ask_csys_info(value, &matrix_id, csys_origin);
				UF_CSYS_ask_matrix_values(matrix_id, matrix_values);

				//输出当前局部坐标系
				char msg[256];
				sprintf(msg, "当前选中的MCS原点为：%f, %f, %f\n\n", csys_origin[0], csys_origin[1], csys_origin[2]);
				UF_UI_open_listing_window();
				UF_UI_write_listing_window(msg);

				sprintf(msg, "当前选中的MCS矩阵为：\n%f, %f, %f,\n%f, %f, %f, \n%f, %f, %f\n\n",
					matrix_values[0], matrix_values[1], matrix_values[2],
					matrix_values[3], matrix_values[4], matrix_values[5],
					matrix_values[6], matrix_values[7], matrix_values[8]);

				UF_UI_write_listing_window(msg);

				//---------------------------------------------求解位移矩阵和旋转矩阵---------------------------------------------

				// 原始坐标系在全局坐标系中的位置与三个轴向向量
				Vector3 original_pos = { global_csys_origin[0], global_csys_origin[1], global_csys_origin[2] };
				//Vector3 original_x = { global_matrix_values[0], global_matrix_values[1], global_matrix_values[2] };
				//Vector3 original_y = { global_matrix_values[3], global_matrix_values[4], global_matrix_values[5] };
				//Vector3 original_z = { global_matrix_values[6], global_matrix_values[7], global_matrix_values[8] };


				// 变换后的坐标系在全局坐标系中的位置与三个轴向向量
				Vector3 transformed_pos = { csys_origin[0], csys_origin[1], csys_origin[2] };
				//Vector3 transformed_x = { matrix_values[0], matrix_values[1], matrix_values[2] };
				//Vector3 transformed_y = { matrix_values[3], matrix_values[4], matrix_values[5] };
				//Vector3 transformed_z = { matrix_values[6], matrix_values[7], matrix_values[8] };

				// 定义旋转矩阵和平移向量
				Matrix3x3 rotation_matrix;
				Vector3 translation_vector;
				Matrix3x3 XYZ_rot;
				Vector3 MSC_vector;


				// 计算新坐标系相对于机床坐标系位置
				translation_vector.x = transformed_pos.x - original_pos.x;
				translation_vector.y = transformed_pos.y - original_pos.y;
				translation_vector.z = transformed_pos.z - original_pos.z;




				//// 计算旋转矩阵和平移向量
				//computeTransform(original_pos, original_x, original_y, original_z,
				//	transformed_pos, transformed_x, transformed_y, transformed_z,
				//	rotation_matrix, translation_vector);

				Matrix3x3 A;
				Matrix3x3 B;
				Matrix3x3 O;

				A.data[0][0] = global_matrix_values[0];
				A.data[0][1] = global_matrix_values[1];
				A.data[0][2] = global_matrix_values[2];
				A.data[1][0] = global_matrix_values[3];
				A.data[1][1] = global_matrix_values[4];
				A.data[1][2] = global_matrix_values[5];
				A.data[2][0] = global_matrix_values[6];
				A.data[2][1] = global_matrix_values[7];
				A.data[2][2] = global_matrix_values[8];

				B.data[0][0] = matrix_values[0];
				B.data[0][1] = matrix_values[1];
				B.data[0][2] = matrix_values[2];
				B.data[1][0] = matrix_values[3];
				B.data[1][1] = matrix_values[4];
				B.data[1][2] = matrix_values[5];
				B.data[2][0] = matrix_values[6];
				B.data[2][1] = matrix_values[7];
				B.data[2][2] = matrix_values[8];

				O.data[0][0] = 1;
				O.data[0][1] = 0;
				O.data[0][2] = 0;
				O.data[1][0] = 0;
				O.data[1][1] = 1;
				O.data[1][2] = 0;
				O.data[2][0] = 0;
				O.data[2][1] = 0;
				O.data[2][2] = 1;

				Matrix3x3 AT;
				Matrix3x3 AT_inv;
				Matrix3x3 BT;
				Matrix3x3 OT;

				AT = transfer(A);
				BT = transfer(B);
				OT = transfer(O);

				AT_inv = inverse(AT);
				rotation_matrix = multiply(AT_inv, BT);

				XYZ_rot = multiply(OT, AT_inv);
				MSC_vector.x = XYZ_rot.data[0][0] * translation_vector.x + XYZ_rot.data[0][1] * translation_vector.y + XYZ_rot.data[0][2] * translation_vector.z;
				MSC_vector.y = XYZ_rot.data[1][0] * translation_vector.x + XYZ_rot.data[1][1] * translation_vector.y + XYZ_rot.data[1][2] * translation_vector.z;
				MSC_vector.z = XYZ_rot.data[2][0] * translation_vector.x + XYZ_rot.data[2][1] * translation_vector.y + XYZ_rot.data[2][2] * translation_vector.z;





				// 输出结果
				char T_matrix[256];
				char R_matrix[256];
				/*char inv_matrix[256];*/
				sprintf(T_matrix, "平移矩阵为：%f, %f, %f\n\n", MSC_vector.x, MSC_vector.y, MSC_vector.z);
				UF_UI_open_listing_window();
				UF_UI_write_listing_window(T_matrix);

				sprintf(R_matrix, "旋转矩阵为：\n%f, %f, %f,\n%f, %f, %f, \n%f, %f, %f\n\n",
					rotation_matrix.data[0][0], rotation_matrix.data[0][1], rotation_matrix.data[0][2],
					rotation_matrix.data[1][0], rotation_matrix.data[1][1], rotation_matrix.data[1][2],
					rotation_matrix.data[2][0], rotation_matrix.data[2][1], rotation_matrix.data[2][2]);

				/*sprintf(inv_matrix, "检查逆矩阵：\n%f, %f, %f,\n%f, %f, %f, \n%f, %f, %f\n\n",
				AT_inv.data[0][0], AT_inv.data[0][1], AT_inv.data[0][2],
				AT_inv.data[1][0], AT_inv.data[1][1], AT_inv.data[1][2],
				AT_inv.data[2][0], AT_inv.data[2][1], AT_inv.data[2][2]);*/

				UF_UI_write_listing_window(R_matrix);
				/*UF_UI_write_listing_window(inv_matrix);*/

				//求一个转置矩阵,得到的新矩阵为列向量坐标对应的旋转矩阵
				Matrix3x3 invrotation_matrix;
				/*invrotation_matrix = inverse(rotation_matrix);*/
				invrotation_matrix = rotation_matrix;

				//-------------------------------------------------------------计算旋转角度---------------------------------------------------------
				double theta1, theta2;
				double psi1, psi2;
				double fi1, fi2;
				if (invrotation_matrix.data[2][0] != 1 && invrotation_matrix.data[2][0] != -1)
				{
					// 求绕y轴旋转的角度（两个解）
					theta1 = std::asin(invrotation_matrix.data[2][0])*(-1);
					theta2 = PI - theta1;
					// 求绕x轴旋转的角度（两个解）
					psi1 = std::atan2(invrotation_matrix.data[2][1] / std::cos(theta1), invrotation_matrix.data[2][2] / std::cos(theta1));
					psi2 = std::atan2(invrotation_matrix.data[2][1] / std::cos(theta2), invrotation_matrix.data[2][2] / std::cos(theta2));
					// 求绕z轴旋转的角度（两个解）
					fi1 = std::atan2(invrotation_matrix.data[1][0] / std::cos(theta1), invrotation_matrix.data[0][0] / std::cos(theta1));
					fi2 = std::atan2(invrotation_matrix.data[1][0] / std::cos(theta2), invrotation_matrix.data[0][0] / std::cos(theta2));
				}

				else
				{
					fi1 = 0;
					fi2 = 0;

					if (invrotation_matrix.data[2][0] == -1)
					{
						theta1 = PI / 2;
						theta2 = PI / 2;

						psi1 = std::atan2(invrotation_matrix.data[0][1], invrotation_matrix.data[0][2]);
						psi2 = std::atan2(invrotation_matrix.data[0][1], invrotation_matrix.data[0][2]);
					}
					else
					{
						theta1 = PI / 2 * (-1);
						theta2 = PI / 2 * (-1);

						psi1 = std::atan2(invrotation_matrix.data[0][1] * (-1), invrotation_matrix.data[0][2] * (-1));
						psi2 = std::atan2(invrotation_matrix.data[0][1] * (-1), invrotation_matrix.data[0][2] * (-1));
					}
				}


				// 将弧度转换为角度
				double angle_x = psi2 * 180.0 / PI;
				double angle_y = theta2 * 180.0 / PI;
				double angle_z = fi2 * 180.0 / PI;

				// 输出结果
				char T_s[256];
				char R_s[256];
				sprintf(T_s, "沿x方向位移为：%f, 沿y方向位移为：%f, 沿z方向位移为：%f\n\n", MSC_vector.x, MSC_vector.y, MSC_vector.z);
				UF_UI_open_listing_window();
				UF_UI_write_listing_window(T_s);

				sprintf(R_s, "先绕 z 轴的旋转角度：%f, 再绕 y 轴的旋转角度：%f, 最后绕 x 轴的旋转角度：%f\n\n",
					angle_z, angle_y, angle_x);

				UF_UI_write_listing_window(R_s);


				//得到当前机床名称
				string machine;
				BlockStyler::PropertyList * string0Props = enum01->GetProperties();
				NXString filename_pui = string0Props->GetEnumAsString("Value");
				delete string0Props;
				char crstring0[133] = "";
				strcpy_s(crstring0, 133, filename_pui.GetLocaleText());
				machine = crstring0;
				const char* m = machine.data();

				string strEnum1;
				BlockStyler::PropertyList * Featureselect0Props = enum0->GetProperties();
				NXString nxStrEnum1 = Featureselect0Props->GetEnumAsString("Value");
				delete Featureselect0Props;
				char crstring1[133] = "";
				strcpy_s(crstring1, 133, nxStrEnum1.GetLocaleText());
				strEnum1 = crstring1;
				/*const char* extra = strEnum1.data();*/

				//生成后处理CN程序
				//NXString SelectionPathNXString; //路径名字

				NXOpen::Part* workPart;
				workPart = NXOpen::Session::GetSession()->Parts()->Work();

				NXString path = workPart->FullPath();

				const char* pathName = path.GetUTF8Text();
				std::string stringName = (char*)pathName;

				std::string::size_type position;
				position = stringName.rfind("\\");

				std::string subStr = stringName.substr(0, position);
				/*NXString NXsubStr = (NXString)subStr;
				SelectionPathNXString = NXsubStr;*/


				/*std::string filename = "Z:\\20240109part\\Operate_" + Operate_name + "." + strEnum1;*/
				std::string filename = subStr + "\\" + Operate_name + "." + strEnum1;
				const char* p = filename.data();

				UF_SETUP_generate_program(setup_tag, objects[i], m, p, UF_SETUP_OUTPUT_UNITS_METRIC);

				FILE *file = fopen(p, "r");
				if (file == NULL)
				{
					char f[256];
					sprintf(f, "文件未保存成功！");
					UF_UI_write_listing_window(f);
					return 1;
				}
				//读取文件内容
				char lines[1024][1024];
				int num_lines = 0;
				while (fgets(lines[num_lines], 1024, file))
				{
					num_lines++;
				}
				//关闭文件
				fclose(file);

				/*UF_UI_write_listing_window(lines);*/

				//在指定行位置写入内容
				std::string trans = "TRANS X" + std::to_string(MSC_vector.x) + "Y" + std::to_string(MSC_vector.y) + "Z" + std::to_string(MSC_vector.z) + "\n";
				std::string spin = "AROT Z" + std::to_string(angle_z) + "Y" + std::to_string(angle_y) + "X" + std::to_string(angle_x) + "\n";

				const char *ctrans = trans.c_str();
				const char *cspin = spin.c_str();
				const char *new_lines[] = {
					ctrans,
					cspin
				};

				int num_new_lines = sizeof(new_lines) / sizeof(new_lines[0]);

				if (num_lines + num_new_lines > 1024)
				{
					char f[256];
					sprintf(f, "添加内容过多！");
					UF_UI_write_listing_window(f);
					return 1;
				}

				//在第四行添加新内容
				for (int i = num_lines - 1; i >= 3; i--)
				{
					strcpy(lines[i + num_new_lines], lines[i]);
				}
				for (int i = 0; i < num_new_lines; i++)
				{
					strcpy(lines[3 + i], new_lines[i]);
				}
				num_lines += num_new_lines;

				//再次打开文件以写入新内容
				file = fopen(p, "w");
				if (file == NULL)
				{
					char f[256];
					sprintf(f, "文件未保存成功！");
					UF_UI_write_listing_window(f);
					return 1;
				}

				//将新内容写入文件
				for (int i = 0; i < num_lines; i++)
				{
					fputs(lines[i], file);
				}
				fclose(file);
			}
			UF_free(objects);

			PropertyList* button0Props = button0->GetProperties();
			button0Props->SetLogical("Enable", false);
			delete button0Props;

			
			/*char tip1[256];
			strcpy(tip1, str.c_str());
			uc1601(tip1, 1);*/
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        Postprocess::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int Postprocess::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        Postprocess::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* Postprocess::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

// 计算矩阵的行列式
double Postprocess::determinant(Matrix3x3& mat)
{
	return mat.data[0][0] * (mat.data[1][1] * mat.data[2][2] - mat.data[2][1] * mat.data[1][2]) -
		mat.data[0][1] * (mat.data[1][0] * mat.data[2][2] - mat.data[1][2] * mat.data[2][0]) +
		mat.data[0][2] * (mat.data[1][0] * mat.data[2][1] - mat.data[1][1] * mat.data[2][0]);
}

//计算矩阵的转置
Postprocess::Matrix3x3 Postprocess::transfer(Matrix3x3& mat)
{
	Matrix3x3 tranMat;
	tranMat.data[0][0] = mat.data[0][0];
	tranMat.data[0][1] = mat.data[1][0];
	tranMat.data[0][2] = mat.data[2][0];
	tranMat.data[1][0] = mat.data[0][1];
	tranMat.data[1][1] = mat.data[1][1];
	tranMat.data[1][2] = mat.data[2][1];
	tranMat.data[2][0] = mat.data[0][2];
	tranMat.data[2][1] = mat.data[1][2];
	tranMat.data[2][2] = mat.data[2][2];

	return tranMat;
}
// 计算矩阵的逆
Postprocess::Matrix3x3 Postprocess::inverse(Matrix3x3& mat)
{
	double det = determinant(mat);
	if (det == 0)
	{
		// 无逆矩阵
		std::cerr << "无法计算逆矩阵，行列式为0。" << std::endl;
		exit(1);
	}

	Matrix3x3 invMat;
	invMat.data[0][0] = (mat.data[1][1] * mat.data[2][2] - mat.data[2][1] * mat.data[1][2]) / det;
	invMat.data[1][0] = (-1)*(mat.data[1][0] * mat.data[2][2] - mat.data[1][2] * mat.data[2][0]) / det;
	invMat.data[2][0] = (mat.data[1][0] * mat.data[2][1] - mat.data[2][0] * mat.data[1][1]) / det;

	invMat.data[0][1] = (-1)*(mat.data[0][1] * mat.data[2][2] - mat.data[0][2] * mat.data[2][1]) / det;
	invMat.data[1][1] = (mat.data[0][0] * mat.data[2][2] - mat.data[0][2] * mat.data[2][0]) / det;
	invMat.data[2][1] = (-1)*(mat.data[0][0] * mat.data[2][1] - mat.data[0][1] * mat.data[2][0]) / det;

	invMat.data[0][2] = (mat.data[0][1] * mat.data[1][2] - mat.data[0][2] * mat.data[1][1]) / det;
	invMat.data[1][2] = (-1)*(mat.data[0][0] * mat.data[1][2] - mat.data[1][0] * mat.data[0][2]) / det;
	invMat.data[2][2] = (mat.data[0][0] * mat.data[1][1] - mat.data[1][0] * mat.data[0][1]) / det;

	return invMat;
}


// 向量叉乘
Postprocess::Vector3 Postprocess::crossProduct(const Vector3& v1, const Vector3& v2)
{
	Vector3 result;
	result.x = v1.y * v2.z - v1.z * v2.y;
	result.y = v1.z * v2.x - v1.x * v2.z;
	result.z = v1.x * v2.y - v1.y * v2.x;
	return result;
}

// 向量点乘
double Postprocess::dotProduct(const Vector3& v1, const Vector3& v2)
{
	return v1.x * v2.x + v1.y * v2.y + v1.z * v2.z;
}

// 标准化向量
Postprocess::Vector3  Postprocess::normalize(const Vector3& v)
{
	double length = std::sqrt(v.x * v.x + v.y * v.y + v.z * v.z);
	Vector3 result = { v.x / length, v.y / length, v.z / length };
	return result;
}

// 计算旋转矩阵和平移向量
void Postprocess::computeTransform(const Vector3& original_pos, const Vector3& original_x, const Vector3& original_y, const Vector3& original_z,
	const Vector3& transformed_pos, const Vector3& transformed_x, const Vector3& transformed_y, const Vector3& transformed_z,
	Matrix3x3& rotation_matrix, Vector3& translation_vector)
{
	// 计算平移向量
	translation_vector.x = transformed_pos.x - original_pos.x;
	translation_vector.y = transformed_pos.y - original_pos.y;
	translation_vector.z = transformed_pos.z - original_pos.z;

	// 计算旋转矩阵
	Vector3 x_axis = normalize(transformed_x);
	Vector3 y_axis = normalize(transformed_y);
	Vector3 z_axis = normalize(transformed_z);

	Vector3 new_x = normalize(crossProduct(y_axis, z_axis));
	Vector3 new_y = normalize(crossProduct(z_axis, x_axis));
	Vector3 new_z = normalize(crossProduct(x_axis, y_axis));

	rotation_matrix.data[0][0] = dotProduct(new_x, original_x);
	rotation_matrix.data[0][1] = dotProduct(new_x, original_y);
	rotation_matrix.data[0][2] = dotProduct(new_x, original_z);

	rotation_matrix.data[1][0] = dotProduct(new_y, original_x);
	rotation_matrix.data[1][1] = dotProduct(new_y, original_y);
	rotation_matrix.data[1][2] = dotProduct(new_y, original_z);

	rotation_matrix.data[2][0] = dotProduct(new_z, original_x);
	rotation_matrix.data[2][1] = dotProduct(new_z, original_y);
	rotation_matrix.data[2][2] = dotProduct(new_z, original_z);
}

// 提取绕 Z 轴的旋转角度
double Postprocess::extractRotationAngleZ(const Matrix3x3& rotationMatrix)
{
	return std::atan2(rotationMatrix.data[1][0], rotationMatrix.data[0][0]);
}

// 提取绕 Y 轴的旋转角度
double Postprocess::extractRotationAngleY(const Matrix3x3& rotationMatrix)
{
	double cos_angle_y = std::sqrt(rotationMatrix.data[2][2] * rotationMatrix.data[2][2] +
		rotationMatrix.data[2][1] * rotationMatrix.data[2][1]);
	return std::atan2(cos_angle_y, rotationMatrix.data[2][0]);
}

// 提取绕 X 轴的旋转角度
double Postprocess::extractRotationAngleX(const Matrix3x3& rotationMatrix)
{
	double cos_angle_x = std::sqrt(rotationMatrix.data[2][2] * rotationMatrix.data[2][2] +
		rotationMatrix.data[2][0] * rotationMatrix.data[2][0]);
	return std::atan2(cos_angle_x, rotationMatrix.data[2][1]);
}

Postprocess::Matrix3x3 Postprocess::multiply(Matrix3x3& A, Matrix3x3& B)
{
	Matrix3x3 result;
	result.data[0][0] = A.data[0][0] * B.data[0][0] + A.data[0][1] * B.data[1][0] + A.data[0][2] * B.data[2][0];
	result.data[0][1] = A.data[0][0] * B.data[0][1] + A.data[0][1] * B.data[1][1] + A.data[0][2] * B.data[2][1];
	result.data[0][2] = A.data[0][0] * B.data[0][2] + A.data[0][1] * B.data[1][2] + A.data[0][2] * B.data[2][2];

	result.data[1][0] = A.data[1][0] * B.data[0][0] + A.data[1][1] * B.data[1][0] + A.data[1][2] * B.data[2][0];
	result.data[1][1] = A.data[1][0] * B.data[0][1] + A.data[1][1] * B.data[1][1] + A.data[1][2] * B.data[2][1];
	result.data[1][2] = A.data[1][0] * B.data[0][2] + A.data[1][1] * B.data[1][2] + A.data[1][2] * B.data[2][2];

	result.data[2][0] = A.data[2][0] * B.data[0][0] + A.data[2][1] * B.data[1][0] + A.data[2][2] * B.data[2][0];
	result.data[2][1] = A.data[2][0] * B.data[0][1] + A.data[2][1] * B.data[1][1] + A.data[2][2] * B.data[2][1];
	result.data[2][2] = A.data[2][0] * B.data[0][2] + A.data[2][1] * B.data[1][2] + A.data[2][2] * B.data[2][2];

	return result;
}
