//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\PRO_code\FBM20230808\newDiag\CasingRoughPlunging.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 08-08-2023  (Format: mm-dd-yyyy)
//              Time: 17:00
//
//==============================================================================

#ifndef CASINGROUGHPLUNGING_H_INCLUDED
#define CASINGROUGHPLUNGING_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>

#include <NXOpen/Part.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/NXObjectManager.hxx>
#include <NXOpen/CAM_CAMObject.hxx>
#include <NXOpen/CartesianCoordinateSystem.hxx>
#include <NXOpen/CAM_NCGroup.hxx>
#include <NXOpen/CAM_MillToolBuilder.hxx>
#include <NXOpen/CAM_CAMSetup.hxx>
#include <NXOpen/CAM_NCGroupCollection.hxx>
#include <NXOpen/CAM_Tool.hxx>
#include <NXOpen/CAM_InheritableDoubleBuilder.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_Label.hxx>
#include <NXOpen/BlockStyler_FaceCollector.hxx>

#include <NXOpen/BlockStyler_TabControl.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_SpecifyPlane.hxx>
#include <uf_ui.h>
#include <uf.h>

#include <comdef.h>
#include <comutil.h>

#include <vector>
#include <string>

#include "FeaturePublicClass.h"
#include "ProcessPublicClass.h"
#include "RoughPlungingCmd.h"

#include <NXSigningResource.cpp>
//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                          EntityType_AllowFaces (1 << 4);
#define                         EntityType_AllowDatums (1 << 5);
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: BodyRules
//------------------------------------------------------------------------------
#define                           BodyRules_SingleBody (1 << 0);
#define                        BodyRules_FeatureBodies (1 << 1);
#define                        BodyRules_BodiesinGroup (1 << 2);
//------------------------------------------------------------------------------
//Bit Option for Property: FaceRules
//------------------------------------------------------------------------------
#define                           FaceRules_SingleFace (1 << 0);
#define                          FaceRules_RegionFaces (1 << 1);
#define                         FaceRules_TangentFaces (1 << 2);
#define                   FaceRules_TangentRegionFaces (1 << 3);
#define                            FaceRules_BodyFaces (1 << 4);
#define                         FaceRules_FeatureFaces (1 << 5);
#define                        FaceRules_AdjacentFaces (1 << 6);
#define                  FaceRules_ConnectedBlendFaces (1 << 7);
#define                        FaceRules_AllBlendFaces (1 << 8);
#define                             FaceRules_RibFaces (1 << 9);
#define                            FaceRules_SlotFaces (1 <<10);
#define                   FaceRules_BossandPocketFaces (1 <<11);
#define                       FaceRules_MergedRibFaces (1 <<12);
#define                  FaceRules_RegionBoundaryFaces (1 <<13);
#define                 FaceRules_FaceandAdjacentFaces (1 <<14);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport CasingRoughPlunging
{
    // class members
public:
	static Session *theSession;
	static UI *theUI;
	CasingRoughPlunging();
	~CasingRoughPlunging();
	int Show();

	bool ReadXMLOK;
	bool XiaxianFlag;
	bool PlungeSelectedFlag;


	bool selectpartFlag = false;
	bool zuobiaoxiFlag = false;
	bool areaFlag = false;

	NXOpen::Part * workPart;
	NXOpen::Body * selectedBody;
	NXOpen::Body * selectedBlank;
	tag_t partTag;
	tag_t blankTag;
	std::vector<Face*> AllFaces;
	std::vector<Rib*> ListOfRib;                            //读取的筋列表
	std::vector<Boss*> ListOfBoss;                          //读取的凸台列表
	std::vector<CircularGroove*> ListOfCavity;               //读取的环(弧)形槽列表
	std::vector<SubsidenceCavity*> ListOfSubsidenceCavity;  //读取的下陷槽列表
	std::vector<ArcCavity*> ListOfArcCavity;                //读取的弧形槽列表
	std::vector<NXOpen::Face*>TempSelectedFaceList;          //缓存面列表
	std::vector<NXOpen::Face*>SelectedFaceList;             //勾选面列表

	RoughPlungeProcessParameter ParameterSet;

	std::vector<CAM::CAMObject*> ProgramMembers;
	std::vector<NXString> ProgramStringList;
	std::vector<CAM::CAMObject*> ToolMembers;
	std::vector<NXString> ToolStringList;
	std::vector<CAM::CAMObject*> MCSMembers;
	std::vector<NXString> MCSStringList;
	std::vector<CAM::CAMObject*> MethodMembers;
	std::vector<NXString> MethodStringList;


	//----------------------- BlockStyler Callback Prototypes ---------------------
	// The following member function prototypes define the callbacks 
	// specified in your BlockStyler dialog.  The empty implementaiton
	// of these prototypes is provided in the CasingRoughPlunging.cpp file. 
	// You are REQUIRED to write the implementation for these funtions.
	//------------------------------------------------------------------------------
	void initialize_cb();
	void dialogShown_cb();
	int apply_cb();
	int ok_cb();
	int update_cb(NXOpen::BlockStyler::UIBlock* block);
	void focusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus);
	void keyboardFocusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus);

	BSTR ConvertToBSTR(NXString iString);
	NXString ConvertToString(BSTR bstr);
	void InitialParameter();
	void ReadXmlFile_AllFeatures();
	void SelectedFaceCampare(std::vector<NXOpen::Face*> SelectedFaceList, std::vector<NXOpen::Face*> FaceList);
	tag_t SelectPart();
	tag_t SelectBlank();
private:
	const char* theDlxFileName;
	NXOpen::BlockStyler::BlockDialog* theDialog;
	NXOpen::BlockStyler::Group* group01;// Block type: Group
	NXOpen::BlockStyler::BodyCollector* bodySelect01;// Block type: Body Collector
	NXOpen::BlockStyler::Enumeration* enumchengxu;// Block type: Enumeration
	NXOpen::BlockStyler::Enumeration* enumtool;// Block type: Enumeration
	NXOpen::BlockStyler::Enumeration* enumfangfa;// Block type: Enumeration
	NXOpen::BlockStyler::Group* group011;// Block type: Group
	NXOpen::BlockStyler::Toggle* togglejubu;// Block type: Toggle
	NXOpen::BlockStyler::BodyCollector* bodySelect011;// Block type: Body Collector
	NXOpen::BlockStyler::Toggle* togglenojubu;// Block type: Toggle
	NXOpen::BlockStyler::Enumeration* enumpart;// Block type: Enumeration
	NXOpen::BlockStyler::Group* group3;// Block type: Group
	NXOpen::BlockStyler::Label* label0;// Block type: Label
	NXOpen::BlockStyler::FaceCollector* face_select0;// Block type: Face Collector
	NXOpen::BlockStyler::Group* group1;// Block type: Group
	NXOpen::BlockStyler::TabControl* tabControl;// Block type: Tabs Page
	NXOpen::BlockStyler::Group* tabPage;// Block type: Group
	NXOpen::BlockStyler::Enumeration* enum07;// Block type: Enumeration
	NXOpen::BlockStyler::Enumeration* enum02;// Block type: Enumeration
	NXOpen::BlockStyler::Enumeration* enum09;// Block type: Enumeration
	NXOpen::BlockStyler::DoubleBlock* double012;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double013;// Block type: Double
	NXOpen::BlockStyler::Enumeration* enum04;// Block type: Enumeration
	NXOpen::BlockStyler::DoubleBlock* double015;// Block type: Double
	NXOpen::BlockStyler::Enumeration* enum013;// Block type: Enumeration
	NXOpen::BlockStyler::DoubleBlock* double016;// Block type: Double
	NXOpen::BlockStyler::Enumeration* enum014;// Block type: Enumeration
	NXOpen::BlockStyler::Group* tabPage1;// Block type: Group
	NXOpen::BlockStyler::DoubleBlock* double0;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double011;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double01;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double02;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double03;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double04;// Block type: Double
	NXOpen::BlockStyler::Group* tabPage2;// Block type: Group
	NXOpen::BlockStyler::DoubleBlock* double017;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double018;// Block type: Double
	NXOpen::BlockStyler::Group* group;// Block type: Group
	NXOpen::BlockStyler::Enumeration* enum05;// Block type: Enumeration
	NXOpen::BlockStyler::DoubleBlock* double06;// Block type: Double
	NXOpen::BlockStyler::Enumeration* enum011;// Block type: Enumeration
	NXOpen::BlockStyler::DoubleBlock* double05;// Block type: Double
	NXOpen::BlockStyler::Enumeration* enum06;// Block type: Enumeration
	NXOpen::BlockStyler::DoubleBlock* double07;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double08;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double09;// Block type: Double
	NXOpen::BlockStyler::DoubleBlock* double010;// Block type: Double
	NXOpen::BlockStyler::Enumeration* enum012;// Block type: Enumeration
	NXOpen::BlockStyler::Group* group2;// Block type: Group
	NXOpen::BlockStyler::Enumeration* enum03;// Block type: Enumeration
	NXOpen::BlockStyler::SpecifyPlane* plane0;// Block type: Specify Plane
	NXOpen::BlockStyler::DoubleBlock* double014;// Block type: Double
	NXOpen::BlockStyler::Button* button0;// Block type: Button
    
};
#endif //CASINGROUGHPLUNGING_H_INCLUDED
