//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\PRO_code\FBM20230808\newDiag\CasingRoughPlunging.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 08-08-2023  (Format: mm-dd-yyyy)
//              Time: 17:00 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "CasingRoughPlunging.hpp"
#include <uf_param.h>
#include <uf_camgeom.h>
#include <uf_cambnd.h>
#include <uf_ui.h>
#include <uf_cut_levels.h>
#include <uf_curve.h>
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(CasingRoughPlunging::theSession) = NULL;
UI *(CasingRoughPlunging::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
CasingRoughPlunging::CasingRoughPlunging()
{
    try
    {
        // Initialize the NX Open C++ API environment
        CasingRoughPlunging::theSession = NXOpen::Session::GetSession();
        CasingRoughPlunging::theUI = UI::GetUI();
        theDlxFileName = "CasingRoughPlunging.dlx";
        theDialog = CasingRoughPlunging::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &CasingRoughPlunging::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &CasingRoughPlunging::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &CasingRoughPlunging::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &CasingRoughPlunging::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &CasingRoughPlunging::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
CasingRoughPlunging::~CasingRoughPlunging()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    CasingRoughPlunging *theCasingRoughPlunging = NULL;
    try
    {
        theCasingRoughPlunging = new CasingRoughPlunging();
        // The following method shows the dialog immediately
        theCasingRoughPlunging->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theCasingRoughPlunging != NULL)
    {
        delete theCasingRoughPlunging;
        theCasingRoughPlunging = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int CasingRoughPlunging::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void CasingRoughPlunging::initialize_cb()
{
    try
    {
		group01 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group01"));
		bodySelect01 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect01"));
		enumchengxu = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enumchengxu"));
		enumtool = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enumtool"));
		enumfangfa = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enumfangfa"));
		group011 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group011"));
		togglejubu = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("togglejubu"));
		bodySelect011 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect011"));
		togglenojubu = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("togglenojubu"));
		enumpart = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enumpart"));
		group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
		label0 = dynamic_cast<NXOpen::BlockStyler::Label*>(theDialog->TopBlock()->FindBlock("label0"));
		face_select0 = dynamic_cast<NXOpen::BlockStyler::FaceCollector*>(theDialog->TopBlock()->FindBlock("face_select0"));
		group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
		tabControl = dynamic_cast<NXOpen::BlockStyler::TabControl*>(theDialog->TopBlock()->FindBlock("tabControl"));
		tabPage = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage"));
		enum07 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum07"));
		enum02 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum02"));
		enum09 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum09"));
		double012 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double012"));
		double013 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double013"));
		enum04 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum04"));
		double015 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double015"));
		enum013 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum013"));
		double016 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double016"));
		enum014 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum014"));
		tabPage1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage1"));
		double0 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double0"));
		double011 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double011"));
		double01 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double01"));
		double02 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double02"));
		double03 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double03"));
		double04 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double04"));
		tabPage2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage2"));
		double017 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double017"));
		double018 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double018"));
		group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
		enum05 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum05"));
		double06 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double06"));
		enum011 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum011"));
		double05 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double05"));
		enum06 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum06"));
		double07 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double07"));
		double08 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double08"));
		double09 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double09"));
		double010 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double010"));
		enum012 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum012"));
		group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
		enum03 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum03"));
		plane0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPlane*>(theDialog->TopBlock()->FindBlock("plane0"));
		double014 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double014"));
		button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));

		//InitialParameter();
		ReadXMLOK = false;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void CasingRoughPlunging::dialogShown_cb()
{
	InitialParameter();
    try
    {
        //---- Enter your callback code here -----
		//PropertyList* face_select0Props = face_select0->GetProperties();
		//face_select0Props->SetLogical("Enable", FALSE);
		//delete face_select0Props;

		//PropertyList* groupProps = group->GetProperties();
		//groupProps->SetLogical("Enable", TRUE);   //SetFile
		//delete groupProps;

		//PropertyList* face_select0Props = face_select0->GetProperties();
		//face_select0Props->SetLogical("Enable", FALSE);
		//delete face_select0Props;

		face_select0->SetFaceRules(1);//设置单个面模式

		PropertyList* toggle003Props = enumpart->GetProperties();
		toggle003Props->SetLogical("Enable", FALSE);
		delete toggle003Props;

		PropertyList* toggle01Props = togglejubu->GetProperties();
		toggle01Props->SetLogical("Enable", TRUE);
		toggle01Props->SetLogical("Value", FALSE);
		delete toggle01Props;

		PropertyList* toggle02Props = togglenojubu->GetProperties();
		toggle02Props->SetLogical("Enable", TRUE);
		toggle02Props->SetLogical("Value", FALSE);
		delete toggle02Props;

		PropertyList* toggle023Props = bodySelect011->GetProperties();
		toggle023Props->SetLogical("Enable", FALSE);
		
		delete toggle023Props;

		//face_select0->SetFaceRules(1);


    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int CasingRoughPlunging::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int CasingRoughPlunging::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
	try
	{


		if (block == bodySelect01)
		{
			//---------Enter your code here-----------
			PropertyList* bodySelect0Props = bodySelect01->GetProperties();
			std::vector<NXOpen::TaggedObject *> Bodies = bodySelect0Props->GetTaggedObjectVector("SelectedObjects");
			selectedBody = dynamic_cast<NXOpen::Body*>(Bodies[0]);
			delete bodySelect0Props;

			AllFaces = selectedBody->GetFaces();
			selectpartFlag = TRUE;
		}


		//---------------------------------------
		else if (block == enumchengxu)
		{
			//---------Enter your code here-----------
		}
		else if (block == enumtool)
		{
			//---------Enter your code here-----------
		}
		else if (block == enumfangfa)
		{
			//---------Enter your code here-----------
		}
		else if (block == togglejubu)
		{
			PropertyList* toggle05Props = togglejubu->GetProperties();
			bool jubu = toggle05Props->GetLogical("Value");
			delete toggle05Props;

			if (jubu)
			{
				PropertyList* toggle0411Props = bodySelect011->GetProperties();
				toggle0411Props->SetLogical("Enable", TRUE);
				delete toggle0411Props;
				
				PropertyList* toggle041Props = togglenojubu->GetProperties();
				toggle041Props->SetLogical("Enable", FALSE);
				delete toggle041Props;

				/*PropertyList* toggle01Props = enumpart->GetProperties();
				toggle01Props->SetLogical("Enable", FALSE);
				delete toggle01Props;*/

				zuobiaoxiFlag = TRUE;
		
			}
			else
			{
				PropertyList* toggle0411Props = bodySelect011->GetProperties();
				toggle0411Props->SetLogical("Enable", FALSE);
				delete toggle0411Props;

				PropertyList* toggle041Props = togglenojubu->GetProperties();
				toggle041Props->SetLogical("Enable", TRUE);
				delete toggle041Props;

				/*PropertyList* toggle01Props = enumpart->GetProperties();
				toggle01Props->SetLogical("Enable", TRUE);
				delete toggle01Props;*/
			}
			//---------Enter your code here-----------
		}
		else if (block == bodySelect011)
		{
			//---------Enter your code here-----------
			PropertyList* bodySelect01Props = bodySelect011->GetProperties();
			std::vector<NXOpen::TaggedObject *> Bodies = bodySelect01Props->GetTaggedObjectVector("SelectedObjects");
			selectedBlank = dynamic_cast<NXOpen::Body*>(Bodies[0]);
			delete bodySelect01Props;

			
		}
		else if (block == togglenojubu)
		{
			//---------Enter your code here-----------
			PropertyList* toggle05Props = togglenojubu->GetProperties();
			bool nojubu = toggle05Props->GetLogical("Value");
			delete toggle05Props;

			if (nojubu)
			{
				PropertyList* toggle003Props = enumpart->GetProperties();
				toggle003Props->SetLogical("Enable", TRUE);
				delete toggle003Props;

				PropertyList* toggle001Props = togglejubu->GetProperties();
				toggle001Props->SetLogical("Enable", FALSE);
				delete toggle001Props;

				zuobiaoxiFlag = TRUE;


			}
			else
			{
				PropertyList* toggle003Props = enumpart->GetProperties();
				toggle003Props->SetLogical("Enable", FALSE);
				delete toggle003Props;

				PropertyList* toggle001Props = togglejubu->GetProperties();
				toggle001Props->SetLogical("Enable", TRUE);
				delete toggle001Props;

			}
		}
		else if (block == enumpart)
		{
			//---------Enter your code here-----------
		}
		else if (block == label0)
		{
			//---------Enter your code here-----------
		}
			
		else if (block == face_select0)
		{
			//---------Enter your code here-----------
			TempSelectedFaceList.clear();
			SelectedFaceList.clear();
			BlockStyler::PropertyList * face_select0Props = face_select0->GetProperties();
			std::vector<NXOpen::TaggedObject*> pTaggedObject_FaceList = face_select0Props->GetTaggedObjectVector("SelectedObjects");
			delete face_select0Props;

			int pTaggedObject_FaceListSize = pTaggedObject_FaceList.size();
			Face* SelectedFace;
			for (int i = 0; i != pTaggedObject_FaceListSize; i++)//得到所选择的面
			{
				SelectedFace = dynamic_cast<NXOpen::Face*>(pTaggedObject_FaceList[i]);
				TempSelectedFaceList.push_back(SelectedFace);
			}

			areaFlag = TRUE;
			
		}

		else if (block == enum07)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum02)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum09)
		{
			//---------Enter your code here-----------
		}
		else if (block == double012)
		{
			//---------Enter your code here-----------
		}
		else if (block == double013)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum04)
		{
			//---------Enter your code here-----------
		}
		else if (block == double015)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum013)
		{
			//---------Enter your code here-----------
		}
		else if (block == double016)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum014)
		{
			//---------Enter your code here-----------
		}
		else if (block == double0)
		{
			//---------Enter your code here-----------
		}
		else if (block == double011)
		{
			//---------Enter your code here-----------
		}
		else if (block == double01)
		{
			//---------Enter your code here-----------
		}
		else if (block == double02)
		{
			//---------Enter your code here-----------
		}
		else if (block == double03)
		{
			//---------Enter your code here-----------
		}
		else if (block == double04)
		{
			//---------Enter your code here-----------
		}
		else if (block == double017)
		{
			//---------Enter your code here-----------
		}
		else if (block == double018)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum05)
		{
			//---------Enter your code here-----------
		}
		else if (block == double06)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum011)
		{
			//---------Enter your code here-----------
		}
		else if (block == double05)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum06)
		{
			//---------Enter your code here-----------
		}
		else if (block == double07)
		{
			//---------Enter your code here-----------
		}
		else if (block == double08)
		{
			//---------Enter your code here-----------
		}
		else if (block == double09)
		{
			//---------Enter your code here-----------
		}
		else if (block == double010)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum012)
		{
			//---------Enter your code here-----------
		}
		else if (block == enum03)
		{
			//---------Enter your code here-----------
		}
		else if (block == plane0)
		{
			//---------Enter your code here-----------
		}
		else if (block == double014)
		{
			//---------Enter your code here-----------
		}
		else if (block == button0)
		{
			//---------Enter your code here-----------

			//设置参数列表ParameterSet里的各种参数
			//程序、刀具、几何体、方法

			if (selectpartFlag == FALSE)
			{
				uc1601("请先完成零件实体模型设置,再开始加工刀轨", 1);
				//break;
			}
			else if (zuobiaoxiFlag == FALSE)
			{
				uc1601("请先完成坐标系与几何体设置,再开始加工刀轨", 1);
			}
			else if (areaFlag == FALSE)
			{
				uc1601("请先完成加工区域设置,再开始加工刀轨", 1);
			}
			else if(areaFlag == TRUE && zuobiaoxiFlag == TRUE)
			{
				PropertyList* enum010Props = enumchengxu->GetProperties();
				ParameterSet.PROGRAM = enum010Props->GetEnumAsString("Value");
				delete enum010Props;

				PropertyList* enum01Props = enumtool->GetProperties();
				NXString tempToolName = enum01Props->GetEnumAsString("Value");
				const char* tempToolNameChar = tempToolName.GetUTF8Text();
				ParameterSet.ToolMsg.ToolName = tempToolName;
				delete enum01Props;


				PropertyList* enum08Props = enumfangfa->GetProperties();
				ParameterSet.METHOD = enum08Props->GetEnumAsString("Value");
				delete enum08Props;

				PropertyList* enum0Props = enumpart->GetProperties();
				ParameterSet.GeomtryMCS = enum0Props->GetEnumAsString("Value");
				delete enum0Props;

				PropertyList* toggle0001Props = togglejubu->GetProperties();
				ParameterSet.IfLCsys = toggle0001Props->GetLogical("Value");
				delete toggle0001Props;

				for (std::vector<NXString>::size_type n = 0; n != ToolStringList.size(); n++)
				{
					NXString nToolName = ToolStringList[n];
					const char* nToolNameChar = nToolName.GetUTF8Text();
					if (lstrcmp(nToolNameChar, tempToolNameChar) == 0)
					{
						NXOpen::CAM::CAMObject* EachMember = ToolMembers[n + 1];
						CAM::MillToolBuilder* millToolBuilder1;
						millToolBuilder1 = workPart->CAMSetup()->CAMGroupCollection()->CreateMillToolBuilder(dynamic_cast<CAM::Tool*>(EachMember));

						ParameterSet.ToolMsg.ToolDiameter = millToolBuilder1->TlDiameterBuilder()->Value();
						ParameterSet.ToolMsg.ToolCorner = millToolBuilder1->TlTaperAngBuilder()->Value();
						ParameterSet.ToolMsg.ToolLength = millToolBuilder1->TlHeightBuilder()->Value();
						ParameterSet.ToolMsg.ToolFluteLength = millToolBuilder1->TlFluteLnBuilder()->Value();
					}
				}


				//加工区域的设置

				PropertyList* enum07Props = enum07->GetProperties();
				ParameterSet.CuttingDirection = enum07Props->GetEnum("Value");
				delete enum07Props;

				PropertyList* enum02Props = enum02->GetProperties();
				ParameterSet.CuttingMode = enum02Props->GetEnum("Value");
				delete enum02Props;

				PropertyList* enum09Props = enum09->GetProperties();
				ParameterSet.StepDisType = enum09Props->GetEnum("Value");
				delete enum09Props;

				PropertyList* double012Props = double012->GetProperties();
				ParameterSet.StepDisAmount = double012Props->GetDouble("Value");
				delete double012Props;

				PropertyList* double013Props = double013->GetProperties();
				ParameterSet.ForwardStepAmount = double013Props->GetDouble("Value");
				delete double013Props;

				PropertyList* enum04Props = enum04->GetProperties();
				ParameterSet.ForwardStepType = enum04Props->GetEnum("Value");
				delete enum04Props;

				PropertyList* double015Props = double015->GetProperties();
				ParameterSet.SingleStepAmount = double015Props->GetDouble("Value");
				delete double015Props;

				PropertyList* enum013Props = enum013->GetProperties();
				ParameterSet.SingleStepType = enum013Props->GetEnum("Value");
				delete enum013Props;

				PropertyList* double016Props = double016->GetProperties();
				ParameterSet.MaxCutDisAmount = double016Props->GetDouble("Value");
				delete double016Props;

				PropertyList* enum014Props = enum014->GetProperties();
				ParameterSet.MaxCutDisType = enum014Props->GetEnum("Value");
				delete enum014Props;

				//切削参数
				PropertyList* double017Props = double017->GetProperties();
				ParameterSet.RetracttingDis = double017Props->GetDouble("Value");
				delete double017Props;

				PropertyList* double018Props = double018->GetProperties();
				ParameterSet.RetracttingAngle = double018Props->GetDouble("Value");
				delete double018Props;

				PropertyList* double0Props = double0->GetProperties();
				ParameterSet.Tolerance = double0Props->GetDouble("Value");
				delete double0Props;

				PropertyList* double011Props = double011->GetProperties();
				ParameterSet.PartAllowance = double011Props->GetDouble("Value");
				delete double011Props;

				PropertyList* double01Props = double01->GetProperties();
				ParameterSet.SpindleSpeed = double01Props->GetDouble("Value");
				delete double01Props;

				PropertyList* double02Props = double02->GetProperties();
				ParameterSet.Machining = double02Props->GetDouble("Value");
				delete double02Props;

				PropertyList* double03Props = double03->GetProperties();
				ParameterSet.Approach = double03Props->GetDouble("Value");
				delete double03Props;

				PropertyList* double04Props = double04->GetProperties();
				ParameterSet.Retract = double04Props->GetDouble("Value");


				RoughPlungingCmd* RoughPlunging = new RoughPlungingCmd(ListOfCavity, ListOfSubsidenceCavity, ListOfArcCavity, ListOfBoss, ListOfRib, ParameterSet, workPart, selectedBody, selectedBlank, TempSelectedFaceList);
				uc1601("编程完成", 1);


			}

		}
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	return 0;
}


//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int CasingRoughPlunging::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

void CasingRoughPlunging::focusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus)
{
	try
	{
		//---- Enter your callback code here -----
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
}

void CasingRoughPlunging::keyboardFocusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus)
{
	try
	{
		//---- Enter your callback code here -----
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		CasingRoughPlunging::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
}
BSTR CasingRoughPlunging::ConvertToBSTR(NXString iString)
{
	char* istr = (char*)iString.GetUTF8Text();
	BSTR bstr = _com_util::ConvertStringToBSTR(istr);
	return bstr;
}

NXString CasingRoughPlunging::ConvertToString(BSTR bstr)
{
	char* istr = _com_util::ConvertBSTRToString(bstr);
	NXString str(istr);
	return str;
}

void CasingRoughPlunging::InitialParameter()
{
	NXOpen::Session *theSession = NXOpen::Session::GetSession();
	workPart = theSession->Parts()->Work();
	theSession->CreateCamSession();



	//-------------------设置所有的程序组  即 program
	CAM::NCGroup *nCGroup010(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NC_PROGRAM")));
	ProgramMembers = nCGroup010->GetMembers();
	int ProgramMemberSize = ProgramMembers.size();
	ProgramStringList.clear();
	for (int i = 1; i < ProgramMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = ProgramMembers[i];
		NXString EachMemberstr = EachMember->Name();               //也可以用GetObject来获取名字
		ProgramStringList.push_back(EachMemberstr);
	}
	PropertyList* enum010Props = enumchengxu->GetProperties();
	enum010Props->SetEnumMembers("Value", ProgramStringList);
	delete enum010Props;

	//--------------------设置所有的刀具
	CAM::NCGroup* nCGroup01(dynamic_cast<CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("GENERIC_MACHINE")));
	ToolMembers = nCGroup01->GetMembers();
	int ToolMemberSize = ToolMembers.size();
	ToolStringList.clear();
	for (int i = 1; i < ToolMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = ToolMembers[i];
		NXString EachMemberstr = EachMember->Name();
		ToolStringList.push_back(EachMemberstr);
	}
	PropertyList* enum01Props = enumtool->GetProperties();
	enum01Props->SetEnumMembers("Value", ToolStringList);
	delete enum01Props;

	//-------------------设置所有的MCS/几何体  
	CAM::NCGroup *nCGroup0(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("GEOMETRY")));
	MCSMembers = nCGroup0->GetMembers();
	int MCSMemberSize = MCSMembers.size();
	MCSStringList.clear();
	NXString MCS_name = "MCS_MILL";
	MCSStringList.push_back(MCS_name);
	/*for (int i = 1; i < MCSMemberSize; i++)
	{
	NXOpen::CAM::CAMObject* EachMember = MCSMembers[i];
	NXString EachMemberstr = EachMember->Name();
	NXString MCS_name = "MCS_MILL";

	MCSStringList.push_back(EachMemberstr);
	}*/
	
	PropertyList* enum0Props = enumpart->GetProperties();

	enum0Props->SetEnumMembers("Value", MCSStringList);
	delete enum0Props;

	//-------------------设置所有的方法  
	CAM::NCGroup *nCGroup08(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
	MethodMembers = nCGroup08->GetMembers();
	int MethodMemberSize = MethodMembers.size();
	MethodStringList.clear();
	for (int i = 1; i < MethodMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = MethodMembers[i];
		NXString EachMemberstr = EachMember->Name();
		MethodStringList.push_back(EachMemberstr);
	}
	PropertyList* enum08Props = enumfangfa->GetProperties();
	enum08Props->SetEnumMembers("Value", MethodStringList);
	delete enum08Props;


	//参数设置   
	//切削策略
	PropertyList* enum07Props = enum07->GetProperties();
	enum07Props->SetEnumAsString("Value", "順铣");
	delete enum07Props;

	PropertyList* enum02Props = enum02->GetProperties();
	enum02Props->SetEnumAsString("Value", "往复");    // 往复 、 跟随周边
	delete enum02Props;

	PropertyList* enum09Props = enum09->GetProperties();
	enum09Props->SetEnumAsString("Value", "刀具百分比（%）");
	delete enum09Props;

	PropertyList* double012Props = double012->GetProperties();  //步距
	//double012Props->initialize();
	double012Props->SetDouble("Value", 55);
	delete double012Props;

	PropertyList* double013Props = double013->GetProperties();    //向前步长
	double013Props->SetDouble("Value", 50);
	delete double013Props;

	PropertyList* enum04Props = enum04->GetProperties();
	enum04Props->SetEnumAsString("Value", "%刀具");
	//enum04Props->SetLogical("Enable", FALSE);
	delete enum04Props;

	PropertyList* double015Props = double015->GetProperties();   //单步向上
	double015Props->SetDouble("Value", 25);
	delete double015Props;

	PropertyList* enum13Props = enum013->GetProperties();
	enum13Props->SetEnumAsString("Value", "%刀具");
	delete enum13Props;

	PropertyList* double016Props = double016->GetProperties();  //最大切削宽度
	double016Props->SetDouble("Value", 50);
	delete double016Props;

	PropertyList* enum14Props = enum014->GetProperties();
	enum14Props->SetEnumAsString("Value", "%刀具");
	delete enum14Props;

	/*NXOpen::Vector3d _Normal(-1.000000, -0.000000, -0.000000);
	ParameterSet.Approch_Normal = _Normal;*/

	//切削参数
	PropertyList* double0Props = double0->GetProperties();       //公差
	double0Props->SetDouble("Value", 1.6);
	delete double0Props;

	PropertyList* double011Props = double011->GetProperties();   //部件余量
	double011Props->SetDouble("Value", 1.5);
	delete double011Props;

	PropertyList* double01Props = double01->GetProperties();     //主轴转速
	double01Props->SetDouble("Value", 5000);
	delete double01Props;

	PropertyList* double02Props = double02->GetProperties();     //进给速度
	double02Props->SetDouble("Value", 5000);
	delete double02Props;

	PropertyList* double03Props = double03->GetProperties();     //进刀速度
	double03Props->SetDouble("Value", 6000);
	delete double03Props;

	PropertyList* double04Props = double04->GetProperties();     //退刀速度
	double04Props->SetDouble("Value", 6000);
	delete double04Props;

	//非切削移动之 进退刀设置
	PropertyList* double017Props = double017->GetProperties();  //退刀距离
	double017Props->SetDouble("Value", 1);
	delete double017Props;

	PropertyList* double018Props = double018->GetProperties();  //退刀角
	double018Props->SetDouble("Value", 75);
	delete double018Props;

	PropertyList* enum05Props = enum05->GetProperties();
	enum05Props->SetEnumAsString("Value", "圆弧");
	delete enum05Props;


}


void CasingRoughPlunging::SelectedFaceCampare(std::vector<NXOpen::Face*> SelectedFaceList, std::vector<NXOpen::Face*> FaceList)
{
	bool SearchFaceFlag;
	std::vector<Face*>::iterator iter = SelectedFaceList.begin();
	while (iter != SelectedFaceList.end())
	{
		Face* SelectedFace = *iter;

		int FaceListSize = FaceList.size();
		for (int j = 0; j != FaceListSize; j++)
		{
			Face* EachFace = FaceList[j];
			tag_t SelectedFaceTag = SelectedFace->Tag();
			tag_t EachFaceTag = EachFace->Tag();

			if (SelectedFaceTag == EachFaceTag)
			{
				SearchFaceFlag = TRUE;
				break;
			}
			else
			{
				SearchFaceFlag = FALSE;
			}
		}
		if (SearchFaceFlag)
		{
			iter++;
		}
		else
		{
			char* str("请选择正确的面");
			uc1601(str, 1);
			break;
		}
	}
}
