//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  Z:\xinduihuakuang\BossSideMilling.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 05-09-2024  (Format: mm-dd-yyyy)
//              Time: 16:00 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "BossSideMilling.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(BossSideMilling::theSession) = NULL;
UI *(BossSideMilling::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
BossSideMilling::BossSideMilling()
{
    try
    {
        // Initialize the NX Open C++ API environment
        BossSideMilling::theSession = NXOpen::Session::GetSession();
        BossSideMilling::theUI = UI::GetUI();
        theDlxFileName = "BossSideMilling.dlx";
        theDialog = BossSideMilling::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &BossSideMilling::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &BossSideMilling::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &BossSideMilling::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &BossSideMilling::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &BossSideMilling::dialogShown_cb));

		BossType1 = false;
		BossType2 = false;
		ParameterSet.syspart = 0;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
BossSideMilling::~BossSideMilling()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    BossSideMilling *theBossSideMilling = NULL;
    try
    {
        theBossSideMilling = new BossSideMilling();
        // The following method shows the dialog immediately
        theBossSideMilling->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theBossSideMilling != NULL)
    {
        delete theBossSideMilling;
        theBossSideMilling = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int BossSideMilling::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void BossSideMilling::initialize_cb()
{
    try
    {
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        bodySelect0 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect0"));
        nativeFileBrowser0 = dynamic_cast<NXOpen::BlockStyler::FileSelection*>(theDialog->TopBlock()->FindBlock("nativeFileBrowser0"));
        enum010 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum010"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
        enum08 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum08"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        toggle04 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle04"));
        bodySelect01 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect01"));
        toggle05 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle05"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group4 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group4"));
        toggle02 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle02"));
        toggle021 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle021"));
        toggle0211 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0211"));
        face_select0 = dynamic_cast<NXOpen::BlockStyler::FaceCollector*>(theDialog->TopBlock()->FindBlock("face_select0"));
        label0 = dynamic_cast<NXOpen::BlockStyler::Label*>(theDialog->TopBlock()->FindBlock("label0"));
        face_select01 = dynamic_cast<NXOpen::BlockStyler::FaceCollector*>(theDialog->TopBlock()->FindBlock("face_select01"));
        toggle03 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle03"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        tabControl = dynamic_cast<NXOpen::BlockStyler::TabControl*>(theDialog->TopBlock()->FindBlock("tabControl"));
        tabPage = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage"));
        enum07 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum07"));
        double012 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double012"));
        enum04 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum04"));
        tabPage1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage1"));
        double0 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double0"));
        double011 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double011"));
        double01 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double01"));
        double02 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double02"));
        double03 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double03"));
        double04 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double04"));
        tabPage2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("tabPage2"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        enum05 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum05"));
        double06 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double06"));
        enum011 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum011"));
        double05 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double05"));
        enum06 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum06"));
        double07 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double07"));
        double08 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double08"));
        double09 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double09"));
        double010 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double010"));
        enum012 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum012"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        enum03 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum03"));
        plane0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPlane*>(theDialog->TopBlock()->FindBlock("plane0"));
        double014 = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("double014"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));

		InitialParameter();
		ReadXMLOK = false;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void BossSideMilling::dialogShown_cb()
{
	InitialParameter();
    try
    {
        //---- Enter your callback code here -----
		

		PropertyList* nativeFileBrowser0Props = nativeFileBrowser0->GetProperties();
		NXString FileString = "";
		nativeFileBrowser0Props->SetString("Path", FileString);   //SetFile
		delete nativeFileBrowser0Props;

		PropertyList* toggle04Props = toggle04->GetProperties();
		toggle04Props->SetLogical("Enable", TRUE);
		toggle04Props->SetLogical("Value", FALSE);
		delete toggle04Props;

		PropertyList* bodySelect01Props = bodySelect01->GetProperties();
		bodySelect01Props->SetLogical("Enable", FALSE);
		delete bodySelect01Props;

		PropertyList* toggle05Props = toggle05->GetProperties();
		toggle05Props->SetLogical("Enable", TRUE);
		toggle05Props->SetLogical("Value", FALSE);
		delete toggle05Props;

		PropertyList* enum0Props = enum0->GetProperties();
		enum0Props->SetLogical("Enable", TRUE);
		delete enum0Props;

		PropertyList* toggle02Props = toggle02->GetProperties();
		toggle02Props->SetLogical("Enable", TRUE);
		toggle02Props->SetLogical("Value", FALSE);
		delete toggle02Props;

		PropertyList* toggle021Props = toggle021->GetProperties();
		toggle021Props->SetLogical("Enable", TRUE);
		toggle021Props->SetLogical("Value", FALSE);
		delete toggle021Props;

		PropertyList* toggle0211Props = toggle0211->GetProperties();
		toggle0211Props->SetLogical("Enable", TRUE);
		toggle0211Props->SetLogical("Value", FALSE);
		delete toggle0211Props;

		/*PropertyList* toggle0Props = toggle0->GetProperties();
		toggle0Props->SetLogical("Enable", TRUE);
		toggle0Props->SetLogical("Value", FALSE);
		delete toggle0Props;*/

		PropertyList* face_select0Props = face_select0->GetProperties();
		face_select0Props->SetLogical("Enable", FALSE);
		delete face_select0Props;

		face_select0->SetFaceRules(1);//设置单个面模式
		face_select01->SetFaceRules(1);//设置单个面模式

		PropertyList* face_select01Props = face_select01->GetProperties();
		face_select01Props->SetLogical("Enable", TRUE);
		delete face_select01Props;

		PropertyList* toggle03Props = toggle03->GetProperties();
		toggle03Props->SetLogical("Enable", TRUE);
		toggle03Props->SetLogical("Value", FALSE);
		delete toggle03Props;

		uc1601("选择刀具时,请选择半径大小与凸台底部R角相同的刀具,且在生成操作之后,不可更改刀具", 1);
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int BossSideMilling::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int BossSideMilling::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == bodySelect0)
        {
        //---------Enter your code here-----------
			PropertyList* bodySelect0Props = bodySelect0->GetProperties();
			std::vector<NXOpen::TaggedObject *> Bodies = bodySelect0Props->GetTaggedObjectVector("SelectedObjects");
			selectedBody = dynamic_cast<NXOpen::Body*>(Bodies[0]);
			delete bodySelect0Props;
			AllFaces = selectedBody->GetFaces();

			workPart = NXOpen::Session::GetSession()->Parts()->Work();
			NXString path = workPart->FullPath();

			const char* pathName = path.GetUTF8Text();
			std::string stringName = (char*)pathName;

			std::string::size_type position;
			position = stringName.rfind("\\");

			std::string subStr = stringName.substr(0, position);
			NXString NXsubStr = (NXString)subStr;
			NXString SelectionPathNXString;
			SelectionPathNXString = NXsubStr;

			NXString namefile = SelectionPathNXString + "\\" + "boss.xml";

			if (Bodies.size() != 0)
			{
				PropertyList* nativeFileBrowser0Props = nativeFileBrowser0->GetProperties();
				nativeFileBrowser0Props->SetString("Path", namefile);
				delete nativeFileBrowser0Props;

				ReadXmlFile_Boss();
				ReadXMLOK = true;
				if (ListOfNBoss.size() == 0 && ListOfDLBoss.size() == 0 && ListOfNSBoss.size() == 0)
				{
					ReadXMLOK = false;
				}
			}
        }
        else if(block == nativeFileBrowser0)
        {
        //---------Enter your code here-----------
			ReadXmlFile_Boss();
			ReadXMLOK = true;
			if (ListOfNBoss.size() == 0 && ListOfDLBoss.size() == 0 && ListOfNSBoss.size() == 0)
			{
				ReadXMLOK = false;
			}
        }
        else if(block == enum010)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum01)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum08)
        {
        //---------Enter your code here-----------
        }
        else if(block == toggle04)
        {
        //---------Enter your code here-----------
			PropertyList* toggle04Props = toggle04->GetProperties();
			bool chuangjianjubu = toggle04Props->GetLogical("Value");
			delete toggle04Props;

			if (chuangjianjubu)
			{
				ParameterSet.syspart = 1;

				PropertyList* bodySelect01Props = bodySelect01->GetProperties();
				bodySelect01Props->SetLogical("Enable", TRUE);
				delete bodySelect01Props;

				PropertyList* toggle05Props = toggle05->GetProperties();
				toggle05Props->SetLogical("Enable", FALSE);
				delete toggle05Props;

				PropertyList* enum0Props = enum0->GetProperties();
				enum0Props->SetLogical("Enable", FALSE);
				delete enum0Props;
			}
			else
			{
				ParameterSet.syspart = 0;

				PropertyList* bodySelect01Props = bodySelect01->GetProperties();
				bodySelect01Props->SetLogical("Enable", FALSE);
				delete bodySelect01Props;

				PropertyList* toggle05Props = toggle05->GetProperties();
				toggle05Props->SetLogical("Enable", TRUE);
				delete toggle05Props;

				PropertyList* enum0Props = enum0->GetProperties();
				enum0Props->SetLogical("Enable", FALSE);
				delete enum0Props;
			}
        }
        else if(block == bodySelect01)
        {
        //---------Enter your code here-----------
			PropertyList* bodySelect01Props = bodySelect01->GetProperties();
			std::vector<NXOpen::TaggedObject *> Bodies = bodySelect01Props->GetTaggedObjectVector("SelectedObjects");
			selectedBlank = dynamic_cast<NXOpen::Body*>(Bodies[0]);
			delete bodySelect01Props;
        }
        else if(block == toggle05)
        {
        //---------Enter your code here-----------
			PropertyList* toggle05Props = toggle05->GetProperties();
			bool buchuangjianjubu = toggle05Props->GetLogical("Value");
			delete toggle05Props;

			if (buchuangjianjubu)
			{
				ParameterSet.syspart = 1;

				PropertyList* toggle04Props = toggle04->GetProperties();
				toggle04Props->SetLogical("Enable", FALSE);
				delete toggle04Props;

				PropertyList* bodySelect01Props = bodySelect01->GetProperties();
				bodySelect01Props->SetLogical("Enable", FALSE);
				delete bodySelect01Props;

				PropertyList* enum0Props = enum0->GetProperties();
				enum0Props->SetLogical("Enable", TRUE);
				delete enum0Props;
			}
			else
			{
				ParameterSet.syspart = 0;

				PropertyList* toggle04Props = toggle04->GetProperties();
				toggle04Props->SetLogical("Enable", TRUE);
				delete toggle04Props;

				PropertyList* bodySelect01Props = bodySelect01->GetProperties();
				bodySelect01Props->SetLogical("Enable", FALSE);
				delete bodySelect01Props;

				PropertyList* enum0Props = enum0->GetProperties();
				enum0Props->SetLogical("Enable", FALSE);
				delete enum0Props;
			}
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
        }
        else if(block == toggle02)
        {
        //---------Enter your code here-----------
			PropertyList* toggle02Props = toggle02->GetProperties();
			bool OneBoss = toggle02Props->GetLogical("Value");
			delete toggle02Props;

			if (OneBoss)
			{

				PropertyList* toggle0211Props = toggle0211->GetProperties();
				toggle0211Props->SetLogical("Enable", FALSE);
				delete toggle0211Props;
				BossType1 = true;
			}
			else
			{

				PropertyList* toggle0211Props = toggle0211->GetProperties();
				toggle0211Props->SetLogical("Enable", TRUE);
				delete toggle0211Props;
				BossType1 = false;
			}
        }
        else if(block == toggle021)
        {
        //---------Enter your code here-----------
			PropertyList* toggle021Props = toggle021->GetProperties();
			bool MoreBoss = toggle021Props->GetLogical("Value");
			delete toggle021Props;

			if (MoreBoss)
			{

				PropertyList* toggle0211Props = toggle0211->GetProperties();
				toggle0211Props->SetLogical("Enable", FALSE);
				delete toggle0211Props;
				BossType2 = true;
			}
			else
			{

				PropertyList* toggle0211Props = toggle0211->GetProperties();
				toggle0211Props->SetLogical("Enable", TRUE);
				delete toggle0211Props;
				BossType2 = false;
			}
        }
        else if(block == toggle0211)
        {
        //---------Enter your code here-----------
			PropertyList* toggle0211Props = toggle0211->GetProperties();
			bool FaceSelectFlag = toggle0211Props->GetLogical("Value");
			delete toggle0211Props;

			if (FaceSelectFlag)
			{
				PropertyList* toggle02Props = toggle02->GetProperties();
				toggle02Props->SetLogical("Enable", FALSE);
				delete toggle02Props;

				PropertyList* toggle021Props = toggle021->GetProperties();
				toggle021Props->SetLogical("Enable", FALSE);
				delete toggle021Props;

				PropertyList* face_select0Props = face_select0->GetProperties();
				face_select0Props->SetLogical("Enable", TRUE);
				delete face_select0Props;
			}

			else
			{
				PropertyList* toggle02Props = toggle02->GetProperties();
				toggle02Props->SetLogical("Enable", TRUE);
				delete toggle02Props;

				PropertyList* toggle021Props = toggle021->GetProperties();
				toggle021Props->SetLogical("Enable", TRUE);
				delete toggle021Props;

				PropertyList* face_select0Props = face_select0->GetProperties();
				face_select0Props->SetLogical("Enable", FALSE);
				delete face_select0Props;
			}
        }
        else if(block == face_select0)
        {
        //---------Enter your code here-----------
			SelectedBossTopFaceList.clear();
			BlockStyler::PropertyList * face_select0Props = face_select0->GetProperties();
			std::vector<NXOpen::TaggedObject*> pTaggedObject_FaceList = face_select0Props->GetTaggedObjectVector("SelectedObjects");
			delete face_select0Props;

			int pTaggedObject_FaceListSize = pTaggedObject_FaceList.size();
			Face* SelectedBossTopFace;
			for (int i = 0; i != pTaggedObject_FaceListSize; i++)
			{
				SelectedBossTopFace = dynamic_cast<NXOpen::Face*>(pTaggedObject_FaceList[i]);
				SelectedBossTopFaceList.push_back(SelectedBossTopFace);
			}

			for (std::vector<NormalBoss*>::size_type i = 0; i != ListOfNBoss.size(); i++)
			{
				NormalBoss* EachBoss = ListOfNBoss[i];
				Face* BossTopFace = EachBoss->TopFaceVector[0];
				BossTopFaceList.push_back(BossTopFace);
			}
			for (std::vector<NoSideBoss*>::size_type i = 0; i != ListOfNSBoss.size(); i++)
			{
				NoSideBoss* EachBoss = ListOfNSBoss[i];
				Face* BossTopFace = EachBoss->TopFaceVector[0];
				BossTopFaceList.push_back(BossTopFace);
			}
			for (std::vector<DoubleLayerBoss*>::size_type i = 0; i != ListOfDLBoss.size(); i++)
			{
				DoubleLayerBoss* EachBoss = ListOfDLBoss[i];
				Face* BossTopFace = EachBoss->TopFaceVector[0];
				BossTopFaceList.push_back(BossTopFace);

				Face* nBossTopFace = EachBoss->NTopFaceVector[0];
				BossTopFaceList.push_back(nBossTopFace);
			}

			SelectedFaceCampare(SelectedBossTopFaceList, BossTopFaceList);
        }
        else if(block == label0)
        {
        //---------Enter your code here-----------
        }
        else if(block == face_select01)
        {
        //---------Enter your code here-----------
			SelectedZhiDingFaceList.clear();
			BlockStyler::PropertyList * face_select01Props = face_select01->GetProperties();
			std::vector<NXOpen::TaggedObject*> pTaggedObject_ZhiDingFaceList = face_select01Props->GetTaggedObjectVector("SelectedObjects");
			delete face_select01Props;

			int pTaggedObject_ZhiDingFaceListSize = pTaggedObject_ZhiDingFaceList.size();
			Face* SelectedZDBossTopFace;
			for (int i = 0; i != pTaggedObject_ZhiDingFaceListSize; i++)
			{
				SelectedZDBossTopFace = dynamic_cast<NXOpen::Face*>(pTaggedObject_ZhiDingFaceList[i]);
				SelectedZhiDingFaceList.push_back(SelectedZDBossTopFace);
			}
        }
        else if(block == toggle03)
        {
        //---------Enter your code here-----------
			PropertyList* toggle03Props = toggle03->GetProperties();
			bool jingjiagong = toggle03Props->GetLogical("Value");
			delete toggle03Props;

			if (jingjiagong)
			{
				uc1601("请选择合适刃长的刀具，保证精加工的一刀切", 1);
			}
        }
        else if(block == enum07)
        {
        //---------Enter your code here-----------
        }
        else if(block == double012)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum04)
        {
        //---------Enter your code here-----------
        }
        else if(block == double0)
        {
        //---------Enter your code here-----------
        }
        else if(block == double011)
        {
        //---------Enter your code here-----------
        }
        else if(block == double01)
        {
        //---------Enter your code here-----------
        }
        else if(block == double02)
        {
        //---------Enter your code here-----------
        }
        else if(block == double03)
        {
        //---------Enter your code here-----------
        }
        else if(block == double04)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum05)
        {
        //---------Enter your code here-----------
			PropertyList* enum05Props = enum05->GetProperties();
			int ToolApproachType = enum05Props->GetEnum("Value");
			delete enum05Props;

			if (ToolApproachType == 0)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();
				double07Props->SetLogical("Enable", TRUE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				double08Props->SetLogical("Enable", FALSE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 1)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();
				double07Props->SetLogical("Enable", FALSE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				double08Props->SetLogical("Enable", TRUE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 2)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetLogical("Enable", FALSE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				double06Props->SetLogical("Enable", FALSE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", TRUE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				double05Props->SetLogical("Enable", TRUE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();
				double07Props->SetLogical("Enable", FALSE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				double08Props->SetLogical("Enable", FALSE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				double09Props->SetLogical("Enable", TRUE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();
				double010Props->SetLogical("Enable", TRUE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", TRUE);
				delete enum012Props;
			}
			else if (ToolApproachType == 3)
			{
				PropertyList* enum011Props = enum011->GetProperties();
				enum011Props->SetEnumAsString("Value", "%刀具");
				enum011Props->SetLogical("Enable", TRUE);
				delete enum011Props;

				PropertyList* double06Props = double06->GetProperties();
				double06Props->SetDouble("Value", 100);
				double06Props->SetLogical("Enable", TRUE);
				delete double06Props;

				PropertyList* enum06Props = enum06->GetProperties();
				enum06Props->SetLogical("Enable", FALSE);
				delete enum06Props;

				PropertyList* double05Props = double05->GetProperties();
				double05Props->SetLogical("Enable", FALSE);
				delete double05Props;

				PropertyList* double07Props = double07->GetProperties();
				double07Props->SetDouble("Value", 0);
				double07Props->SetLogical("Enable", TRUE);
				delete double07Props;

				PropertyList* double08Props = double08->GetProperties();
				double08Props->SetDouble("Value", 0);
				double08Props->SetLogical("Enable", TRUE);
				delete double08Props;

				PropertyList* double09Props = double09->GetProperties();
				double09Props->SetLogical("Enable", FALSE);
				delete double09Props;

				PropertyList* double010Props = double010->GetProperties();
				double010Props->SetLogical("Enable", FALSE);
				delete double010Props;

				PropertyList* enum012Props = enum012->GetProperties();
				enum012Props->SetLogical("Enable", FALSE);
				delete enum012Props;
			}
        }
        else if(block == double06)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum011)
        {
        //---------Enter your code here-----------
        }
        else if(block == double05)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum06)
        {
        //---------Enter your code here-----------
        }
        else if(block == double07)
        {
        //---------Enter your code here-----------
        }
        else if(block == double08)
        {
        //---------Enter your code here-----------
        }
        else if(block == double09)
        {
        //---------Enter your code here-----------
        }
        else if(block == double010)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum012)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum03)
        {
        //---------Enter your code here-----------
        }
        else if(block == plane0)
        {
        //---------Enter your code here-----------
        }
        else if(block == double014)
        {
        //---------Enter your code here-----------
        }
        else if(block == button0)
        {
        //---------Enter your code here-----------
			if (!ReadXMLOK)
			{
				uc1601("请选择 正确的特征识别XML文件！", 1);
				return -1;
			}

			PropertyList* enum010Props = enum010->GetProperties();
			ParameterSet.PROGRAM = enum010Props->GetEnumAsString("Value");
			delete enum010Props;

			PropertyList* enum0Props = enum0->GetProperties();
			ParameterSet.GeomtryMCS = enum0Props->GetEnumAsString("Value");
			delete enum0Props;

			PropertyList* enum08Props = enum08->GetProperties();
			ParameterSet.METHOD = enum08Props->GetEnumAsString("Value");
			delete enum08Props;

			PropertyList* enum01Props = enum01->GetProperties();
			NXString tempToolName = enum01Props->GetEnumAsString("Value");
			const char* tempToolNameChar = tempToolName.GetUTF8Text();
			ParameterSet.ToolMsg.ToolName = tempToolName;
			delete enum01Props;
			
			for (std::vector<NXString>::size_type n = 0; n != ToolStringList.size(); n++)
			{
				NXString nToolName = ToolStringList[n];
				const char* nToolNameChar = nToolName.GetUTF8Text();
				if (lstrcmp(nToolNameChar, tempToolNameChar) == 0)
				{
					NXOpen::CAM::CAMObject* EachMember = ToolMembers[n + 1];
					CAM::MillToolBuilder* millToolBuilder1;
					millToolBuilder1 = workPart->CAMSetup()->CAMGroupCollection()->CreateMillToolBuilder(dynamic_cast<CAM::Tool*>(EachMember));

					ParameterSet.ToolMsg.ToolDiameter = millToolBuilder1->TlDiameterBuilder()->Value();
					ParameterSet.ToolMsg.ToolCorner = millToolBuilder1->TlCor1RadBuilder()->Value();
					ParameterSet.ToolMsg.ToolLength = millToolBuilder1->TlHeightBuilder()->Value();
					ParameterSet.ToolMsg.ToolFluteLength = millToolBuilder1->TlFluteLnBuilder()->Value();
				}
			}

			PropertyList* double0Props = double0->GetProperties();
			ParameterSet.Tolerance = double0Props->GetDouble("Value");
			delete double0Props;

			PropertyList* double011Props = double011->GetProperties();
			ParameterSet.PartAllowance = double011Props->GetDouble("Value");
			delete double011Props;

			PropertyList* double01Props = double01->GetProperties();
			ParameterSet.SpindleSpeed = double01Props->GetDouble("Value");
			delete double01Props;

			PropertyList* double02Props = double02->GetProperties();
			ParameterSet.Machining = double02Props->GetDouble("Value");
			delete double02Props;

			PropertyList* double03Props = double03->GetProperties();
			ParameterSet.Approach = double03Props->GetDouble("Value");
			delete double03Props;

			PropertyList* double04Props = double04->GetProperties();
			ParameterSet.Retract = double04Props->GetDouble("Value");
			delete double04Props;

			PropertyList* toggle04Props = toggle04->GetProperties();
			ParameterSet.LCsys = toggle04Props->GetLogical("Value");
			delete toggle04Props;

			PropertyList* toggle05Props = toggle05->GetProperties();
			ParameterSet.NotLCsys = toggle05Props->GetLogical("Value");
			delete toggle05Props;

			PropertyList* toggle02Props = toggle02->GetProperties();
			ParameterSet.ONEboss = toggle02Props->GetLogical("Value");
			delete toggle02Props;

			PropertyList* toggle021Props = toggle021->GetProperties();
			ParameterSet.MOREboss = toggle021Props->GetLogical("Value");
			delete toggle021Props;

			PropertyList* toggle0211Props = toggle0211->GetProperties();
			ParameterSet.FaceSelect = toggle0211Props->GetLogical("Value");
			delete toggle0211Props;

			/*PropertyList* toggle0Props = toggle0->GetProperties();
			ParameterSet.PointPart = toggle0Props->GetLogical("Value");
			delete toggle0Props;*/

			PropertyList* toggle03Props = toggle03->GetProperties();
			ParameterSet.Finishing = toggle03Props->GetLogical("Value");
			delete toggle03Props;

			PropertyList* enum07Props = enum07->GetProperties();
			ParameterSet.CuttingDirection = enum07Props->GetEnum("Value");
			delete enum07Props;

			PropertyList* double012Props = double012->GetProperties();
			ParameterSet.CuttingStepdistance = double012Props->GetDouble("Value");
			delete double012Props;

			PropertyList* enum04Props = enum04->GetProperties();
			ParameterSet.CuttingStepdistanceunit = enum04Props->GetEnum("Value");
			delete enum04Props;

			PropertyList* enum05Props = enum05->GetProperties();
			ParameterSet.ToolMotion.ToolMotionType = enum05Props->GetEnum("Value");
			delete enum05Props;

			PropertyList* enum011Props = enum011->GetProperties();
			ParameterSet.ToolMotion.ToolMotionDistanceUnit = enum011Props->GetEnum("Value");
			delete enum011Props;

			PropertyList* double06Props = double06->GetProperties();
			ParameterSet.ToolMotion.ToolMotionDistance = double06Props->GetDouble("Value");
			delete double06Props;

			PropertyList* enum06Props = enum06->GetProperties();
			ParameterSet.ToolMotion.CircleRadiusUnit = enum06Props->GetEnum("Value");
			delete enum06Props;

			PropertyList* double05Props = double05->GetProperties();
			ParameterSet.ToolMotion.CircleRadius = double05Props->GetDouble("Value");
			delete double05Props;

			PropertyList* double07Props = double07->GetProperties();
			ParameterSet.ToolMotion.RotationAngle = double07Props->GetDouble("Value");
			delete double07Props;

			PropertyList* double08Props = double08->GetProperties();
			ParameterSet.ToolMotion.TiltAngle = double08Props->GetDouble("Value");
			delete double08Props;

			PropertyList* double09Props = double09->GetProperties();
			ParameterSet.ToolMotion.CircleAngle = double09Props->GetDouble("Value");
			delete double09Props;

			PropertyList* enum012Props = enum012->GetProperties();
			ParameterSet.ToolMotion.LinearExtensionUnit = enum012Props->GetEnum("Value");
			delete enum012Props;

			PropertyList* double010Props = double010->GetProperties();
			ParameterSet.ToolMotion.LinearExtension = double010Props->GetDouble("Value");
			delete double010Props;

			PropertyList* enum03Props = enum03->GetProperties();
			ParameterSet.SafeSetType = enum03Props->GetEnum("Value");
			delete enum03Props;

			PropertyList* double014Props = double014->GetProperties();
			ParameterSet.SafeSetOffset = double014Props->GetDouble("Value");
			delete double014Props;


			/*if (BossType1 || ParameterSet.FaceSelect)
			{
				
			}*/
			NBossSideMillingCmd* BossSideMilling0 = new NBossSideMillingCmd(ListOfNBoss, ListOfNSBoss, ParameterSet, workPart, selectedBody, selectedBlank, SelectedBossTopFaceList, SelectedZhiDingFaceList);
			/*if (BossType2 || ParameterSet.FaceSelect)
			{
				
			}*/
			DLBossSideMillingCmd* DLBossSideMilling2 = new DLBossSideMillingCmd(ListOfDLBoss, ParameterSet, workPart, selectedBody, selectedBlank, SelectedBossTopFaceList, SelectedZhiDingFaceList);
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int BossSideMilling::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* BossSideMilling::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
void BossSideMilling::focusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus)
{
	try
	{
		//---- Enter your callback code here -----
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
}
void BossSideMilling::keyboardFocusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus)
{
	try
	{
		//---- Enter your callback code here -----
	}
	catch (exception& ex)
	{
		//---- Enter your exception handling code here -----
		BossSideMilling::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
}
void BossSideMilling::InitialParameter()
{
	NXOpen::Session *theSession = NXOpen::Session::GetSession();
	workPart = theSession->Parts()->Work();
	theSession->CreateCamSession();

	CAM::NCGroup *nCGroup010(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("NC_PROGRAM")));
	ProgramMembers = nCGroup010->GetMembers();
	int ProgramMemberSize = ProgramMembers.size();
	ProgramStringList.clear();
	for (int i = 1; i < ProgramMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = ProgramMembers[i];
		NXString EachMemberstr = EachMember->Name();
		ProgramStringList.push_back(EachMemberstr);
	}
	PropertyList* enum010Props = enum010->GetProperties();
	enum010Props->SetEnumMembers("Value", ProgramStringList);
	delete enum010Props;

	CAM::NCGroup* nCGroup01(dynamic_cast<CAM::NCGroup*>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("GENERIC_MACHINE")));
	ToolMembers = nCGroup01->GetMembers();
	int ToolMemberSize = ToolMembers.size();
	ToolStringList.clear();
	for (int i = 1; i < ToolMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = ToolMembers[i];
		NXString EachMemberstr = EachMember->Name();
		ToolStringList.push_back(EachMemberstr);
	}


	PropertyList* enum01Props = enum01->GetProperties();
	enum01Props->SetEnumMembers("Value", ToolStringList);
	delete enum01Props;

	CAM::NCGroup *nCGroup0(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("GEOMETRY")));
	MCSMembers = nCGroup0->GetMembers();
	int MCSMemberSize = MCSMembers.size();
	MCSStringList.clear();
	NXString MCS_name = "MCS_MILL";
	MCSStringList.push_back(MCS_name);
	/*for (int i = 1; i < MCSMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = MCSMembers[i];
		NXString EachMemberstr = EachMember->Name();
		MCSStringList.push_back(EachMemberstr);
	}*/
	PropertyList* enum0Props = enum0->GetProperties();
	enum0Props->SetEnumMembers("Value", MCSStringList);
	delete enum0Props;

	CAM::NCGroup *nCGroup08(dynamic_cast<CAM::NCGroup *>(workPart->CAMSetup()->CAMGroupCollection()->FindObject("METHOD")));
	MethodMembers = nCGroup08->GetMembers();
	int MethodMemberSize = MethodMembers.size();
	MethodStringList.clear();
	for (int i = 1; i < MethodMemberSize; i++)
	{
		NXOpen::CAM::CAMObject* EachMember = MethodMembers[i];
		NXString EachMemberstr = EachMember->Name();
		MethodStringList.push_back(EachMemberstr);
	}
	PropertyList* enum08Props = enum08->GetProperties();
	enum08Props->SetEnumMembers("Value", MethodStringList);
	delete enum08Props;


	PropertyList* toggle04Props = toggle04->GetProperties();
	toggle04Props->SetLogical("Enable", TRUE);
	toggle04Props->SetLogical("Value", FALSE);
	delete toggle04Props;

	PropertyList* toggle05Props = toggle05->GetProperties();
	toggle05Props->SetLogical("Enable", TRUE);
	toggle05Props->SetLogical("Value", FALSE);
	delete toggle05Props;

	PropertyList* toggle02Props = toggle02->GetProperties();
	toggle02Props->SetLogical("Enable", TRUE);
	toggle02Props->SetLogical("Value", FALSE);
	delete toggle02Props;

	PropertyList* toggle021Props = toggle021->GetProperties();
	toggle021Props->SetLogical("Enable", TRUE);
	toggle021Props->SetLogical("Value", FALSE);
	delete toggle021Props;

	PropertyList* toggle0211Props = toggle0211->GetProperties();
	toggle0211Props->SetLogical("Enable", TRUE);
	toggle0211Props->SetLogical("Value", FALSE);
	delete toggle0211Props;

	/*PropertyList* toggle0Props = toggle0->GetProperties();
	toggle0Props->SetLogical("Enable", TRUE);
	toggle0Props->SetLogical("Value", FALSE);
	delete toggle0Props;*/

	PropertyList* toggle03Props = toggle03->GetProperties();
	toggle03Props->SetLogical("Enable", TRUE);
	toggle03Props->SetLogical("Value", FALSE);
	delete toggle03Props;

	PropertyList* enum07Props = enum07->GetProperties();
	enum07Props->SetEnumAsString("Value", "順铣");
	delete enum07Props;

	PropertyList* double012Props = double012->GetProperties();
	double012Props->SetDouble("Value", 30);
	delete double012Props;

	PropertyList* enum04Props = enum04->GetProperties();
	enum04Props->SetLogical("Enable", TRUE);
	enum04Props->SetEnumAsString("Value", "%刀具");
	delete enum04Props;

	PropertyList* double0Props = double0->GetProperties();
	double0Props->SetDouble("Value", 0.03);
	delete double0Props;

	PropertyList* double011Props = double011->GetProperties();
	double011Props->SetDouble("Value", 0);
	delete double011Props;

	PropertyList* double01Props = double01->GetProperties();
	double01Props->SetDouble("Value", 8000);
	delete double01Props;

	PropertyList* double02Props = double02->GetProperties();
	double02Props->SetDouble("Value", 1000);
	delete double02Props;

	PropertyList* double03Props = double03->GetProperties();
	double03Props->SetDouble("Value", 2000);
	delete double03Props;

	PropertyList* double04Props = double04->GetProperties();
	double04Props->SetDouble("Value", 6000);
	delete double04Props;

	PropertyList* enum05Props = enum05->GetProperties();
	enum05Props->SetEnumAsString("Value", "圆弧-垂直于刀轴");
	delete enum05Props;

	PropertyList* enum011Props = enum011->GetProperties();
	enum011Props->SetEnumAsString("Value", "%刀具");
	enum011Props->SetLogical("Enable", FALSE);
	delete enum011Props;

	PropertyList* double06Props = double06->GetProperties();
	double06Props->SetDouble("Value", 100);
	double06Props->SetLogical("Enable", FALSE);
	delete double06Props;

	PropertyList* enum06Props = enum06->GetProperties();
	enum06Props->SetEnumAsString("Value", "%刀具");
	enum06Props->SetLogical("Enable", TRUE);
	delete enum06Props;

	PropertyList* double05Props = double05->GetProperties();
	double05Props->SetDouble("Value", 50);
	double05Props->SetLogical("Enable", TRUE);
	delete double05Props;

	PropertyList* double07Props = double07->GetProperties();
	double07Props->SetDouble("Value", 0);
	double07Props->SetLogical("Enable", TRUE);
	delete double07Props;

	PropertyList* double08Props = double08->GetProperties();
	double08Props->SetDouble("Value", 0);
	double08Props->SetLogical("Enable", FALSE);
	delete double08Props;

	PropertyList* double09Props = double09->GetProperties();
	double09Props->SetDouble("Value", 90);
	double09Props->SetLogical("Enable", TRUE);
	delete double09Props;

	PropertyList* double010Props = double010->GetProperties();
	double010Props->SetDouble("Value", 0);
	double010Props->SetLogical("Enable", TRUE);
	delete double010Props;

	PropertyList* enum012Props = enum012->GetProperties();
	enum012Props->SetEnumAsString("Value", "mm");
	enum012Props->SetLogical("Enable", TRUE);
	delete enum012Props;


	PropertyList* enum03Props = enum03->GetProperties();
	enum03Props->SetEnumAsString("Value", "包容圆柱体");
	delete enum03Props;

	PropertyList* plane0Props = plane0->GetProperties();
	plane0Props->SetLogical("Enable", FALSE);
	delete plane0Props;

	PropertyList* double014Props = double014->GetProperties();
	double014Props->SetDouble("Value", 30);
	delete double014Props;
}

void BossSideMilling::ReadXmlFile_Boss()
{
	try
	{
		ListOfBoss.clear();
		ListOfDLBoss.clear();
		ListOfNBoss.clear();
		ListOfNSBoss.clear();

		PropertyList* File = nativeFileBrowser0->GetProperties();
		NXString FileString = File->GetString("Path");

		IXMLDOMDocumentPtr pXMLDom;
		HRESULT hr;
		CoInitialize(NULL);
		hr = pXMLDom.CreateInstance("msxml2.domdocument");
		if (FAILED(hr))
		{
			uc1601("Load XML file failed!", 1);
			return;
		}

		VARIANT var;
		VariantInit(&var);
		VARIANT_BOOL bFlag;
		BSTR FileName = ConvertToBSTR(FileString);
		V_BSTR(&var) = SysAllocString(FileName);
		V_VT(&var) = VT_BSTR;
		hr = pXMLDom->load(var, &bFlag);

		IXMLDOMElementPtr rootPtr;

		IXMLDOMNodeListPtr AllFeatureNodeList;
		pXMLDom->get_documentElement(&rootPtr);

		BSTR TagName;
		NXString NodeStr;

		rootPtr->get_nodeName(&TagName);

		char* CharString = _com_util::ConvertBSTRToString(TagName);

		NodeStr = CharString;

		char* nodename = "特征识别结果列表";
		if (!strstr(CharString, nodename))
		{
			uc1601("读入的不是特征识别结果列表！", 1);
			return;
		}

		rootPtr->get_childNodes(&AllFeatureNodeList);

		IXMLDOMNodePtr BossNode;

		AllFeatureNodeList->get_item(2, &BossNode);

		IXMLDOMNodeListPtr AllBossNodeList;
		BossNode->get_childNodes(&AllBossNodeList);

		long BosslistLength;
		AllBossNodeList->get_length(&BosslistLength);

		for (int i = 0; i < BosslistLength; i++)
		{
			IXMLDOMNodePtr EachBossNode;
			AllBossNodeList->get_item(i, &EachBossNode);

			IXMLDOMNodeListPtr EachBossNodeList;
			EachBossNode->get_childNodes(&EachBossNodeList);

			BSTR BossTagName;
			NXString BossNodeStr;
			EachBossNode->get_nodeName(&BossTagName);
			char* BossCharString = _com_util::ConvertBSTRToString(BossTagName);
			BossNodeStr = BossCharString;

			char* bossnodename = "含侧面凸台";
			char* nsbossnodename = "无侧面凸台";
			char* dlbossnodename = "多层凸台";
			char* outside = "外侧";
			char* inside = "内侧";

			if (strstr(BossCharString, bossnodename) != NULL)
			{
				NormalBoss* pTempBoss = new NormalBoss;
				if (strstr(BossCharString, inside) != NULL)
				{
					pTempBoss->OutOrIn = 0;
				}
				else if (strstr(BossCharString, outside) != NULL)
				{
					pTempBoss->OutOrIn = 1;
				}
				pTempBoss->name = BossCharString;

				IXMLDOMNodePtr EachBossBottomCornerNode;
				EachBossNodeList->get_item(0, &EachBossBottomCornerNode);

				IXMLDOMNodeListPtr EachBossBottomCornerNodeList;
				EachBossBottomCornerNode->get_childNodes(&EachBossBottomCornerNodeList);

				long EachBossBottomCornerNodeListLength;
				EachBossBottomCornerNodeList->get_length(&EachBossBottomCornerNodeListLength);

				for (int j = 0; j < EachBossBottomCornerNodeListLength; j++)
				{
					IXMLDOMNodePtr EachBossBottomCorner;
					EachBossBottomCornerNodeList->get_item(j, &EachBossBottomCorner);

					BSTR BottomCornerFaceTag_bstr;
					EachBossBottomCorner->get_text(&BottomCornerFaceTag_bstr);

					NXString iStringBottomCornerFaceTag = ConvertToString(BottomCornerFaceTag_bstr);
					std::string BottomCornerFaceTagString(iStringBottomCornerFaceTag.GetUTF8Text());
					int BottomCornerFaceTag = atoi(BottomCornerFaceTagString.c_str());


					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == BottomCornerFaceTag)
						{
							pTempBoss->BottomCornerFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachBossSideNode;
				EachBossNodeList->get_item(1, &EachBossSideNode);

				IXMLDOMNodeListPtr EachBossSideNodeList;
				EachBossSideNode->get_childNodes(&EachBossSideNodeList);

				long EachBossSideNodeListLength;
				EachBossSideNodeList->get_length(&EachBossSideNodeListLength);

				for (int j = 0; j < EachBossSideNodeListLength; j++)
				{
					IXMLDOMNodePtr EachBossSide;
					EachBossSideNodeList->get_item(j, &EachBossSide);

					BSTR SideFaceTag_bstr;
					EachBossSide->get_text(&SideFaceTag_bstr);

					NXString iStringSideFaceTag = ConvertToString(SideFaceTag_bstr);
					std::string SideFaceTagString(iStringSideFaceTag.GetUTF8Text());
					int SideFaceTag = atoi(SideFaceTagString.c_str());

					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == SideFaceTag)
						{
							pTempBoss->SideFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachBossTopNode;
				EachBossNodeList->get_item(2, &EachBossTopNode);

				IXMLDOMNodeListPtr EachBossTopNodeList;
				EachBossTopNode->get_childNodes(&EachBossTopNodeList);

				long EachBossTopNodeListLength;
				EachBossTopNodeList->get_length(&EachBossTopNodeListLength);

				for (int j = 0; j < EachBossTopNodeListLength; j++)
				{
					IXMLDOMNodePtr EachBossTop;
					EachBossTopNodeList->get_item(j, &EachBossTop);

					BSTR TopFaceTag_bstr;
					EachBossTop->get_text(&TopFaceTag_bstr);

					NXString iStringTopFaceTag = ConvertToString(TopFaceTag_bstr);
					std::string TopFaceTagString(iStringTopFaceTag.GetUTF8Text());
					int TopFaceTag = atoi(TopFaceTagString.c_str());


					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == TopFaceTag)
						{
							pTempBoss->TopFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}
				if (pTempBoss->TopFaceVector.size() != 0)
				{
					ListOfNBoss.push_back(pTempBoss);
				}
			}
			else if (strstr(BossCharString, nsbossnodename) != NULL)
			{
				NoSideBoss* pTempBoss = new NoSideBoss;
				if (strstr(BossCharString, inside) != NULL)
				{
					pTempBoss->OutOrIn = 0;
				}
				else if (strstr(BossCharString, outside) != NULL)
				{
					pTempBoss->OutOrIn = 1;
				}
				pTempBoss->name = BossCharString;

				IXMLDOMNodePtr EachBossBottomCornerNode;
				EachBossNodeList->get_item(0, &EachBossBottomCornerNode);

				IXMLDOMNodeListPtr EachBossBottomCornerNodeList;
				EachBossBottomCornerNode->get_childNodes(&EachBossBottomCornerNodeList);

				long EachBossBottomCornerNodeListLength;
				EachBossBottomCornerNodeList->get_length(&EachBossBottomCornerNodeListLength);

				for (int j = 0; j < EachBossBottomCornerNodeListLength; j++)
				{
					IXMLDOMNodePtr EachBossBottomCorner;
					EachBossBottomCornerNodeList->get_item(j, &EachBossBottomCorner);//凸台.i+1

					BSTR BottomCornerFaceTag_bstr;
					EachBossBottomCorner->get_text(&BottomCornerFaceTag_bstr);

					NXString iStringBottomCornerFaceTag = ConvertToString(BottomCornerFaceTag_bstr);
					std::string BottomCornerFaceTagString(iStringBottomCornerFaceTag.GetUTF8Text());
					int BottomCornerFaceTag = atoi(BottomCornerFaceTagString.c_str());

					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == BottomCornerFaceTag)
						{
							pTempBoss->BottomCornerFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachBossTopNode;
				EachBossNodeList->get_item(1, &EachBossTopNode);

				IXMLDOMNodeListPtr EachBossTopNodeList;
				EachBossTopNode->get_childNodes(&EachBossTopNodeList);

				long EachBossTopNodeListLength;
				EachBossTopNodeList->get_length(&EachBossTopNodeListLength);

				for (int j = 0; j < EachBossTopNodeListLength; j++)
				{
					IXMLDOMNodePtr EachBossTop;
					EachBossTopNodeList->get_item(j, &EachBossTop);

					BSTR TopFaceTag_bstr;
					EachBossTop->get_text(&TopFaceTag_bstr);

					NXString iStringTopFaceTag = ConvertToString(TopFaceTag_bstr);
					std::string TopFaceTagString(iStringTopFaceTag.GetUTF8Text());
					int TopFaceTag = atoi(TopFaceTagString.c_str());

					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == TopFaceTag)
						{
							pTempBoss->TopFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}
				if (pTempBoss->TopFaceVector.size() != 0)
				{
					ListOfNSBoss.push_back(pTempBoss);
				}
			}
			else if (strstr(BossCharString, dlbossnodename) != NULL)
			{
				DoubleLayerBoss* pTempBoss = new DoubleLayerBoss;
				if (strstr(BossCharString, inside) != NULL)
				{
					pTempBoss->OutOrIn = 0;
				}
				else if (strstr(BossCharString, outside) != NULL)
				{
					pTempBoss->OutOrIn = 1;
				}
				pTempBoss->name = BossCharString;

				IXMLDOMNodePtr EachDLBossBottomCornerNode;
				EachBossNodeList->get_item(0, &EachDLBossBottomCornerNode);

				IXMLDOMNodeListPtr EachDLBossBottomCornerNodeList;
				EachDLBossBottomCornerNode->get_childNodes(&EachDLBossBottomCornerNodeList);

				long EachDLBossBottomCornerNodeListLength;
				EachDLBossBottomCornerNodeList->get_length(&EachDLBossBottomCornerNodeListLength);

				for (int j = 0; j < EachDLBossBottomCornerNodeListLength; j++)
				{
					IXMLDOMNodePtr EachDLBossBottomCorner;
					EachDLBossBottomCornerNodeList->get_item(j, &EachDLBossBottomCorner);

					BSTR BottomCornerFaceTag_bstr;
					EachDLBossBottomCorner->get_text(&BottomCornerFaceTag_bstr);

					NXString iStringBottomCornerFaceTag = ConvertToString(BottomCornerFaceTag_bstr);
					std::string BottomCornerFaceTagString(iStringBottomCornerFaceTag.GetUTF8Text());
					int BottomCornerFaceTag = atoi(BottomCornerFaceTagString.c_str());


					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == BottomCornerFaceTag)
						{
							pTempBoss->BottomCornerFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachDLBossSideNode;
				EachBossNodeList->get_item(1, &EachDLBossSideNode);

				IXMLDOMNodeListPtr EachDLBossSideNodeList;
				EachDLBossSideNode->get_childNodes(&EachDLBossSideNodeList);

				long EachDLBossSideNodeListLength;
				EachDLBossSideNodeList->get_length(&EachDLBossSideNodeListLength);

				for (int j = 0; j < EachDLBossSideNodeListLength; j++)
				{
					IXMLDOMNodePtr EachDLBossSide;
					EachDLBossSideNodeList->get_item(j, &EachDLBossSide);//凸台.i+1

					BSTR SideFaceTag_bstr;
					EachDLBossSide->get_text(&SideFaceTag_bstr);

					NXString iStringSideFaceTag = ConvertToString(SideFaceTag_bstr);
					std::string SideFaceTagString(iStringSideFaceTag.GetUTF8Text());
					int SideFaceTag = atoi(SideFaceTagString.c_str());


					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == SideFaceTag)
						{
							pTempBoss->SideFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachDLBossTopNode;
				EachBossNodeList->get_item(2, &EachDLBossTopNode);

				IXMLDOMNodeListPtr EachDLBossTopNodeList;
				EachDLBossTopNode->get_childNodes(&EachDLBossTopNodeList);

				long EachDLBossTopNodeListLength;
				EachDLBossTopNodeList->get_length(&EachDLBossTopNodeListLength);

				for (int j = 0; j < EachDLBossTopNodeListLength; j++)
				{
					IXMLDOMNodePtr EachDLBossTop;
					EachDLBossTopNodeList->get_item(j, &EachDLBossTop);

					BSTR TopFaceTag_bstr;
					EachDLBossTop->get_text(&TopFaceTag_bstr);

					NXString iStringTopFaceTag = ConvertToString(TopFaceTag_bstr);
					std::string TopFaceTagString(iStringTopFaceTag.GetUTF8Text());
					int TopFaceTag = atoi(TopFaceTagString.c_str());


					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == TopFaceTag)
						{
							pTempBoss->TopFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachDLBossNTopNode;
				EachBossNodeList->get_item(3, &EachDLBossNTopNode);

				IXMLDOMNodeListPtr EachDLBossNTopNodeList;
				EachDLBossNTopNode->get_childNodes(&EachDLBossNTopNodeList);

				long EachDLBossNTopNodeListLength;
				EachDLBossNTopNodeList->get_length(&EachDLBossNTopNodeListLength);

				for (int j = 0; j < EachDLBossNTopNodeListLength; j++)
				{
					IXMLDOMNodePtr EachDLBossNTop;
					EachDLBossNTopNodeList->get_item(j, &EachDLBossNTop);

					BSTR TopFaceTag_bstr;
					EachDLBossNTop->get_text(&TopFaceTag_bstr);

					NXString iStringTopFaceTag = ConvertToString(TopFaceTag_bstr);
					std::string TopFaceTagString(iStringTopFaceTag.GetUTF8Text());
					int TopFaceTag = atoi(TopFaceTagString.c_str());


					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == TopFaceTag)
						{
							pTempBoss->NTopFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachDLBossNSideNode;
				EachBossNodeList->get_item(4, &EachDLBossNSideNode);

				IXMLDOMNodeListPtr EachDLBossNSideNodeList;
				EachDLBossNSideNode->get_childNodes(&EachDLBossNSideNodeList);

				long EachDLBossNSideNodeListLength;
				EachDLBossNSideNodeList->get_length(&EachDLBossNSideNodeListLength);

				for (int j = 0; j < EachDLBossNSideNodeListLength; j++)
				{
					IXMLDOMNodePtr EachDLBossNSide;
					EachDLBossNSideNodeList->get_item(j, &EachDLBossNSide);

					BSTR SideFaceTag_bstr;
					EachDLBossNSide->get_text(&SideFaceTag_bstr);

					NXString iStringSideFaceTag = ConvertToString(SideFaceTag_bstr);
					std::string SideFaceTagString(iStringSideFaceTag.GetUTF8Text());
					int SideFaceTag = atoi(SideFaceTagString.c_str());


					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == SideFaceTag)
						{
							pTempBoss->NSideFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				IXMLDOMNodePtr EachDLBossConnectNode;
				EachBossNodeList->get_item(5, &EachDLBossConnectNode);

				IXMLDOMNodeListPtr EachDLBossConnectNodeList;
				EachDLBossConnectNode->get_childNodes(&EachDLBossConnectNodeList);

				long EachDLBossConnectNodeListLength;
				EachDLBossConnectNodeList->get_length(&EachDLBossConnectNodeListLength);

				for (int j = 0; j < EachDLBossConnectNodeListLength; j++)
				{
					IXMLDOMNodePtr EachDLBossConnect;
					EachDLBossConnectNodeList->get_item(j, &EachDLBossConnect);

					BSTR ConnectFaceTag_bstr;
					EachDLBossConnect->get_text(&ConnectFaceTag_bstr);

					NXString iStringConnectFaceTag = ConvertToString(ConnectFaceTag_bstr);
					std::string ConnectFaceTagString(iStringConnectFaceTag.GetUTF8Text());
					int ConnectFaceTag = atoi(ConnectFaceTagString.c_str());


					for (std::vector<Face*>::size_type k = 0; k != AllFaces.size(); k++)
					{
						Face* pFace_Each = AllFaces[k];
						if (pFace_Each->Tag() == ConnectFaceTag)
						{
							pTempBoss->ConnectFaceVector.push_back(pFace_Each);
							break;
						}
					}
				}

				if (pTempBoss->TopFaceVector.size() != 0)
				{
					ListOfDLBoss.push_back(pTempBoss);
				}
			}
		}
		if (ListOfNBoss.size() == 0 && ListOfDLBoss.size() == 0 && ListOfNSBoss.size() == 0)
		{
			uc1601("Read XML file failed!\n Error is:\n待加工零件模型与特征识别文件所属模型 不完全匹配!", 1);

			return;
		}

		IXMLDOMNodePtr NormalNode;
		AllFeatureNodeList->get_item(5, &NormalNode);

		IXMLDOMNodeListPtr NormalNodeList;
		NormalNode->get_childNodes(&NormalNodeList);

		IXMLDOMNodePtr NormalX;
		NormalNodeList->get_item(0, &NormalX);

		BSTR NormalX_bstr;
		NormalX->get_text(&NormalX_bstr);

		NXString iStringNormalX = ConvertToString(NormalX_bstr);
		std::string NormalXString(iStringNormalX.GetUTF8Text());

		std::string::size_type position;
		position = NormalXString.find(",");
		std::string subStr = NormalXString.substr(0, position);
		double X = atof(subStr.c_str());

		std::string::size_type EndY;
		EndY = NormalXString.length();
		std::string NormalYString = NormalXString.substr(position + 1, EndY);
		std::string::size_type position1;
		position1 = NormalYString.find(",");
		std::string subStr1 = NormalYString.substr(0, position1);
		double Y = atof(subStr1.c_str());

		std::string::size_type EndZ;
		EndZ = NormalYString.length();
		std::string NormalZString = NormalYString.substr(position1 + 1, EndZ);
		double Z = atof(NormalZString.c_str());

		NXOpen::Vector3d _Normal(X, Y, Z);
		ParameterSet.Approch_Normal = _Normal;
	}
	catch (exception& ex2)
	{
		uc1601("Read XML file failed!\n Error is:\n几何模型与特征识别模型不完全匹配!", 1);

	}
}

BSTR BossSideMilling::ConvertToBSTR(NXString iString)
{
	char* istr = (char*)iString.GetUTF8Text();
	BSTR bstr = _com_util::ConvertStringToBSTR(istr);
	return bstr;
}

NXString BossSideMilling::ConvertToString(BSTR bstr)
{
	char* istr = _com_util::ConvertBSTRToString(bstr);
	NXString str(istr);
	return str;
}

void BossSideMilling::SelectedFaceCampare(std::vector<NXOpen::Face*> SelectedFaceList, std::vector<NXOpen::Face*> FaceList)
{
	bool SearchFaceFlag;
	std::vector<Face*>::iterator iter = SelectedFaceList.begin();
	while (iter != SelectedFaceList.end())
	{
		Face* SelectedFace = *iter;

		int FaceListSize = FaceList.size();
		for (int j = 0; j != FaceListSize; j++)
		{
			Face* BossTopFace = BossTopFaceList[j];
			tag_t SelectedFaceTag = SelectedFace->Tag();
			tag_t BossTopFaceTag = BossTopFace->Tag();

			if (SelectedFaceTag == BossTopFaceTag)
			{
				SearchFaceFlag = TRUE;
				break;
			}
			else
			{
				SearchFaceFlag = FALSE;
			}
		}

		if (SearchFaceFlag)
		{
			iter++;
		}

		else
		{
			char* str("请选择正确的凸台顶面");
			uc1601(str, 1);
			break;
		}
	}
}
