//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  Z:\xinduihuakuang\PlanGrooveMilling.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 06-17-2024  (Format: mm-dd-yyyy)
//              Time: 23:58
//
//==============================================================================

#ifndef PLANGROOVEMILLING_H_INCLUDED
#define PLANGROOVEMILLING_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_FileSelection.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/BlockStyler_FaceCollector.hxx>
#include <NXOpen/BlockStyler_TabControl.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_SpecifyPlane.hxx>
#include <NXOpen/BlockStyler_Button.hxx>

#include <NXOpen/Part.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/NXObjectManager.hxx>
#include <NXOpen/CAM_CAMObject.hxx>
#include <NXOpen/CartesianCoordinateSystem.hxx>
#include <NXOpen/CAM_NCGroup.hxx>
#include <NXOpen/CAM_MillToolBuilder.hxx>
#include <NXOpen/CAM_CAMSetup.hxx>
#include <NXOpen/CAM_NCGroupCollection.hxx>
#include <NXOpen/CAM_Tool.hxx>
#include <NXOpen/CAM_InheritableDoubleBuilder.hxx>
#include <uf_ui.h>
#include <uf.h>

#include <comdef.h>
#include <comutil.h>

#include "FeaturePublicClass.h"
#include "ProcessPublicClass.h"
#include "PlanerBlindGrooveMillingCmd.h"

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport PlanGrooveMilling
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    PlanGrooveMilling();
    ~PlanGrooveMilling();
    int Show();

	bool ReadXMLOK;
	NXOpen::Part * workPart;
	NXOpen::Body * selectedBody;
	NXOpen::Body * selectedBlank;
	std::vector<Face*> AllFaces;
	std::vector<PlanerBlindGroove*> ListOfPlanerBlindGroove;
	std::vector<Boss*> ListOfBoss;

	std::vector<Face*> SelectedArcCavityBottomFaceList;
	std::vector<Face*> ArcCavityBottomFaceFaceList;
	std::vector<Face*> SelectedPlanerBlindGrooveBottomFaceList;
	std::vector<Face*> PlanerBlindGrooveBottomFaceList;

	PlanerBlindGrooveProcessParameter ParameterSet;

	std::vector<CAM::CAMObject*> ProgramMembers;
	std::vector<NXString> ProgramStringList;
	std::vector<CAM::CAMObject*> ToolMembers;
	std::vector<NXString> ToolStringList;
	std::vector<CAM::CAMObject*> MCSMembers;
	std::vector<NXString> MCSStringList;
	std::vector<CAM::CAMObject*> MethodMembers;
	std::vector<NXString> MethodStringList;
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the PlanGrooveMilling.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);

	void InitialParameters();
	void ReadXmlFile_ArcCavity();
	void ReadXmlFile_PlanerBlindGroove();
	BSTR ConvertToBSTR(NXString iString);
	NXString ConvertToString(BSTR bstr);
	void SelectedFaceCampare(std::vector<NXOpen::Face*> SelectedFaceList, std::vector<NXOpen::Face*> FaceList);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* bodySelect0;// Block type: Body Collector
    NXOpen::BlockStyler::FileSelection* nativeFileBrowser0;// Block type: NativeFileBrowser
    NXOpen::BlockStyler::Enumeration* enum010;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum01;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum08;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::Toggle* toggle03;// Block type: Toggle
    NXOpen::BlockStyler::BodyCollector* bodySelect01;// Block type: Body Collector
    NXOpen::BlockStyler::Toggle* toggle05;// Block type: Toggle
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group4;// Block type: Group
    NXOpen::BlockStyler::Toggle* toggle02;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle04;// Block type: Toggle
    NXOpen::BlockStyler::FaceCollector* face_select0;// Block type: Face Collector
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::TabControl* tabControl;// Block type: Tabs Page
    NXOpen::BlockStyler::Group* tabPage;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum07;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum02;// Block type: Enumeration
    NXOpen::BlockStyler::Toggle* toggle0;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggle01;// Block type: Toggle
    NXOpen::BlockStyler::Enumeration* enum09;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double012;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double013;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double015;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage1;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double0;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double011;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double01;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double02;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double03;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double04;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage2;// Block type: Group
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum05;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double06;// Block type: Double
    NXOpen::BlockStyler::Enumeration* enum011;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double05;// Block type: Double
    NXOpen::BlockStyler::Enumeration* enum06;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double07;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double08;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double09;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double010;// Block type: Double
    NXOpen::BlockStyler::Enumeration* enum012;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum03;// Block type: Enumeration
    NXOpen::BlockStyler::SpecifyPlane* plane0;// Block type: Specify Plane
    NXOpen::BlockStyler::DoubleBlock* double014;// Block type: Double
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    
};
#endif //PLANGROOVEMILLING_H_INCLUDED
