//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\ug12\Desktop\HuNXTool\Application\fullsetholecolor.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: ug12
//              Version: NX 12
//              Date: 04-17-2026  (Format: mm-dd-yyyy)
//              Time: 19:20 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "fullsetholecolor.hpp"
#include <vector>
#include <map>
#include <string>
#include <sstream>
#include <cmath>

#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/BodyCollection.hxx>

#include <NXOpen/Body.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Edge.hxx>
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/ListingWindow.hxx>
#include <NXOpen/NXObjectManager.hxx>

#include <uf.h>
#include <uf_obj.h>
#include <uf_modl.h>

using namespace NXOpen;
using namespace NXOpen::BlockStyler;

namespace
{
	std::vector<NXOpen::DisplayableObject*> g_holeFaces;
	std::map<tag_t, int> g_originalColors;
	bool g_isColoredRed = false;

	double Dot3(const double a[3], const double b[3])
	{
		return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
	}

	double Norm3(const double v[3])
	{
		return std::sqrt(Dot3(v, v));
	}

	bool Normalize3(double v[3])
	{
		double n = Norm3(v);
		if (n < 1.0e-9)
			return false;
		v[0] /= n;
		v[1] /= n;
		v[2] /= n;
		return true;
	}

	bool IsParallel(const double a[3], const double b[3], double tolCos)
	{
		double aa[3] = { a[0], a[1], a[2] };
		double bb[3] = { b[0], b[1], b[2] };

		if (!Normalize3(aa) || !Normalize3(bb))
			return false;

		return std::fabs(Dot3(aa, bb)) >= tolCos;
	}

	bool AskFaceData(
		tag_t faceTag,
		int& type,
		double point[3],
		double dir[3],
		double box[6],
		double& radius,
		double& radData,
		int& normDir)
	{
		int rc = UF_MODL_ask_face_data(
			faceTag,
			&type,
			point,
			dir,
			box,
			&radius,
			&radData,
			&normDir);

		return (rc == 0);
	}

	bool GetPlanarFaceNormal(tag_t faceTag, double normal[3])
	{
		int type = 0;
		int normDir = 0;
		double point[3] = { 0.0, 0.0, 0.0 };
		double dir[3] = { 0.0, 0.0, 0.0 };
		double box[6] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
		double radius = 0.0;
		double radData = 0.0;

		if (!AskFaceData(faceTag, type, point, dir, box, radius, radData, normDir))
			return false;

		if (type != UF_MODL_PLANAR_FACE)
			return false;

		normal[0] = dir[0];
		normal[1] = dir[1];
		normal[2] = dir[2];
		return Normalize3(normal);
	}

	bool GetCylOrConeAxis(tag_t faceTag, int& outType, double axis[3], double& radius)
	{
		int type = 0;
		int normDir = 0;
		double point[3] = { 0.0, 0.0, 0.0 };
		double dir[3] = { 0.0, 0.0, 0.0 };
		double box[6] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
		double r = 0.0;
		double radData = 0.0;

		if (!AskFaceData(faceTag, type, point, dir, box, r, radData, normDir))
			return false;

		if (type != UF_MODL_CYLINDRICAL_FACE && type != UF_MODL_CONICAL_FACE)
			return false;

		axis[0] = dir[0];
		axis[1] = dir[1];
		axis[2] = dir[2];
		if (!Normalize3(axis))
			return false;

		outType = type;
		radius = r;
		return true;
	}

	int GetSimpleFaceType(tag_t faceTag)
	{
		int type = 0;
		int normDir = 0;
		double point[3] = { 0.0, 0.0, 0.0 };
		double dir[3] = { 0.0, 0.0, 0.0 };
		double box[6] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
		double radius = 0.0;
		double radData = 0.0;

		if (!AskFaceData(faceTag, type, point, dir, box, radius, radData, normDir))
			return -1;

		return type;
	}

	void ClearHighlight()
	{
		for (size_t i = 0; i < g_holeFaces.size(); ++i)
		{
			try
			{
				if (g_holeFaces[i] != NULL)
					g_holeFaces[i]->Unhighlight();
			}
			catch (...)
			{
			}
		}
		g_holeFaces.clear();
	}

	void HighlightFaces(const std::vector<NXOpen::DisplayableObject*>& faces)
	{
		for (size_t i = 0; i < faces.size(); ++i)
		{
			if (faces[i] != NULL)
				faces[i]->Highlight();
		}
	}

	bool CandidateFaceLooksLikeHoleWall(
		NXOpen::Face* face)
	{
		if (face == NULL)
			return false;

		int faceType = 0;
		double axis[3] = { 0.0, 0.0, 0.0 };
		double radius = 0.0;

		if (!GetCylOrConeAxis(face->Tag(), faceType, axis, radius))
			return false;

		if (radius < 1.0e-4)
			return false;

		std::vector<NXOpen::Edge*> edges = face->GetEdges();

		int planarPerpCount = 0;
		int coaxialConeCount = 0;

		for (size_t i = 0; i < edges.size(); ++i)
		{
			NXOpen::Edge* edge = edges[i];
			if (edge == NULL)
				continue;

			std::vector<NXOpen::Face*> nbrFaces = edge->GetFaces();

			for (size_t j = 0; j < nbrFaces.size(); ++j)
			{
				NXOpen::Face* nbr = nbrFaces[j];
				if (nbr == NULL || nbr->Tag() == face->Tag())
					continue;

				double planeNormal[3] = { 0.0, 0.0, 0.0 };
				if (GetPlanarFaceNormal(nbr->Tag(), planeNormal))
				{
					if (IsParallel(planeNormal, axis, 0.97))
					{
						++planarPerpCount;
					}
					continue;
				}

				int nbrType = 0;
				double nbrAxis[3] = { 0.0, 0.0, 0.0 };
				double nbrRadius = 0.0;
				if (GetCylOrConeAxis(nbr->Tag(), nbrType, nbrAxis, nbrRadius))
				{
					if (nbrType == UF_MODL_CONICAL_FACE && IsParallel(nbrAxis, axis, 0.97))
					{
						++coaxialConeCount;
					}
				}
			}
		}

		if (planarPerpCount >= 1)
			return true;

		if (coaxialConeCount >= 1)
			return true;

		return false;
	}
}

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(fullsetholecolor::theSession) = NULL;
UI *(fullsetholecolor::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
fullsetholecolor::fullsetholecolor()
{
    try
    {
        // Initialize the NX Open C++ API environment
        fullsetholecolor::theSession = NXOpen::Session::GetSession();
        fullsetholecolor::theUI = UI::GetUI();
        theDlxFileName = "fullsetholecolor.dlx";
        theDialog = fullsetholecolor::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &fullsetholecolor::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &fullsetholecolor::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &fullsetholecolor::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &fullsetholecolor::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &fullsetholecolor::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
fullsetholecolor::~fullsetholecolor()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    fullsetholecolor *thefullsetholecolor = NULL;
    try
    {
        thefullsetholecolor = new fullsetholecolor();
        // The following method shows the dialog immediately
        thefullsetholecolor->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        fullsetholecolor::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(thefullsetholecolor != NULL)
    {
        delete thefullsetholecolor;
        thefullsetholecolor = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        fullsetholecolor::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int fullsetholecolor::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        fullsetholecolor::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void fullsetholecolor::initialize_cb()
{
    try
    {
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        bodySelect0 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect0"));
        face_select0 = dynamic_cast<NXOpen::BlockStyler::FaceCollector*>(theDialog->TopBlock()->FindBlock("face_select0"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        list_box0 = dynamic_cast<NXOpen::BlockStyler::ListBox*>(theDialog->TopBlock()->FindBlock("list_box0"));
        button01 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        //------------------------------------------------------------------------------
        //Registration of ListBox specific callbacks
        //------------------------------------------------------------------------------
        //list_box0->SetAddHandler(make_callback(this, &fullsetholecolor::AddCallback));
        
        //list_box0->SetDeleteHandler(make_callback(this, &fullsetholecolor::DeleteCallback));
        
        //------------------------------------------------------------------------------
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        fullsetholecolor::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void fullsetholecolor::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        fullsetholecolor::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int fullsetholecolor::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        fullsetholecolor::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int fullsetholecolor::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == bodySelect0)
        {
        //---------Enter your code here-----------
        }
        else if(block == face_select0)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
        }
        else if(block == button0)
        {
            NXOpen::BlockStyler::PropertyList* enumProps = enum0->GetProperties();
            int enumVal = enumProps->GetEnum("Value");
            delete enumProps;

            if (enumVal != 0) {
                fullsetholecolor::theUI->NXMessageBox()->Show("提示 ", NXOpen::NXMessageBox::DialogTypeInformation, "当前仅支持孔特征识别！ ");
                return 0;
            }

            NXOpen::BlockStyler::PropertyList* bodyProps = bodySelect0->GetProperties();
            std::vector<NXOpen::TaggedObject*> selBodies = bodyProps->GetTaggedObjectVector("SelectedObjects");
            delete bodyProps;

            if (selBodies.empty()) {
                fullsetholecolor::theUI->NXMessageBox()->Show("提示 ", NXOpen::NXMessageBox::DialogTypeInformation, "请先选中用于识别孔特征的体！ ");
                return 0;
            }

            NXOpen::BlockStyler::PropertyList* faceProps = face_select0->GetProperties();
            std::vector<NXOpen::TaggedObject*> selFaces = faceProps->GetTaggedObjectVector("SelectedObjects");
            delete faceProps;

            bool hasRefFace = false;
            double refNormal[3] = {0.0, 0.0, 0.0};
            if (!selFaces.empty()) {
                NXOpen::Face* refFace = dynamic_cast<NXOpen::Face*>(selFaces[0]);
                if (refFace) {
                    if (GetPlanarFaceNormal(refFace->Tag(), refNormal)) {
                        hasRefFace = true;
                    } else {
                        fullsetholecolor::theUI->NXMessageBox()->Show("警告 ", NXOpen::NXMessageBox::DialogTypeWarning, "参考面必须是平面。本次识别将不使用该面进行过滤。 ");
                    }
                }
            }

            if (g_isColoredRed) {
                for (size_t i = 0; i < g_holeFaces.size(); ++i) {
                    if (g_holeFaces[i] && g_originalColors.count(g_holeFaces[i]->Tag())) {
                        g_holeFaces[i]->SetColor(g_originalColors[g_holeFaces[i]->Tag()]);
                        g_holeFaces[i]->RedisplayObject();
                    }
                }
                g_isColoredRed = false;
            }
            ClearHighlight();
            g_originalColors.clear();

            for (size_t i = 0; i < selBodies.size(); ++i) {
                NXOpen::Body* body = dynamic_cast<NXOpen::Body*>(selBodies[i]);
                if (!body || !body->IsSolidBody()) continue;

                std::vector<NXOpen::Face*> faces = body->GetFaces();
                for (size_t j = 0; j < faces.size(); ++j) {
                    NXOpen::Face* face = faces[j];
                    if (CandidateFaceLooksLikeHoleWall(face)) {
                        if (hasRefFace) {
                            int faceType = 0;
                            double axis[3] = {0.0, 0.0, 0.0};
                            double radius = 0.0;
                            if (GetCylOrConeAxis(face->Tag(), faceType, axis, radius)) {
                                if (!IsParallel(axis, refNormal, 0.97)) { 
                                    continue;
                                }
                            }
                        }
                        g_holeFaces.push_back(face);
                    }
                }
            }

            HighlightFaces(g_holeFaces);

            std::vector<NXString> listItems;
            listItems.push_back(NXString("- 识别结果 (Recognition Results) -"));
            
            char summaryBuf[128];
            sprintf(summaryBuf, "  共找到 %d 个孔面候选 (Found %d faces)", (int)g_holeFaces.size(), (int)g_holeFaces.size());
            listItems.push_back(NXString(summaryBuf));

            for (size_t i = 0; i < g_holeFaces.size(); ++i) {
                char buf[128];
                sprintf(buf, "  -> 孔面(Face) Tag: %d", (int)g_holeFaces[i]->Tag());
                listItems.push_back(NXString(buf));
            }

            NXOpen::BlockStyler::PropertyList* listProps = list_box0->GetProperties();
            listProps->SetStrings("ListItems", listItems);
            delete listProps;

            char msgBuf[256];
            sprintf(msgBuf, "识别完成！共在选中的体上识别出 %d 个候选孔面。 ", (int)g_holeFaces.size());
            fullsetholecolor::theUI->NXMessageBox()->Show("信息 ", NXOpen::NXMessageBox::DialogTypeInformation, msgBuf);
        }
        else if(block == list_box0)
        {
        //---------Enter your code here-----------
        }
        else if(block == button01)
        {
            if (g_holeFaces.empty()) {
                fullsetholecolor::theUI->NXMessageBox()->Show("提示 ", NXOpen::NXMessageBox::DialogTypeWarning, "当前没有识别出来的特征可以标红。请先点击识别按钮。 ");
                return 0;
            }

            if (g_isColoredRed) {
                for (size_t i = 0; i < g_holeFaces.size(); ++i) {
                    if (g_holeFaces[i] && g_originalColors.count(g_holeFaces[i]->Tag())) {
                        g_holeFaces[i]->SetColor(g_originalColors[g_holeFaces[i]->Tag()]);
                        g_holeFaces[i]->RedisplayObject();
                    }
                }
                g_isColoredRed = false;
            } else {
                for (size_t i = 0; i < g_holeFaces.size(); ++i) {
                    if (g_holeFaces[i] != NULL) {
                        if (!g_originalColors.count(g_holeFaces[i]->Tag())) {
                            g_originalColors[g_holeFaces[i]->Tag()] = g_holeFaces[i]->Color();
                        }
                        g_holeFaces[i]->SetColor(186); // Red
                        g_holeFaces[i]->RedisplayObject();
                    }
                }
                g_isColoredRed = true;
            }
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        fullsetholecolor::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int fullsetholecolor::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        fullsetholecolor::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}
//------------------------------------------------------------------------------
//ListBox specific callbacks
//------------------------------------------------------------------------------
//int fullsetholecolor::AddCallback (NXOpen::BlockStyler::ListBox* list_box)
//{
//}

//int fullsetholecolor::DeleteCallback(NXOpen::BlockStyler::ListBox* list_box)
//{
//}

//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* fullsetholecolor::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
