//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\2023win640504\Application\FeatureSpy.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: NX
//              Version: NX 11
//              Date: 05-04-2023  (Format: mm-dd-yyyy)
//              Time: 21:31
//
//==============================================================================

#ifndef FEATURESPY_H_INCLUDED
#define FEATURESPY_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_FaceCollector.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport FeatureSpy
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    FeatureSpy();
    ~FeatureSpy();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the FeatureSpy.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
    //int AddCallback (NXOpen::BlockStyler::ListBox* list_box);
    //int DeleteCallback(NXOpen::BlockStyler::ListBox* list_box);
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* bodySelect0;// Block type: Body Collector
    NXOpen::BlockStyler::FaceCollector* face_select0;// Block type: Face Collector
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::ListBox* list_box0;// Block type: List Box
    NXOpen::BlockStyler::Button* button01;// Block type: Button
    
};
#endif //FEATURESPY_H_INCLUDED
