//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\fxy\Desktop\xindlx\RibMilling.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 06-11-2023  (Format: mm-dd-yyyy)
//              Time: 21:04
//
//==============================================================================

#ifndef RIBMILLING_H_INCLUDED
#define RIBMILLING_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_FileSelection.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/BlockStyler_FaceCollector.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_TabControl.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_SpecifyPlane.hxx>
#include <NXOpen/BlockStyler_Button.hxx>

#include <NXOpen/Part.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/BlockStyler_Label.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/NXObjectManager.hxx>
#include <NXOpen/CAM_CAMObject.hxx>
#include <NXOpen/CartesianCoordinateSystem.hxx>
#include <NXOpen/CAM_NCGroup.hxx>
#include <NXOpen/CAM_MillToolBuilder.hxx>
#include <NXOpen/CAM_CAMSetup.hxx>
#include <NXOpen/CAM_NCGroupCollection.hxx>
#include <NXOpen/CAM_Tool.hxx>
#include <NXOpen/CAM_InheritableDoubleBuilder.hxx>
#include <uf_ui.h>
#include <uf.h>
#include <NXOpen/CAM_DmSurfBuilder.hxx>
#include <comdef.h>
#include <comutil.h>
#include <vector>
#include <NXOpen/BlockStyler_IntegerBlock.hxx>

#include "FeaturePublicClass.h"
#include "ProcessPublicClass.h"
#include "AnnulusCavityBottomMillingCmd.h"


//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport RibMilling
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
	RibMilling();
	~RibMilling();
    int Show();

	bool ReadXMLOK;


	bool selectpartFlag = false;
	bool zuobiaoxiFlag = false;
	bool areaFlag = false;
	bool stepovernuFlag = false;


	NXOpen::Part * workPart;
	NXOpen::Body * selectedBody;
	NXOpen::Body * selectedBlank;
	std::vector<Face*> AllFaces;
	std::vector<ArcCavity*> ListOfCavity_Hu;      //读取的弧形槽列表
	std::vector<AnnulusCavity*> ListOfCavity_Huanout;      //读取的waice环形槽列表
	std::vector<AnnulusCavity*> ListOfCavity_Huanin;
	std::vector<AnnulusCavity*> ListOfCavity_Huan;

	std::vector<Boss*> ListOfBoss;      //读取的凸台列表

	ArcCavityProcessParameter ParameterSet_Hu;
	AnnulusCavityProcessParameter ParameterSet_Huan;

	std::vector<Face*> SelectedCavityBottomFaceList;
	std::vector<Face*> CavityBottomFaceFaceList;

	std::vector<CAM::CAMObject*> ProgramMembers;
	std::vector<NXString> ProgramStringList;
	std::vector<CAM::CAMObject*> ToolMembers;
	std::vector<NXString> ToolStringList;
	std::vector<CAM::CAMObject*> MCSMembers;
	std::vector<NXString> MCSStringList;
	std::vector<CAM::CAMObject*> MethodMembers;
	std::vector<NXString> MethodStringList;
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the RibMilling.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);

	void ReadXmlFile_ArcCavity();
	void ReadXmlFile_AnnulusCavity();
	BSTR ConvertToBSTR(NXString iString);
	NXString ConvertToString(BSTR bstr);
	void InitialParameters();

	void SelectedFaceCampare(std::vector<NXOpen::Face*> SelectedFaceList, std::vector<NXOpen::Face*> FaceList);

    
private:
    const char* theDlxFileName;
	NXOpen::BlockStyler::BlockDialog* theDialog;
	NXOpen::BlockStyler::Group* group41;// Block type: Group
	NXOpen::BlockStyler::BodyCollector* bodySelect011;// Block type: Body Collector
	NXOpen::BlockStyler::Enumeration* enumchengxu;// Block type: Enumeration
	NXOpen::BlockStyler::Enumeration* enumtool;// Block type: Enumeration
	NXOpen::BlockStyler::Enumeration* enumfangfa;// Block type: Enumeration
	NXOpen::BlockStyler::Group* group411;// Block type: Group
	NXOpen::BlockStyler::Toggle* togglejubu11;// Block type: Toggle
	NXOpen::BlockStyler::BodyCollector* bodySelect0111;// Block type: Body Collector
	NXOpen::BlockStyler::Toggle* togglenojubu11;// Block type: Toggle
	NXOpen::BlockStyler::Enumeration* enumpart11;// Block type: Enumeration
	NXOpen::BlockStyler::Group* group4;// Block type: Group
	NXOpen::BlockStyler::Label* label0;// Block type: Label
	NXOpen::BlockStyler::FaceCollector* face_select0;// Block type: Face Collector
	NXOpen::BlockStyler::Group* group1;// Block type: Group
	NXOpen::BlockStyler::TabControl* tabControl;// Block type: Tabs Page
	NXOpen::BlockStyler::Group* tabPage;// Block type: Group
	NXOpen::BlockStyler::Group* group3;// Block type: Group

    NXOpen::BlockStyler::Enumeration* enum07;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum02;// Block type: Enumeration
	NXOpen::BlockStyler::IntegerBlock* integer0;// Block type: Integer

    //NXOpen::BlockStyler::Toggle* toggle0;// Block type: Toggle
    //NXOpen::BlockStyler::Toggle* toggle01;// Block type: Toggle
    //NXOpen::BlockStyler::DoubleBlock* double012;// Block type: Double
    //NXOpen::BlockStyler::DoubleBlock* double013;// Block type: Double

    NXOpen::BlockStyler::Group* tabPage1;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double0;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double011;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double01;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double02;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double03;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double04;// Block type: Double
    NXOpen::BlockStyler::Group* tabPage2;// Block type: Group
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum05;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double06;// Block type: Double
    NXOpen::BlockStyler::Enumeration* enum011;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double05;// Block type: Double
    NXOpen::BlockStyler::Enumeration* enum06;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* double07;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double08;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double09;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double010;// Block type: Double
    NXOpen::BlockStyler::Enumeration* enum012;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum03;// Block type: Enumeration
    NXOpen::BlockStyler::SpecifyPlane* plane0;// Block type: Specify Plane
    NXOpen::BlockStyler::DoubleBlock* double014;// Block type: Double
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    
};
#endif //GROSIDEMILLING_H_INCLUDED
