//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\PRO_code\FBM_NX11_NUAA_Win32_D1020\Application\FeatureSpy.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: fxy
//              Version: NX 11
//              Date: 01-03-2024  (Format: mm-dd-yyyy)
//              Time: 15:41
//
//==============================================================================

#ifndef FEATURESPY260722_H_INCLUDED
#define FEATURESPY260722_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_FaceCollector.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>

#include "HuNXOpen.h"
#include "uf_all.h"

#include "afxdlgs.h "

#include "PublicFunctions.h"
#include "FeaturePublicClass.h"
#include "SpyFunctions.h"
#include "xml.h"
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport FeatureSpy260722
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    FeatureSpy260722();
    ~FeatureSpy260722();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the FeatureSpy.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
    //int AddCallback (NXOpen::BlockStyler::ListBox* list_box);
    //int DeleteCallback(NXOpen::BlockStyler::ListBox* list_box);

	//---------------------------------------------------------自定义函数--------------------------------------------------------
	int  GetDefaultColor();//待修改
	void GetInfomation();

	//环形槽识别
	/*void RemoveInnerLoopFace(std::vector<Face*> &RemoveFaceVector);*/
	/*void SearchInnerFaces(std::vector<Face*> SearchingFaces, std::vector<Face*> &SearchedFaces, Face* EndFace);*/
	//树列表相关函数
	void FeatureSpyResultDisplay();
	void GetSelectedIndexAndFeatureName(int &Index, NXString &FeaName);//树列表相关函数1
	void ResponseToFeatureList(int iRowIndex, NXString FeatureName);//树列表相关函数2
	//待修改
	void SetAllFeatureColor(int i);

	void SetAllBossColor(int Color);
	//---------单独点亮凸台一类特征
	void SetAllNormalBossColor(int Color);
	void SetAllNoSideBossColor(int Color);
	void SetAllDoubleLayerBossColor(int Color);
	//---------单独点亮凸台一类特征

	//设置槽颜色（待定）
	void SetAllGrooveColor(int Color);
	void SetCircularGroove0Color(int Color);
	void SetCircularGroove1Color(int Color);
	void SetSubsidenceGrooveColor(int Color);
	void SetPlanerBlindGrooveColor(int Color);
	void SetPassGrooveColor(int Color);

	/*void SetAllAnnulusCavityColor(int Color) ;*/
	/*void SetAllResidueColor(int Color) ;*/

	//设置颜色20230204-mql（筋）
	void SetAllDirectionRibColor(int Color);
	void SetAllRibColor(int Color);
	void SetAllHookFaceRibColor(int Color);

	//设置曲面槽筋特征颜色
	//设置颜色20230204-mql（轮廓）
	void SetAllOutLineColor(int Color);
	void SetInOutLineColor(int Color);
	void SetOutOutLineColor(int Color);

	//设置颜色20230204-fxy（孔）

	void Setother1HoleColor(int Color);
	void Setother2HoleColor(int Color);
	void Setother3HoleColor(int Color);

	void SetAllHoleColor(int Color);
	void SetDirectionNormalHoleColor(int Color);
	void SetDirectionRightHoleColor(int Color);
	void SetDirectionBlindHoleColor(int Color);

	void ColorDirectionStepThroughHole_31(int Color);
	void ColorDirectionLongRoundThroughHole_31(int Color);
	void ColorDirectionBlindHole_31(int Color);

	void SetWallNormalHoleColor(int Color);
	void SetWallCircleCombineHoleColor(int Color);
	void SetRibCombineHoleColor(int Color);

	void SetBossNormalHoleColor(int Color);
	void SetBossOneRightHoleColor(int Color);
	void SetBossOneCircleHoleColor(int Color);
	void SetBossDoubleRightHoleColor(int Color);
	void SetBossDoubleCircleHoleColor(int Color);
	void SetBossOneRightOneCircleHoleColor(int Color);

	void SetBossManyLayerHoleColor(int Color);
	void SetBossOutsideWideCombineHoleColor(int Color);
	void SetBossInsideWideCombineHoleColor(int Color);
	void SetBossMidCricleCombineHoleColor(int Color);
	void SetBossNormalBlindHoleColor(int Color);
	void SetBossRightBlindHoleColor(int Color);
	void CreateXmlFile();


	NXOpen::Part* workPart;
	Body * pSelectedBody;//selected body
	std::vector<NXOpen::Face*> pFaceList;//get all face in a selected body
	std::vector<NXOpen::Face*> pFaceAll_For_color;
	Face * pSelectedFace;//Selected joint face(Note:this face is the lowest face on a direction in a body)
	int DefaultColor;//所选面缺省颜色
	NXOpen::Vector3d _Approach_Normal;
	std::vector<Face*> AllFaces;
	Face* BottomPlaneFace;
	Face* TopPlaneFace;
	std::vector<Face*> ParallelPlaneFace;
	NXString NXStringName;  //部件名字
	NXString SelectionPathNXString; //路径名字
	NXOpen::Face* Begin_Face;//分型面
	NXString PartNameNXString;

	xml* _xml;
	IXMLDOMDocumentPtr pDocument;

	std::vector<NXOpen::Face*>AllFacesVector;//体上所有的面
	std::vector<Body*>SelectBodyVector;
	std::vector<Face*>SelectFaceVector;
	Body* PartBody;

	//树列表相关成员
	std::vector<NXString> FeatureSpyResultDisplayStringTitle;
	std::vector<NXString> FeatureSpyResultDisplayStringList;

	std::vector<NXString> GrooveClassflyList;//槽列表
	std::vector<NXString> BossClassflyList;//凸台列表
	std::vector<NXString> HoleClassflyList;//孔列表
	//New-------20230209-mql
	std::vector<NXString> OutlineClassList;
	std::vector<NXString> RibClassList;
	//特征识别结果
	/*std::vector<AnnulusCavity*> AnnulusCavitySpyResult;
	std::vector<SubsidenceCavity*> SubsidenceCavitySpyResult;
	std::vector<ArcCavity*> ArcCavitySpyResult;
	std::vector<Boss*> BossSpyResult;
	std::vector<Rib*> RibSpyResult;
	std::vector<Hole*> HoleSpyResult;
	std::vector<Residue*> ResidueSpyResult ;*/
	std::vector<bool> FeatureStateList;

	//凸台种子面20221219回家后加
	std::vector<NXOpen::Face*>SealFace_NormalBoss;
	std::vector<NXOpen::Face*>SealFace_NoSideBoss;
	std::vector<NXOpen::Face*>SealFace_DoubleLayerBoss;

	//凸台特征20221219回家后加
	std::vector<DoubleLayerBoss*>Feature_DoubleLayerBoss;
	std::vector<NoSideBoss*>Feature_NoSideBoss;
	std::vector<NormalBoss*>Feature_NormalBoss;

	//凸台特征20221221回家后加
	double _Approcah_Point[3];

	//孔种子面20230202加------------------------------------------------------
	//轴向孔种子面和特征
	std::vector<NXOpen::Face*>SealFace_DirectionNormalHole;//普通通孔
	std::vector<NXOpen::Face*>SealFace_DirectionRightHole;//倒斜角通孔
	std::vector<NXOpen::Face*>SealFace_DirectionBlindHole;//盲孔

	std::vector<DirectionNormalHole*>Feature_DirectionNormalHole;//普通通孔
	std::vector<DirectionRightHole*>Feature_DirectionRightHole;//倒斜角通孔
	std::vector<DirectionBlindHole*>Feature_DirectionBlindHole;//盲孔

	std::vector<DirectionStepThroughHole_31*>Feature_DirectionStepThroughHole;
	std::vector<DirectionLongRoundThroughHole_31*>Feature_DirectionLongRoundThroughHole;
	std::vector<DirectionBlindHole_31*>Feature_DirectionBlindHole_31;
	//筋和壁面孔种子面和特征
	std::vector<NXOpen::Face*>SealFace_WallNormalHole;//壁面通孔
	std::vector<NXOpen::Face*>SealFace_WallCircleCombineHole;//壁面倒斜角复合通孔
	std::vector<NXOpen::Face*>SealFace_RibCombineHole;//筋面复合孔

	std::vector<WallNormalHole*>Feature_WallNormalHole;//壁面通孔
	std::vector<WallCircleCombineHole*>Feature_WallCircleCombineHole;//壁面倒斜角复合通孔
	std::vector<RibCombineHole*>Feature_RibCombineHole;//筋面复合孔
	//std::vector<RibCombineHole*>Feature_RibotherHole;//筋面其它孔


	//凸台孔种子面
	std::vector<NXOpen::Face*>SealFace_BossNormalHole;//凸台通孔
	std::vector<NXOpen::Face*>SealFace_BossOneRightHole;//凸台单侧斜角通孔
	std::vector<NXOpen::Face*>SealFace_BossOneCircleHole;//凸台单侧圆角通孔
	std::vector<NXOpen::Face*>SealFace_BossDoubleRightHole;//凸台双侧斜角通孔
	std::vector<NXOpen::Face*>SealFace_BossDoubleCircleHole;//凸台双侧圆角通孔
	std::vector<NXOpen::Face*>SealFace_BossOneRightOneCircleHole;//凸台单侧直角单侧圆角通孔

	std::vector<NXOpen::Face*>SealFace_BossManyLayerHole;//凸台多层通孔
	std::vector<NXOpen::Face*>SealFace_BossOutsideWideCombineHole;//凸台外宽内窄复合通孔
	std::vector<NXOpen::Face*>SealFace_BossInsideWideCombineHole;//凸台内宽外窄复合通孔
	std::vector<NXOpen::Face*>SealFace_BossMidCricleCombineHole;//凸台中间倒圆角复合通孔
	std::vector<NXOpen::Face*>SealFace_BossNormalBlindHole;//凸台无倒角盲孔
	std::vector<NXOpen::Face*>SealFace_BossRightBlindHole;//凸台倒斜角盲孔

	std::vector<NXOpen::Face*>SealFace_otherHole1;//其他孔 一个壁面（内外都不是完整圆弧 2边）
	std::vector<NXOpen::Face*>SealFace_otherHole2;//其他孔 一个壁面，一个内侧面 （外侧非完整圆弧，内侧完整圆弧，相邻倒角或倒圆 2边）/ （内外都为圆弧，但倒角倒圆在内侧 2边）
	std::vector<NXOpen::Face*>SealFace_otherHole3;//其他孔 3边 一个壁面，外侧为完整圆弧，一个外侧相邻面（任意面）

	std::vector<Other1Hole*>Feature_otherHole1;//其他孔 一个壁面（内外都不是完整圆弧 2边）
	std::vector<Other2Hole*>Feature_otherHole2;//其他孔 一个壁面，一个内侧面 （外侧非完整圆弧，内侧完整圆弧，相邻倒角或倒圆 2边）/ （内外都为圆弧，但倒角倒圆在内侧 2边）
	std::vector<Other3Hole*>Feature_otherHole3;//其他孔 3边 一个壁面，外侧为完整圆弧，一个外侧相邻面（任意面）


	std::vector<BossNormalHole*>Feature_BossNormalHole;
	std::vector<BossOneRightHole*>Feature_BossOneRightHole;
	std::vector<BossOneCircleHole*>Feature_BossOneCircleHole;
	std::vector<BossDoubleRightHole*>Feature_BossDoubleRightHole;
	std::vector<BossDoubleCircleHole*>Feature_BossDoubleCircleHole;
	std::vector<BossOneRightOneCircleHole*>Feature_BossOneRightOneCircleHole;
	std::vector<BossManyLayerHole*>Feature_BossManyLayerHole;

	std::vector<BossOutsideWideCombineHole*>Feature_BossOutsideWideCombineHole;
	std::vector<BossInsideWideCombineHole*>Feature_BossInsideWideCombineHole;
	std::vector<BossMidCricleCombineHole*>Feature_BossMidCricleCombineHole;
	std::vector<BossNormalBlindHole*>Feature_BossNormalBlindHole;
	std::vector<BossRightBlindHole*>Feature_BossRightBlindHole;

	//环形槽种子面和特征0为内侧，1为外侧
	std::vector<NXOpen::Face*>SealFace_CircularGroove0;
	std::vector<CircularGroove*>Feature_CircularGroove0;
	std::vector<NXOpen::Face*>SealFace_CircularGroove1;
	std::vector<CircularGroove*>Feature_CircularGroove1;
	//下陷槽（曲面槽）种子面和特征
	std::vector<NXOpen::Face*>SealFace_SubsidenceGroove;
	std::vector<SubsidenceGroove*>Feature_SubsidenceGroove;
	//下陷槽筋
	std::vector<NXOpen::Face*>SealFace_HookFaceRib;
	std::vector<HookFaceRib*>Feature_HookFaceRib;
	//平面浅槽种子面和特征
	std::vector<NXOpen::Face*>SealFace_PlanerBlindGroove;
	std::vector<PlanerBlindGroove*>Feature_PlanerBlindGroove;
	//通槽种子面和特征
	std::vector<NXOpen::Face*>SealFace_PassGroove;
	std::vector<PassGroove*>Feature_PassGroove;

	//筋特征----------------------20230207-mql
	std::vector<NXOpen::Face*>SealFace_NoLimitRib;
	std::vector<NXOpen::Face*>SealFace_BossLimitRib;
	std::vector<NXOpen::Face*>SealFace_SideLimitRib;
	std::vector<NXOpen::Face*>SealFace_DirectionRib;

	std::vector<NoLimitRib*>Feature_NoLimitRib;
	std::vector<BossLimitRib*>Feature_BossLimitRib;
	std::vector<SideLimitRib*>Feature_SideLimitRib;
	std::vector<DirectionRib*>Feature_DirectionRib;

	//轮廓特征---------------20230203-mql
	std::vector<Face*>SeelFaces_OutlineVector;
	std::vector<Outline*>Feature_OutlineVector;
	std::vector<Face*>SeelFaces_OutlineVector1;
	std::vector<Outline*>Feature_OutlineVector1;

	//筋-fxy-0726
	int selectNumber = 0;


private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* bodySelect0;// Block type: Body Collector
    NXOpen::BlockStyler::FaceCollector* face_select0;// Block type: Face Collector
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum0;// Block type: Enumeration
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::ListBox* list_box0;// Block type: List Box
    NXOpen::BlockStyler::Button* button01;// Block type: Button
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum01;// Block type: Enumeration
    NXOpen::BlockStyler::Button* button02;// Block type: Button
    
};
#endif //FEATURESPY260722_H_INCLUDED
#include"PublicFunctions.cpp"